## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('Skin_NonSkin.txt', header = None, delimiter = r"\s+")
dataset.shape

(245057, 4)

In [3]:
dataset.head()

0   1    2  3
0  74  85  123  1
1  73  84  122  1
2  72  83  121  1
3  70  81  119  1
4  70  81  119  1

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:3].values
Y = dataset.iloc[:, 3].values

In [5]:
X.shape

(245057, 3)

In [6]:
Y.shape

(245057,)

In [7]:
X

array([[ 74,  85, 123],
       [ 73,  84, 122],
       [ 72,  83, 121],
       ..., 
       [163, 162, 112],
       [163, 162, 112],
       [255, 255, 255]], dtype=int64)

In [8]:
Y

array([1, 1, 1, ..., 2, 2, 2], dtype=int64)

## Preprocess the Data

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)

In [12]:
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [13]:
sc_X = StandardScaler()

In [14]:
X = sc_X.fit_transform(X)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [15]:
X

array([[-0.82025564, -0.79256715, -0.00244137],
       [-0.83631847, -0.8092502 , -0.01622268],
       [-0.8523813 , -0.82593325, -0.030004  ],
       ..., 
       [ 0.60933634,  0.49202777, -0.15403583],
       [ 0.60933634,  0.49202777, -0.15403583],
       [ 2.08711681,  2.04355149,  1.81669219]])

## Create Train and Test Data

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [18]:
X_train.shape

(196045, 3)

In [19]:
X_test.shape

(49012, 3)

In [20]:
Y_train.shape

(196045,)

In [21]:
Y_test.shape

(49012,)

In [22]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
1  155428
0   40617

In [23]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
1  38770
0  10242

## Create and train the ANN Classifier

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 3))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=3, activation="relu", units=8, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
196045/196045 [==============================] - 10s - loss: 0.0557 - acc: 0.9808    - ETA: 7s - loss: 0.1593 - ac - ETA: 7s - loss: 0.1457 - ac - ETA: 6s - loss: 0.1326 -  - ETA: 6s - loss: 0.1193 -  - E
Epoch 2/100
196045/196045 [==============================] - 9s - loss: 0.0078 - acc: 0.9983     
Epoch 3/100
196045/196045 [==============================] - 10s - loss: 0.0066 - acc: 0.9985    - ETA: 9s - loss: 0.0054 -  - ETA: 7s - loss: 0.0069 - acc: - E - ETA: - ETA: 1s - lo - ETA: 0s - loss: 0.0066 - acc: 0.9
Epoch 4/100
196045/196045 [==============================] - 9s - loss: 0.0062 - acc: 0.9986     - ETA: 0s - loss: 0.0061 - a - ETA: 0s - loss: 0.0062 - acc: 0.998
Epoch 5/100
196045/196045 [==============================] - 10s - loss: 0.0058 - acc: 0.9987    - ETA: 1s - los - ETA: 0s - loss: 0.0058 - acc: 0.99
Epoch 6/100
196045/196045 [==============================] - 10s - loss: 0.0053 - acc: 0.9988    - - ET
Epoch 7/100
196045/196045 [=====================

196045/196045 [==============================] - 13s - loss: 0.0032 - acc: 0.9993      ET - ETA: 9 - ETA: 7s - loss: 0.0035  - ETA: 6s - loss: 0.0035 - acc: 0.9 - ETA: 6s - loss: 0.0034 - acc: 0 - ETA: 6s - loss: 0.003 - ETA: 5s - loss - ETA: 4s - loss: 0.0033 - acc: 0.99 - ETA: 4s - loss: 0.0032 - acc:  - ETA: 4s - los - ETA: 2s - loss: 0.0 - ETA: 1s - - ETA: 0s - loss: 0.0033 - 
Epoch 48/100
196045/196045 [==============================] - 13s - loss: 0.0031 - acc: 0.9993      ETA: 10s - loss:  - ETA: 10s - loss: 0 - ETA: 9s - loss: - ETA: 8s - loss: 0.0028 -  - ETA: 8s - loss: 0.0029 - acc: 0.999 - ETA: 8s - loss: 0.003 - ETA: 7s - loss: 0.0032 - - ETA: 2s - loss: 0.0 - ETA: 1s - loss: 0.003 - ETA: 1s - los
Epoch 49/100
196045/196045 [==============================] - 13s - loss: 0.0031 - acc: 0.9992    - ETA: 8s - los - ETA: 3s - loss: 0.0031 - acc: 0.9 - ETA: 3s - loss: 0.0031 - acc:  - ETA: 2s - loss: 0.0031 - a - ETA: 2s - loss: 0.0 - ETA: 1s - loss: 0.0031 - ac - ETA: 1s - loss

196045/196045 [==============================] - 13s - loss: 0.0030 - acc: 0.9993    - ETA: 9s - loss: 0.0033 - a - ETA: 4s - loss: 0.0032 - acc: 0 - ETA: 4s - loss: 0.0032 - ETA: 3s - loss: 0.0031 -  - ETA: 3s - loss: 0.003 - ETA: 2s - loss: 0.0030 - acc - ETA: 1s - loss: 0.0031 - acc: 0.99 - ETA: - ETA: 0s - loss: 0.0030 - acc: 0.999
Epoch 90/100
196045/196045 [==============================] - 13s - loss: 0.0031 - acc: 0.9993      ETA: 12s - loss: 0.0043 - - - ETA: 7s - loss: 0.0032 - ac - ETA: 6s - loss: 0.0032 - acc: 0.9 - ETA: 4s - loss: 0.0034  - ETA: 4s - loss: 0.0033 - acc: 0 - ETA: 3s - loss: 0.0033 - ac - ETA: 3s - loss: 0.0033 - acc: 0.999 - ETA: 3s - loss: 0.0032 - acc: 0.99 - ETA: 3s - loss: 0.0032 - acc: - ETA: 2s - loss: 0.0032 - acc - ETA: 2s - loss: 0.0032 - acc - E - ETA: 0s - loss: 0.0031 - acc: 
Epoch 91/100
196045/196045 [==============================] - 13s - loss: 0.0030 - acc: 0.9993          - ETA: 19s - l - ETA: 12s - loss: 0.0015 - acc:  - ETA: 12s - lo - E

In [26]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [28]:
accuracy_score(Y_pred, Y_test)

0.99940830816942794

In [29]:
confusion_matrix(Y_pred, Y_test)

array([[10240,    27],
       [    2, 38743]], dtype=int64)