## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('Skin_NonSkin.txt', header = None, delimiter = r"\s+")
dataset.shape

(245057, 4)

In [3]:
dataset.head()

0   1    2  3
0  74  85  123  1
1  73  84  122  1
2  72  83  121  1
3  70  81  119  1
4  70  81  119  1

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:3].values
Y = dataset.iloc[:, 3].values

In [5]:
X.shape

(245057, 3)

In [6]:
Y.shape

(245057,)

In [7]:
X[0]

array([ 74,  85, 123], dtype=int64)

In [8]:
Y[0]

1

## Preprocess the Data

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)

In [12]:
Y[0]

0

In [13]:
sc_X = StandardScaler()

In [14]:
X = sc_X.fit_transform(X)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [15]:
X[0]

array([-0.82025564, -0.79256715, -0.00244137])

## Create Train and Test Data

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [18]:
X_train.shape

(196045, 3)

In [19]:
X_test.shape

(49012, 3)

In [20]:
Y_train.shape

(196045,)

In [21]:
Y_test.shape

(49012,)

In [22]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
1  155428
0   40617

In [23]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
1  38770
0  10242

## Create and train the ANN Classifier

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 3))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=3, activation="relu", units=8, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
196045/196045 [==============================] - 9s - loss: 0.1016 - acc: 0.9631     - ETA: 2s - loss: 0.124 - ETA: 1s - loss: 0.1169 - a - ETA: 1s - loss - ETA: 0s - loss: 0.1021 - acc: 0.96
Epoch 2/100
196045/196045 [==============================] - 9s - loss: 0.0089 - acc: 0.9983     - ETA: 2s - ETA: 0s - loss: 0.0
Epoch 3/100
196045/196045 [==============================] - 9s - loss: 0.0064 - acc: 0.9986     
Epoch 4/100
196045/196045 [==============================] - 9s - loss: 0.0058 - acc: 0.9988     
Epoch 5/100
196045/196045 [==============================] - 9s - loss: 0.0055 - acc: 0.9987     - ETA: 8s - lo - ETA: 7s - loss: 0 - E - ETA: 4s - loss: 0.0059 - - E - ETA: 2s - loss: 0.0 - ET
Epoch 6/100
196045/196045 [==============================] - 9s - loss: 0.0054 - acc: 0.9987     - ETA: 1s - loss: 0 - ETA: 0s - loss: 0.0054 - acc: 0.99
Epoch 7/100
196045/196045 [==============================] - 9s - loss: 0.0053 - acc: 0.9988     - ETA: 1s - loss: 0.0053 -

196045/196045 [==============================] - 9s - loss: 0.0041 - acc: 0.9990     - ETA: 1s - loss:  - ETA: 0s - loss: 0.0042 - acc
Epoch 55/100
196045/196045 [==============================] - 9s - loss: 0.0041 - acc: 0.9990     
Epoch 56/100
196045/196045 [==============================] - 9s - loss: 0.0040 - acc: 0.9991     - ETA: 1s - l - ETA: 0s - loss: 0.0040 - acc: 0.999
Epoch 57/100
196045/196045 [==============================] - 9s - loss: 0.0039 - acc: 0.9991     - ETA: 2s - loss: 0.0041 - a - ETA: 2s - loss: 0.0041 - a
Epoch 58/100
196045/196045 [==============================] - 9s - loss: 0.0039 - acc: 0.9991     - ET - ETA: 4s - loss: 0.0033 - acc: 0 - ETA: 4s - loss: 0.0034 - a - ETA: 1s - loss: 0.0038 - acc: 0.999 -
Epoch 59/100
196045/196045 [==============================] - 9s - loss: 0.0037 - acc: 0.9991     
Epoch 60/100
196045/196045 [==============================] - 9s - loss: 0.0038 - acc: 0.9991     - ETA: 1s - loss: 0.0036 - ac - ETA: 0s - loss: 0.0
Epoch

In [26]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [28]:
accuracy_score(Y_test, Y_pred)

0.99938790500285646

In [29]:
confusion_matrix(Y_test, Y_pred)

array([[10242,     0],
       [   30, 38740]], dtype=int64)