## Initialization

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [3]:
model_accuracies = {'LogReg':1, 'DT':1, 'RF':1, 'LinearSVC':1, 'KernelSVC':1, 'NB':1, 'KNN':1}

## Importing the data

In [4]:
dataset = pd.read_csv('Skin_NonSkin.txt', header = None, delimiter = r'\s+')
dataset.shape

(245057, 4)

In [5]:
dataset.head()

0   1    2  3
0  74  85  123  1
1  73  84  122  1
2  72  83  121  1
3  70  81  119  1
4  70  81  119  1

## Create X and Y

In [6]:
X = dataset.iloc[:, 0:3].values
Y = dataset.iloc[:, 3].values

In [7]:
X.shape

(245057, 3)

In [8]:
Y.shape

(245057,)

In [9]:
X

array([[ 74,  85, 123],
       [ 73,  84, 122],
       [ 72,  83, 121],
       ..., 
       [163, 162, 112],
       [163, 162, 112],
       [255, 255, 255]], dtype=int64)

In [10]:
Y

array([1, 1, 1, ..., 2, 2, 2], dtype=int64)

## Preprocess the Data

In [11]:
le_Y = LabelEncoder()

In [12]:
Y = le_Y.fit_transform(Y)

In [13]:
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [14]:
sc_X = StandardScaler()

In [15]:
X = sc_X.fit_transform(X)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [16]:
X

array([[-0.82025564, -0.79256715, -0.00244137],
       [-0.83631847, -0.8092502 , -0.01622268],
       [-0.8523813 , -0.82593325, -0.030004  ],
       ..., 
       [ 0.60933634,  0.49202777, -0.15403583],
       [ 0.60933634,  0.49202777, -0.15403583],
       [ 2.08711681,  2.04355149,  1.81669219]])

## Create Train and Test Data

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [18]:
X_train.shape

(196045, 3)

In [19]:
X_test.shape

(49012, 3)

In [20]:
Y_train.shape

(196045,)

In [21]:
Y_test.shape

(49012,)

In [22]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
1  155428
0   40617

In [23]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
1  38770
0  10242

## DecisionTree

In [24]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [25]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [26]:
Y_pred_dt = clf_dt.predict(X_test)

In [27]:
confusion_matrix(Y_pred_dt, Y_test)

array([[10223,    16],
       [   19, 38754]], dtype=int64)

## Random Forest

In [28]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [29]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [30]:
Y_pred_rf = clf_rf.predict(X_test)

In [31]:
confusion_matrix(Y_pred_rf, Y_test)

array([[10234,    30],
       [    8, 38740]], dtype=int64)

## Naive Bayes

In [32]:
clf_nb = GaussianNB()

In [33]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [34]:
Y_pred_nb = clf_nb.predict(X_test)

In [35]:
confusion_matrix(Y_pred_nb, Y_test)

array([[ 7466,  1068],
       [ 2776, 37702]], dtype=int64)

## KNN

In [36]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [37]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [38]:
Y_pred_knn = clf_knn.predict(X_test)

In [39]:
confusion_matrix(Y_pred_knn, Y_test)

array([[10240,    18],
       [    2, 38752]], dtype=int64)

## Logistic Regression

In [40]:
clf_lr = LogisticRegression()

In [41]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [42]:
Y_pred_lr = clf_lr.predict(X_test)

In [43]:
confusion_matrix(Y_pred_lr, Y_test)

array([[ 8406,  2186],
       [ 1836, 36584]], dtype=int64)

## Linear SVC

In [44]:
clf_lsvc = SVC(kernel = 'linear')

In [45]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [46]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [47]:
confusion_matrix(Y_pred_lsvc, Y_test)

array([[ 9629,  2860],
       [  613, 35910]], dtype=int64)

## Kernel SVC

In [48]:
clf_ksvc = SVC(kernel = 'rbf')

In [49]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [50]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [51]:
confusion_matrix(Y_pred_ksvc, Y_test)

array([[10242,    87],
       [    0, 38683]], dtype=int64)

## Accuracy of Various Models

In [52]:
model_accuracies['DT'] = accuracy_score(Y_pred_dt, Y_test)
model_accuracies['KNN'] = accuracy_score(Y_pred_knn, Y_test)
model_accuracies['KernelSVC'] = accuracy_score(Y_pred_ksvc, Y_test)
model_accuracies['LinearSVC'] = accuracy_score(Y_pred_lsvc, Y_test)
model_accuracies['LogReg'] = accuracy_score(Y_pred_lr, Y_test)
model_accuracies['NB'] = accuracy_score(Y_pred_nb, Y_test)
model_accuracies['RF'] = accuracy_score(Y_pred_rf, Y_test)
model_accuracies

{'DT': 0.99928588916999916,
 'KNN': 0.99959193666857094,
 'KernelSVC': 0.99822492450828371,
 'LinearSVC': 0.92913980249734762,
 'LogReg': 0.91793846404962054,
 'NB': 0.92157022769933894,
 'RF': 0.99922467967028483}