## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df = pd.read_csv('balance-scale.data', header = None)
df.shape

(625, 5)

In [6]:
df.head()

0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5

## Creating X and Y

In [7]:
X = df.iloc[:, 1:5].values
Y = df.iloc[:, 0].values

In [8]:
X

array([[1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 3],
       ..., 
       [5, 5, 5, 3],
       [5, 5, 5, 4],
       [5, 5, 5, 5]], dtype=int64)

In [9]:
Y

array(['B', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'L',
       'B', 'R', 'R', 'R', 'B', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'L',
       'B', 'R', 'R', 'L', 'R', 'R', 'R', 'R', 'B', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'L',
       'B', 'R', 'L', 'B', 'R', 'R', 'R', 'L', 'R', 'R', 'R', 'R', 'B',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'L', 'L',
       'B', 'L', 'L', 'R', 'R', 'R', 'L', 'R', 'R', 'R', 'R', 'L', 'R',
       'R', 'R', 'R', 'B', 'R', 'R', 'R', 'R', 'L', 'B', 'R', 'R', 'R',
       'B', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'L', 'B', 'R', 'L',
       'B', 'R', 'R', 'R', 'L', 'R', 'R', 'R', 'R', 'B', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'L', 'L', 'L', 'L

## Preprocess the Data

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)
Y

array([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 1, 0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 1, 0, 2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0, 2, 1, 0, 2, 2, 2, 1,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2,
       2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 1, 1, 0,
       2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 1,

## Create Train and Test data

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [13]:
X_train.shape

(500, 4)

In [14]:
X_test.shape

(125, 4)

In [15]:
Y_train.shape

(500,)

In [16]:
Y_test.shape

(125,)

In [17]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
2  230
1  230
0   40

In [18]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
2  58
1  58
0   9

## Decision Tree Classifier

In [19]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [20]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [21]:
Y_pred_dt = clf_dt.predict(X_test)

In [22]:
cm_dt = confusion_matrix(Y_pred_dt, Y_test)
cm_dt

array([[ 0,  5,  7],
       [ 4, 50,  1],
       [ 5,  3, 50]], dtype=int64)

## Random Forest Classifier

In [23]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [24]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [25]:
Y_pred_rf = clf_rf.predict(X_test)

In [26]:
cm_rf = confusion_matrix(Y_pred_rf, Y_test)
cm_rf

array([[ 0,  2,  5],
       [ 5, 54,  2],
       [ 4,  2, 51]], dtype=int64)

## Naive Bayes Classifier

In [27]:
clf_nb = GaussianNB()

In [28]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [29]:
Y_pred_nb = clf_nb.predict(X_test)

In [30]:
cm_nb = confusion_matrix(Y_pred_nb, Y_test)
cm_nb

array([[ 0,  0,  0],
       [ 6, 57,  2],
       [ 3,  1, 56]], dtype=int64)

## KNN Classifier

In [31]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [32]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [33]:
Y_pred_knn = clf_knn.predict(X_test)

In [34]:
cm_knn = confusion_matrix(Y_pred_knn, Y_test)
cm_knn

array([[ 0,  1,  5],
       [ 4, 54,  2],
       [ 5,  3, 51]], dtype=int64)

## Logistic Regression

In [35]:
clf_lr = LogisticRegression()

In [36]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [37]:
Y_pred_lr = clf_lr.predict(X_test)

In [38]:
cm_lr = confusion_matrix(Y_pred_lr, Y_test)
cm_lr

array([[ 0,  0,  0],
       [ 2, 54,  2],
       [ 7,  4, 56]], dtype=int64)

## SVC Linear

In [39]:
clf_lsvc = SVC(kernel = "linear")

In [40]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [41]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [42]:
cm_lsvc = confusion_matrix(Y_pred_lsvc, Y_test)
cm_lsvc

array([[ 8,  5,  2],
       [ 0, 52,  2],
       [ 1,  1, 54]], dtype=int64)

## SVC Kernel

In [43]:
clf_ksvc = SVC(kernel = "rbf")

In [44]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [45]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [46]:
cm_ksvc = confusion_matrix(Y_pred_ksvc, Y_test)
cm_ksvc

array([[ 0,  0,  0],
       [ 2, 55,  0],
       [ 7,  3, 58]], dtype=int64)

## Accuracy of Various Classifiers

In [47]:
model_accuracies['DT'] = accuracy_score(Y_pred_dt, Y_test)
model_accuracies['KNN'] = accuracy_score(Y_pred_knn, Y_test)
model_accuracies['KernelSVC'] = accuracy_score(Y_pred_ksvc, Y_test)
model_accuracies['LinearSVC'] = accuracy_score(Y_pred_lsvc, Y_test)
model_accuracies['LogReg'] = accuracy_score(Y_pred_lr, Y_test)
model_accuracies['NB'] = accuracy_score(Y_pred_nb, Y_test)
model_accuracies['RF'] = accuracy_score(Y_pred_rf, Y_test)
model_accuracies

{'DT': 0.80000000000000004,
 'KNN': 0.83999999999999997,
 'KernelSVC': 0.90400000000000003,
 'LinearSVC': 0.91200000000000003,
 'LogReg': 0.88,
 'NB': 0.90400000000000003,
 'RF': 0.83999999999999997}