## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("balance-scale.data", header = None)

In [3]:
X = dataset.iloc[:, 1:5].values
Y = dataset.iloc[:, 0].values

In [4]:
dataset.head()

0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5

## Preprocess the Data

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)

In [6]:
ohe = OneHotEncoder(categorical_features=[0])
Y = ohe.fit_transform(Y).toarray()

In [7]:
Y

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       ..., 
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])

In [8]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
X

array([[-1.41421356, -1.41421356, -1.41421356, -1.41421356],
       [-1.41421356, -1.41421356, -1.41421356, -0.70710678],
       [-1.41421356, -1.41421356, -1.41421356,  0.        ],
       ..., 
       [ 1.41421356,  1.41421356,  1.41421356,  0.        ],
       [ 1.41421356,  1.41421356,  1.41421356,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356]])

## Create Train and Test Data

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [11]:
from keras.models import Sequential
from keras.layers import Dense

clf_ann = Sequential()

In [12]:
# First Hidden Layer
clf_ann.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu', input_dim = 4))

# Output Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", input_dim=4, units=5, activation="relu")`
  from ipykernel import kernelapp as app
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=3, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
500/500 [==============================] - 0s - loss: 1.0707 - acc: 0.6180     
Epoch 2/200
500/500 [==============================] - 0s - loss: 0.9316 - acc: 0.8660     
Epoch 3/200
500/500 [==============================] - 0s - loss: 0.7046 - acc: 0.8800     
Epoch 4/200
500/500 [==============================] - 0s - loss: 0.5348 - acc: 0.8780     
Epoch 5/200
500/500 [==============================] - 0s - loss: 0.4440 - acc: 0.8740     
Epoch 6/200
500/500 [==============================] - 0s - loss: 0.3948 - acc: 0.8800     
Epoch 7/200
500/500 [==============================] - 0s - loss: 0.3654 - acc: 0.8700     
Epoch 8/200
500/500 [==============================] - 0s - loss: 0.3458 - acc: 0.8720     
Epoch 9/200
500/500 [==============================] - 0s - loss: 0.3306 - acc: 0.8720     
Epoch 10/200
500/500 [==============================] - 0s - loss: 0.3196 - acc: 0.8720     
Epoch 11/200
500/500 [==============================] - 0s - loss: 0.3108 - acc

500/500 [==============================] - 0s - loss: 0.2452 - acc: 0.9160     
Epoch 90/200
500/500 [==============================] - 0s - loss: 0.2451 - acc: 0.9140     
Epoch 91/200
500/500 [==============================] - 0s - loss: 0.2452 - acc: 0.9180     
Epoch 92/200
500/500 [==============================] - 0s - loss: 0.2457 - acc: 0.9180     
Epoch 93/200
500/500 [==============================] - 0s - loss: 0.2447 - acc: 0.9160     
Epoch 94/200
500/500 [==============================] - 0s - loss: 0.2451 - acc: 0.9160     
Epoch 95/200
500/500 [==============================] - 0s - loss: 0.2444 - acc: 0.9160     
Epoch 96/200
500/500 [==============================] - 0s - loss: 0.2447 - acc: 0.9140     
Epoch 97/200
500/500 [==============================] - 0s - loss: 0.2453 - acc: 0.9180     
Epoch 98/200
500/500 [==============================] - 0s - loss: 0.2450 - acc: 0.9140     
Epoch 99/200
500/500 [==============================] - 0s - loss: 0.2457 - acc: 0.

500/500 [==============================] - 0s - loss: 0.2438 - acc: 0.9180     
Epoch 177/200
500/500 [==============================] - 0s - loss: 0.2431 - acc: 0.9160     
Epoch 178/200
500/500 [==============================] - 0s - loss: 0.2435 - acc: 0.9160     
Epoch 179/200
500/500 [==============================] - 0s - loss: 0.2429 - acc: 0.9180     
Epoch 180/200
500/500 [==============================] - 0s - loss: 0.2433 - acc: 0.9160     
Epoch 181/200
500/500 [==============================] - 0s - loss: 0.2432 - acc: 0.9120     
Epoch 182/200
500/500 [==============================] - 0s - loss: 0.2432 - acc: 0.9160     
Epoch 183/200
500/500 [==============================] - 0s - loss: 0.2438 - acc: 0.9180     
Epoch 184/200
500/500 [==============================] - 0s - loss: 0.2436 - acc: 0.9220     
Epoch 185/200
500/500 [==============================] - 0s - loss: 0.2432 - acc: 0.9160     
Epoch 186/200
500/500 [==============================] - 0s - loss: 0.2439

In [13]:
# Test the Classifier on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred_class, Y_test_class)

0.91200000000000003

In [15]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[ 6,  5,  0],
       [ 0, 52,  2],
       [ 3,  1, 56]], dtype=int64)