## Initialization

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [3]:
model_accuracies = {'LogReg':1, 'DT':1, 'RF':1, 'LinearSVC':1, 'KernelSVC':1, 'NB':1, 'KNN':1}

## Importing the data

In [4]:
dataset = pd.read_csv('Dataset.csv', delimiter=';')
dataset.shape

(165633, 19)

In [5]:
dataset.head()

user gender  age  how_tall_in_meters  weight  body_mass_index  x1  y1  \
0  debora  Woman   46                1.62      75             28.6  -3  92   
1  debora  Woman   46                1.62      75             28.6  -3  94   
2  debora  Woman   46                1.62      75             28.6  -1  97   
3  debora  Woman   46                1.62      75             28.6  -2  96   
4  debora  Woman   46                1.62      75             28.6  -1  96   

   z1  x2  y2  z2  x3   y3  z3   x4   y4   z4    class  
0 -63 -23  18 -19   5  104 -92 -150 -103 -147  sitting  
1 -64 -21  18 -18 -14  104 -90 -149 -104 -145  sitting  
2 -61 -12  20 -15 -13  104 -90 -151 -104 -144  sitting  
3 -57 -15  21 -16 -13  104 -89 -153 -103 -142  sitting  
4 -61 -13  20 -15 -13  104 -89 -153 -104 -143  sitting

## Create X and Y

In [6]:
X = dataset.iloc[:, 1:18].values
Y = dataset.iloc[:, 18].values

In [7]:
X.shape

(165633, 17)

In [8]:
Y.shape

(165633,)

In [9]:
X[0]

array(['Woman', 46, 1.62, 75, 28.6, -3, 92, -63, -23, 18, -19, 5, 104, -92,
       -150, -103, -147], dtype=object)

In [10]:
Y[0]

'sitting'

## Preprocess the Data

In [11]:
le_Y = LabelEncoder()

In [12]:
Y = le_Y.fit_transform(Y)

In [13]:
Y[0]

0

In [14]:
le_X = LabelEncoder()

In [15]:
X[:, 0] = le_X.fit_transform(X[:, 0])

In [16]:
X[0]

array([1, 46, 1.62, 75, 28.6, -3, 92, -63, -23, 18, -19, 5, 104, -92, -150,
       -103, -147], dtype=object)

In [17]:
sc_X = StandardScaler()

In [18]:
X = sc_X.fit_transform(X)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [19]:
X[0]

array([ 0.79616611,  0.58668263, -0.37319438,  0.37007877,  0.80496163,
        0.31415835,  0.15510422,  0.76541851,  0.38261059,  0.3415156 ,
        0.80934764, -0.23603041, -0.00954964,  0.0414573 ,  0.46047725,
       -0.51955844,  0.95687879])

## Create Train and Test Data

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [21]:
X_train.shape

(132506, 17)

In [22]:
X_test.shape

(33127, 17)

In [23]:
Y_train.shape

(132506,)

In [24]:
Y_test.shape

(33127,)

In [25]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  40443
2  37922
4  34751
3   9971
1   9419

In [26]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  10188
2   9448
4   8639
3   2444
1   2408

## DecisionTree

In [27]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [28]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [29]:
Y_pred_dt = clf_dt.predict(X_test)

In [30]:
confusion_matrix(Y_test, Y_pred_dt)

array([[10177,     3,     0,     6,     2],
       [    4,  2312,    11,    55,    26],
       [    0,     8,  9359,    25,    56],
       [    7,    68,    18,  2330,    21],
       [    1,    32,    75,    28,  8503]], dtype=int64)

## Random Forest

In [31]:
clf_rf = RandomForestClassifier(n_estimators = 100, criterion = 'entropy')

In [32]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [33]:
Y_pred_rf = clf_rf.predict(X_test)

In [34]:
confusion_matrix(Y_test, Y_pred_rf)

array([[10187,     1,     0,     0,     0],
       [    0,  2384,     7,    13,     4],
       [    0,     0,  9416,     9,    23],
       [    1,    25,     5,  2406,     7],
       [    0,     6,     6,     1,  8626]], dtype=int64)

## Naive Bayes

In [35]:
clf_nb = GaussianNB()

In [36]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [37]:
Y_pred_nb = clf_nb.predict(X_test)

In [38]:
confusion_matrix(Y_test, Y_pred_nb)

array([[9215,   84,  823,   64,    2],
       [ 217, 1382,  651,   31,  127],
       [  69,  119, 8730,   37,  493],
       [ 223,  503, 1031,  328,  359],
       [ 150,  352, 1786,  509, 5842]], dtype=int64)

## KNN

In [39]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [40]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [41]:
Y_pred_knn = clf_knn.predict(X_test)

In [42]:
confusion_matrix(Y_test, Y_pred_knn)

array([[10179,     1,     0,     6,     2],
       [    1,  2372,    15,    17,     3],
       [    1,     3,  9419,    18,     7],
       [    6,    48,    28,  2358,     4],
       [    1,    24,    89,    19,  8506]], dtype=int64)

## Logistic Regression

In [43]:
clf_lr = LogisticRegression()

In [44]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [45]:
Y_pred_lr = clf_lr.predict(X_test)

In [46]:
confusion_matrix(Y_test, Y_pred_lr)

array([[10140,    13,     0,    35,     0],
       [  187,  1267,   574,   246,   134],
       [    0,    19,  8134,    16,  1279],
       [  134,   355,   535,  1181,   239],
       [   14,    79,  1737,   150,  6659]], dtype=int64)

## Linear SVC

In [47]:
clf_lsvc = SVC(kernel = 'linear')

In [48]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [49]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [50]:
confusion_matrix(Y_test, Y_pred_lsvc)

array([[10133,    10,     0,    45,     0],
       [   63,  1867,   196,   206,    76],
       [    0,    82,  7939,    21,  1406],
       [   42,   251,   405,  1599,   147],
       [    3,   384,  1421,   106,  6725]], dtype=int64)

## Kernel SVC

In [51]:
clf_ksvc = SVC(kernel = 'rbf')

In [52]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [53]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [54]:
confusion_matrix(Y_test, Y_pred_ksvc)

array([[10175,     0,     0,    12,     1],
       [    5,  2336,    37,    21,     9],
       [    1,     3,  9386,    26,    32],
       [   11,    59,    51,  2312,    11],
       [    0,    24,   206,    17,  8392]], dtype=int64)

## Accuracy of Various Models

In [55]:
model_accuracies['DT'] = accuracy_score(Y_test, Y_pred_dt)
model_accuracies['KNN'] = accuracy_score(Y_test, Y_pred_knn)
model_accuracies['KernelSVC'] = accuracy_score(Y_test, Y_pred_ksvc)
model_accuracies['LinearSVC'] = accuracy_score(Y_test, Y_pred_lsvc)
model_accuracies['LogReg'] = accuracy_score(Y_test, Y_pred_lr)
model_accuracies['NB'] = accuracy_score(Y_test, Y_pred_nb)
model_accuracies['RF'] = accuracy_score(Y_test, Y_pred_rf)
model_accuracies

{'DT': 0.98653666193739242,
 'KNN': 0.99115525100371293,
 'KernelSVC': 0.98412171340598309,
 'LinearSVC': 0.85317112929030703,
 'LogReg': 0.8265463217315181,
 'NB': 0.76967428381682612,
 'RF': 0.99673981948259727}