## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('Dataset.csv', delimiter = ';')
dataset.shape

(165633, 19)

In [3]:
dataset.head()

user gender  age  how_tall_in_meters  weight  body_mass_index  x1  y1  \
0  debora  Woman   46                1.62      75             28.6  -3  92   
1  debora  Woman   46                1.62      75             28.6  -3  94   
2  debora  Woman   46                1.62      75             28.6  -1  97   
3  debora  Woman   46                1.62      75             28.6  -2  96   
4  debora  Woman   46                1.62      75             28.6  -1  96   

   z1  x2  y2  z2  x3   y3  z3   x4   y4   z4    class  
0 -63 -23  18 -19   5  104 -92 -150 -103 -147  sitting  
1 -64 -21  18 -18 -14  104 -90 -149 -104 -145  sitting  
2 -61 -12  20 -15 -13  104 -90 -151 -104 -144  sitting  
3 -57 -15  21 -16 -13  104 -89 -153 -103 -142  sitting  
4 -61 -13  20 -15 -13  104 -89 -153 -104 -143  sitting

## Create X and Y

In [4]:
X = dataset.iloc[:, 1:18].values
Y = dataset.iloc[:, 18].values

In [5]:
X.shape

(165633, 17)

In [6]:
Y.shape

(165633,)

In [7]:
X

array([['Woman', 46, 1.62, ..., -150, -103, -147],
       ['Woman', 46, 1.62, ..., -149, -104, -145],
       ['Woman', 46, 1.62, ..., -151, -104, -144],
       ..., 
       ['Man', 75, 1.67, ..., -185, -80, -153],
       ['Man', 75, 1.67, ..., -185, -84, -156],
       ['Man', 75, 1.67, ..., -210, -88, -148]], dtype=object)

In [8]:
Y

array(['sitting', 'sitting', 'sitting', ..., 'walking', 'walking',
       'walking'], dtype=object)

## Preprocess the Data

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)

In [12]:
Y

array([0, 0, 0, ..., 4, 4, 4], dtype=int64)

In [13]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [14]:
Y = ohe_Y.fit_transform(Y).toarray()

In [15]:
Y

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [16]:
le_X = LabelEncoder()

In [17]:
X[:, 0] = le_X.fit_transform(X[:, 0])

In [18]:
X

array([[1, 46, 1.62, ..., -150, -103, -147],
       [1, 46, 1.62, ..., -149, -104, -145],
       [1, 46, 1.62, ..., -151, -104, -144],
       ..., 
       [0, 75, 1.67, ..., -185, -80, -153],
       [0, 75, 1.67, ..., -185, -84, -156],
       [0, 75, 1.67, ..., -210, -88, -148]], dtype=object)

In [19]:
sc_X = StandardScaler()

In [20]:
X = sc_X.fit_transform(X)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [21]:
X

array([[ 0.79616611,  0.58668263, -0.37319438, ...,  0.46047725,
        -0.51955844,  0.95687879],
       [ 0.79616611,  0.58668263, -0.37319438, ...,  0.48657926,
        -0.56963719,  1.10815332],
       [ 0.79616611,  0.58668263, -0.37319438, ...,  0.43437524,
        -0.56963719,  1.18379059],
       ..., 
       [-1.25601929,  2.78631009,  0.57341349, ..., -0.45309309,
         0.63225278,  0.5030552 ],
       [-1.25601929,  2.78631009,  0.57341349, ..., -0.45309309,
         0.43193779,  0.2761434 ],
       [-1.25601929,  2.78631009,  0.57341349, ..., -1.10564333,
         0.23162279,  0.88124153]])

## Create Train and Test Data

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [24]:
X_train.shape

(132506, 17)

In [25]:
X_test.shape

(33127, 17)

In [26]:
Y_train.shape

(132506, 5)

In [27]:
Y_test.shape

(33127, 5)

## Create and train the ANN Classifier

In [28]:
from keras.models import Sequential
from keras.layers import Dense

In [34]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 11, init = 'uniform', activation = 'relu', input_dim = 17))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 11, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 5, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=17, units=11, kernel_initializer="uniform", activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=11, kernel_initializer="uniform", activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=5, kernel_initializer="uniform", activation="softmax")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
132506/132506 [==============================] - 7s - loss: 0.3085 - acc: 0.8929     - ETA: 6s - loss:  - ETA: 5s - loss - ETA: 0s - loss: 0.3150 - acc
Epoch 2/100
132506/132506 [==============================] - 6s - loss: 0.1506 - acc: 0.9557     
Epoch 3/100
132506/132506 [==============================] - 7s - loss: 0.1281 - acc: 0.9633     
Epoch 4/100
132506/132506 [==============================] - 6s - loss: 0.1159 - acc: 0.9670     
Epoch 5/100
132506/132506 [==============================] - 7s - loss: 0.1061 - acc: 0.9698     - ETA: - ETA: 2s - l - ETA: 0s - loss: 0.1071 - acc: 0.969 - ETA: 0s - loss: 0.
Epoch 6/100
132506/132506 [==============================] - 7s - loss: 0.0985 - acc: 0.9724     - ETA: 5s - loss: 0.1024 - ac - ETA: 4s - loss
Epoch 7/100
132506/132506 [==============================] - 7s - loss: 0.0934 - acc: 0.9739     - ETA:  - ETA: 1s - loss: 0.092 - ETA: 0s - loss: 0.09 - ETA: 0s - loss: 0.0933 - acc: 0.9
Epoch 8/100
132506/132506 [======

132506/132506 [==============================] - 9s - loss: 0.0653 - acc: 0.9821     - ETA: 7s - - ETA:  - ETA: 4s - loss: 0.0657 - acc: 0.981 - ETA: 4s - loss - ETA: 3s - loss: 0.0664 - acc - ETA: 3s -  - ETA: 0s - loss: 0.0653 - acc: 0.982 - ETA: 0s - loss: 0.0652 - acc: 0.9
Epoch 46/100
132506/132506 [==============================] - 9s - loss: 0.0648 - acc: 0.9820     - ETA: 8s - loss: 0.0591 - acc: 0.98 - ETA: 8s - loss: 0.0596 - acc: 0.983 - ETA: 8s - los - ETA: 4s - loss: 0.0647 - acc: 0.98 - ETA: - ETA: 3s - l
Epoch 47/100
132506/132506 [==============================] - 9s - loss: 0.0646 - acc: 0.9820     - ETA: 2s - loss: 0.0633 - acc: 0 - ETA: 2s - los - ETA: 1s - loss: 0.0643 - acc: 0.9 - ETA: 1s - loss: 0.0 - ETA: 0s - loss: 0.0639 -
Epoch 48/100
132506/132506 [==============================] - 9s - loss: 0.0646 - acc: 0.9822     - ETA: 8s - loss: 0. - ETA: 5s - loss: 0.0672 - acc: 0.982 - ETA: 5s - - ET - ETA: 0s - loss: 0
Epoch 49/100
132506/132506 [====================

132506/132506 [==============================] - 9s - loss: 0.0603 - acc: 0.9832     - ETA: 6s - loss: 0.0624 - ETA: 5s - loss - ETA: 0s - loss: 0.0607 - a
Epoch 77/100
132506/132506 [==============================] - 9s - loss: 0.0611 - acc: 0.9828     - ETA: 5s - loss: 0.0623 - ETA: 5s - loss: 0.0613 - ac - ETA: 4s - loss: 0.0614 -  - ETA: 4s - loss - ETA: 3s - lo - ETA: 1s - loss: 0.0604 - a - ETA: 1s - loss: 0 - ETA: 0s - loss: 0.0610 - acc
Epoch 78/100
132506/132506 [==============================] - 9s - loss: 0.0606 - acc: 0.9833     - ETA: 7s - loss: 0.0588 - acc: 0.984 - ETA: 7s - loss: 0.0593 - acc: 0 - ETA: 7s  - ETA: 5s - loss: 0.061 - ETA: 4s - loss: 0.0607 - ETA: 4s - loss: 0.0596 - acc - ETA: 3s - loss: 0.05 - ETA: 3s - loss: 0.0600 - acc: 0.983 - ETA: 3s - loss: 0.0600 - acc: 0 - ETA: 2s - loss: 0.0597 - - ETA: 2s -  - ETA: 0s - loss: 0.0605  - ETA: 0s - loss: 0.0608 - acc: 0
Epoch 79/100
132506/132506 [==============================] - 9s - loss: 0.0603 - acc: 0.9832  

In [35]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [36]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [37]:
accuracy_score(Y_pred_class, Y_test_class)

0.98300479971020616

In [38]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[10160,     2,     0,    10,     5],
       [    4,  2273,    11,    74,    45],
       [    0,    31,  9330,    33,    67],
       [   23,    72,    36,  2301,    22],
       [    1,    30,    71,    26,  8500]], dtype=int64)