## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('Dataset.csv', delimiter = ';')
dataset.shape

(165633, 19)

In [3]:
dataset.head()

user gender  age  how_tall_in_meters  weight  body_mass_index  x1  y1  \
0  debora  Woman   46                1.62      75             28.6  -3  92   
1  debora  Woman   46                1.62      75             28.6  -3  94   
2  debora  Woman   46                1.62      75             28.6  -1  97   
3  debora  Woman   46                1.62      75             28.6  -2  96   
4  debora  Woman   46                1.62      75             28.6  -1  96   

   z1  x2  y2  z2  x3   y3  z3   x4   y4   z4    class  
0 -63 -23  18 -19   5  104 -92 -150 -103 -147  sitting  
1 -64 -21  18 -18 -14  104 -90 -149 -104 -145  sitting  
2 -61 -12  20 -15 -13  104 -90 -151 -104 -144  sitting  
3 -57 -15  21 -16 -13  104 -89 -153 -103 -142  sitting  
4 -61 -13  20 -15 -13  104 -89 -153 -104 -143  sitting

## Create X and Y

In [4]:
X = dataset.iloc[:, 1:18].values
Y = dataset.iloc[:, 18].values

In [5]:
X.shape

(165633, 17)

In [6]:
Y.shape

(165633,)

In [7]:
X[0]

array(['Woman', 46, 1.62, 75, 28.6, -3, 92, -63, -23, 18, -19, 5, 104, -92,
       -150, -103, -147], dtype=object)

In [8]:
Y[0]

'sitting'

## Preprocess the Data

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)

In [12]:
Y[0]

0

In [13]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [14]:
Y = ohe_Y.fit_transform(Y).toarray()

In [15]:
Y[0]

array([ 1.,  0.,  0.,  0.,  0.])

In [16]:
le_X = LabelEncoder()

In [17]:
X[:, 0] = le_X.fit_transform(X[:, 0])

In [18]:
X[0]

array([1, 46, 1.62, 75, 28.6, -3, 92, -63, -23, 18, -19, 5, 104, -92, -150,
       -103, -147], dtype=object)

In [19]:
sc_X = StandardScaler()

In [20]:
X = sc_X.fit_transform(X)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [21]:
X[0]

array([ 0.79616611,  0.58668263, -0.37319438,  0.37007877,  0.80496163,
        0.31415835,  0.15510422,  0.76541851,  0.38261059,  0.3415156 ,
        0.80934764, -0.23603041, -0.00954964,  0.0414573 ,  0.46047725,
       -0.51955844,  0.95687879])

## Create Train and Test Data

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [24]:
X_train.shape

(132506, 17)

In [25]:
X_test.shape

(33127, 17)

In [26]:
Y_train.shape

(132506, 5)

In [27]:
Y_test.shape

(33127, 5)

## Create and train the ANN Classifier

In [28]:
from keras.models import Sequential
from keras.layers import Dense

In [29]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 11, init = 'uniform', activation = 'relu', input_dim = 17))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 11, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 5, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=11, kernel_initializer="uniform", activation="relu", input_dim=17)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=11)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="softmax", units=5)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
132506/132506 [==============================] - 7s - loss: 0.2972 - acc: 0.8914     - ETA: 2s - loss: 0.3509 - acc: 0.86 - ETA: 1s - loss:  - ETA: 1s - loss: 0.319 - ETA: 0s - loss: 0.3014 - acc: 0.
Epoch 2/100
132506/132506 [==============================] - 7s - loss: 0.1327 - acc: 0.9611     - ETA: 5s - loss: 0.1 - ETA: 0s - loss: 0.1338
Epoch 3/100
132506/132506 [==============================] - 7s - loss: 0.1114 - acc: 0.9683     - ETA: 5s - loss: 0. - ETA: 4s -  - ETA: 2s - loss: 0.1157 - acc: 0.9  - ETA: 0s - loss: 0.1127 - acc: 0.9 - ETA: 0s - loss: 0.
Epoch 4/100
132506/132506 [==============================] - 6s - loss: 0.1005 - acc: 0.9715      - ETA: 1s - loss: 0.0 - ETA: 0s - loss: 0.0991 - a - ETA: 0s - loss: 0.1002 - acc
Epoch 5/100
132506/132506 [==============================] - 7s - loss: 0.0946 - acc: 0.9733     - ETA: 6s - loss: 0.0952 - ac - ETA: 6s - loss - ETA: 5s - loss: 0.0912 - acc: 0.97 - ETA: 5s - loss: 0.0912  - ETA: 4s - loss: 0.0923 - acc -

132506/132506 [==============================] - 10s - loss: 0.0672 - acc: 0.9818    - ETA: 8s - loss:  - ETA: 7s - loss:  - ETA: 4s - loss: 0.0685 - acc: 0.98 - ETA: 4s - loss: 0.0685 - acc: 0.9 - ETA: 4s - loss: 0.0686 -  - ETA: 3s - loss: 0.0689 - acc: 0.9 - ETA: 3s - loss: - ETA: 2s - loss: 0.069 - ETA: 1s - loss: 0.0689 - acc: 0 - 
Epoch 32/100
132506/132506 [==============================] - 10s - loss: 0.0671 - acc: 0.9816    - ETA: 8s - ETA - ETA: 1s - loss: 0.066 - ETA: 0s - loss: 0.067 - ETA: 0s - loss: 0.0673 - acc: 0.981 - ETA: 0s - loss: 0.0672 - acc: 0
Epoch 33/100
132506/132506 [==============================] - 9s - loss: 0.0672 - acc: 0.9818     - ETA: 9s - loss: 0.0655 - acc: 0 - ETA: 8s - loss: 0.0679 - acc: 0.98 - ETA: 8s - loss: - ETA: 7s -   - ETA: 0s - loss: 0.0673 - acc
Epoch 34/100
132506/132506 [==============================] - 9s - loss: 0.0664 - acc: 0.9814     - ETA: 9s - loss: 0.0689 - acc - ETA: 8s - loss: 0.0666 - acc: 0 - ETA: 8s - loss: 0.0691  - ETA:

132506/132506 [==============================] - 9s - loss: 0.0629 - acc: 0.9826     - ETA: 8s - loss: 0.0594 - acc:  - ETA: 7s - loss: 0.0 - ETA: 6s - loss:  - ETA: 5s - loss: - ETA: 4s - loss: 0.0 - ETA: 4s - loss: 0 - ETA: 3s - loss: 0.0620 - acc: 0.982 - ETA: 3s - loss: 0.0621 - acc: 0.9 - ETA: 0s - loss: 0.0630 - a - ETA: 0s - loss: 0.0624 - acc:
Epoch 58/100
132506/132506 [==============================] - 9s - loss: 0.0632 - acc: 0.9828     - ETA: 7s - loss: 0.0636 - acc: 0.9 - ETA: 7s - loss: 0.0644 - acc: 0.9 - ETA: 7s - loss: 0.065 - ETA:  - ETA: 5s - loss: 0.06 - ETA: 1s - loss:
Epoch 59/100
132506/132506 [==============================] - 11s - loss: 0.0626 - acc: 0.9828    - ETA: 7s - loss: 0.0582 - a - ETA: 7s - loss: 0.0577 - acc - ETA: 7s - loss - ETA: 3s - loss: 0.0632 - - ETA: 3s - loss: 0.0631  - ETA: 2s - loss: 0. - ETA: 1s - loss: 0.0630 -  - ETA: 0s - loss: 0.0
Epoch 60/100
132506/132506 [==============================] - 10s - loss: 0.0626 - acc: 0.9828    - ETA:

132506/132506 [==============================] - 9s - loss: 0.0610 - acc: 0.9831     - ETA: 6s - loss: 0.0587 - acc:  - ETA: 6s - loss: 0.0594 - acc:  - ETA: 6s - loss: 0.0598  - ETA: 5s - loss: 0.0593 - ac - ETA: 5s - loss: 0.0597 - acc - ETA: 4s - loss: 0.0595  - ETA: 3s - lo - ETA: 2s - loss: 0.0597 - acc: 0.983 - ETA: 2s - loss: 0.0598 - acc: 0.98 - ETA: 2s - loss: 0. - ETA: 1s - loss: - ETA: 0s - loss: 0.0608 - acc: - ETA: 0s - loss: 0.0611 - acc: 0 - ETA: 0s - loss: 0.0612 - acc: 0
Epoch 83/100
132506/132506 [==============================] - 9s - loss: 0.0611 - acc: 0.9830     - ETA: 9s - loss - ETA: 8s -  - ETA: 7s - loss: 0
Epoch 84/100
132506/132506 [==============================] - 9s - loss: 0.0613 - acc: 0.9831     - - ETA: 6s - loss: 0.0554 - - ETA: 5s - - ETA: 2s - loss: 0.0606 - acc: 0.983 - ETA: 2s - loss: 0.0607 
Epoch 85/100
132506/132506 [==============================] - 9s - loss: 0.0611 - acc: 0.9831     - ETA: 8s - loss: 0.060 - ETA: 7s - loss: 0 - ETA: 6s - lo

In [30]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [32]:
accuracy_score(Y_test_class, Y_pred_class)

0.98188788601442933

In [33]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[10155,     1,     0,    27,     5],
       [    0,  2299,    45,    51,    13],
       [    0,    13,  9395,    16,    24],
       [   14,    91,    78,  2240,    21],
       [    1,    29,   144,    27,  8438]], dtype=int64)