## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('Wholesale customers data.csv')
dataset.shape

(440, 8)

In [3]:
dataset.head()

Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

## Create X and Y

In [4]:
X = dataset.iloc[:, 2:].values
Y = dataset.iloc[:, 0].values

In [5]:
X.shape

(440, 6)

In [6]:
Y.shape

(440,)

In [7]:
X[0]

array([12669,  9656,  7561,   214,  2674,  1338], dtype=int64)

In [8]:
Y[0]

2

## Preprocess the Data

In [9]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)

In [12]:
Y[0]

1

In [13]:
sc_X = StandardScaler()

In [14]:
X = sc_X.fit_transform(X)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [15]:
X[0]

array([ 0.05293319,  0.52356777, -0.04111489, -0.58936716, -0.04356873,
       -0.06633906])

## Create Train and Test Data

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [18]:
X_train.shape

(352, 6)

In [19]:
X_test.shape

(88, 6)

In [20]:
Y_train.shape

(352,)

In [21]:
Y_test.shape

(88,)

In [22]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  240
1  112

In [23]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  58
1  30

## Create and train the ANN Classifier

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'relu', input_dim = 6))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=3, input_dim=6, kernel_initializer="uniform", activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="uniform", activation="sigmoid")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
352/352 [==============================] - 0s - loss: 0.6862 - acc: 0.7443     
Epoch 2/200
352/352 [==============================] - 0s - loss: 0.6663 - acc: 0.8523     
Epoch 3/200
352/352 [==============================] - 0s - loss: 0.6373 - acc: 0.8835     
Epoch 4/200
352/352 [==============================] - 0s - loss: 0.6034 - acc: 0.9034     
Epoch 5/200
352/352 [==============================] - 0s - loss: 0.5714 - acc: 0.9006     
Epoch 6/200
352/352 [==============================] - 0s - loss: 0.5443 - acc: 0.9006     
Epoch 7/200
352/352 [==============================] - 0s - loss: 0.5212 - acc: 0.9034     
Epoch 8/200
352/352 [==============================] - 0s - loss: 0.5012 - acc: 0.9091     
Epoch 9/200
352/352 [==============================] - 0s - loss: 0.4837 - acc: 0.9091     
Epoch 10/200
352/352 [==============================] - 0s - loss: 0.4680 - acc: 0.9119     
Epoch 11/200
352/352 [==============================] - 0s - loss: 0.4536 - acc

352/352 [==============================] - 0s - loss: 0.2284 - acc: 0.9176     
Epoch 89/200
352/352 [==============================] - 0s - loss: 0.2280 - acc: 0.9119     
Epoch 90/200
352/352 [==============================] - 0s - loss: 0.2279 - acc: 0.9148     
Epoch 91/200
352/352 [==============================] - 0s - loss: 0.2274 - acc: 0.9148     
Epoch 92/200
352/352 [==============================] - 0s - loss: 0.2269 - acc: 0.9119     
Epoch 93/200
352/352 [==============================] - 0s - loss: 0.2268 - acc: 0.9119     
Epoch 94/200
352/352 [==============================] - 0s - loss: 0.2264 - acc: 0.9176     
Epoch 95/200
352/352 [==============================] - 0s - loss: 0.2265 - acc: 0.9148     
Epoch 96/200
352/352 [==============================] - 0s - loss: 0.2260 - acc: 0.9119     
Epoch 97/200
352/352 [==============================] - 0s - loss: 0.2257 - acc: 0.9119     
Epoch 98/200
352/352 [==============================] - 0s - loss: 0.2252 - acc: 0.

352/352 [==============================] - 0s - loss: 0.2178 - acc: 0.9119     
Epoch 176/200
352/352 [==============================] - 0s - loss: 0.2179 - acc: 0.9091     
Epoch 177/200
352/352 [==============================] - 0s - loss: 0.2178 - acc: 0.9148     
Epoch 178/200
352/352 [==============================] - 0s - loss: 0.2177 - acc: 0.9119     
Epoch 179/200
352/352 [==============================] - 0s - loss: 0.2176 - acc: 0.9119     
Epoch 180/200
352/352 [==============================] - 0s - loss: 0.2176 - acc: 0.9119     
Epoch 181/200
352/352 [==============================] - 0s - loss: 0.2179 - acc: 0.9119     
Epoch 182/200
352/352 [==============================] - 0s - loss: 0.2178 - acc: 0.9148     
Epoch 183/200
352/352 [==============================] - 0s - loss: 0.2175 - acc: 0.9119     
Epoch 184/200
352/352 [==============================] - 0s - loss: 0.2174 - acc: 0.9119     
Epoch 185/200
352/352 [==============================] - 0s - loss: 0.2172

In [26]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [28]:
accuracy_score(Y_test, Y_pred)

0.88636363636363635

In [29]:
confusion_matrix(Y_test, Y_pred)

array([[56,  2],
       [ 8, 22]], dtype=int64)