## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('semeion.data', header = None, delimiter = r"\s+")
dataset.shape

(1593, 266)

In [3]:
dataset.head()

0    1    2    3    4    5    6    7    8    9   ...   256  257  258  259  \
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0 ...     1    0    0    0   
1  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0 ...     1    0    0    0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...     1    0    0    0   
3  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0 ...     1    0    0    0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...     1    0    0    0   

   260  261  262  263  264  265  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 266 columns]

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:256].values
Y = dataset.iloc[:, 256:].values

In [5]:
X.shape

(1593, 256)

In [6]:
Y.shape

(1593, 10)

In [7]:
X[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,
        1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,
        0.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,
        0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0

In [8]:
Y[0]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

## Create Train and Test Data

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [11]:
X_train.shape

(1274, 256)

In [12]:
X_test.shape

(319, 256)

In [13]:
Y_train.shape

(1274, 10)

In [14]:
Y_test.shape

(319, 10)

## Create and train the ANN Classifier

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 133, init = 'uniform', activation = 'relu', input_dim = 256))

# Second Hidden Layer
#clf_ann.add(Dense(output_dim = 133, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=256, units=133, kernel_initializer="uniform", activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=10, kernel_initializer="uniform", activation="softmax")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
1274/1274 [==============================] - 0s - loss: 1.3069 - acc: 0.6758     
Epoch 2/100
1274/1274 [==============================] - 0s - loss: 0.4131 - acc: 0.8909     
Epoch 3/100
1274/1274 [==============================] - 0s - loss: 0.2472 - acc: 0.9356     
Epoch 4/100
1274/1274 [==============================] - 0s - loss: 0.1690 - acc: 0.9647     
Epoch 5/100
1274/1274 [==============================] - 0s - loss: 0.1264 - acc: 0.9749     
Epoch 6/100
1274/1274 [==============================] - 0s - loss: 0.0848 - acc: 0.9851     
Epoch 7/100
1274/1274 [==============================] - 0s - loss: 0.0692 - acc: 0.9906     
Epoch 8/100
1274/1274 [==============================] - 0s - loss: 0.0496 - acc: 0.9961     
Epoch 9/100
1274/1274 [==============================] - 0s - loss: 0.0337 - acc: 0.9969     
Epoch 10/100
1274/1274 [==============================] - 0s - loss: 0.0256 - acc: 0.9984     
Epoch 11/100
1274/1274 [==============================] - 0

1274/1274 [==============================] - 0s - loss: 1.6537e-05 - acc: 1.0000     
Epoch 86/100
1274/1274 [==============================] - 0s - loss: 1.5354e-05 - acc: 1.0000     
Epoch 87/100
1274/1274 [==============================] - 0s - loss: 1.4294e-05 - acc: 1.0000     
Epoch 88/100
1274/1274 [==============================] - 0s - loss: 1.3312e-05 - acc: 1.0000     
Epoch 89/100
1274/1274 [==============================] - 0s - loss: 1.2414e-05 - acc: 1.0000     
Epoch 90/100
1274/1274 [==============================] - 0s - loss: 1.1492e-05 - acc: 1.0000     
Epoch 91/100
1274/1274 [==============================] - 0s - loss: 1.0796e-05 - acc: 1.0000     
Epoch 92/100
1274/1274 [==============================] - 0s - loss: 9.9846e-06 - acc: 1.0000     
Epoch 93/100
1274/1274 [==============================] - 0s - loss: 9.3076e-06 - acc: 1.0000     
Epoch 94/100
1274/1274 [==============================] - 0s - loss: 8.6896e-06 - acc: 1.0000     
Epoch 95/100
1274/1274 

In [17]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [19]:
accuracy_score(Y_test_class, Y_pred_class)

0.94357366771159878

In [20]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 31,  1,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0, 25,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0, 30,  0,  1,  0,  0,  0,  1],
       [ 2,  0,  0,  0, 36,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0, 27,  1,  0,  0,  0],
       [ 0,  1,  0,  0,  1,  0, 32,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 23,  0,  1],
       [ 0,  1,  0,  0,  0,  0,  0,  0, 31,  1],
       [ 0,  1,  0,  1,  1,  0,  0,  0,  0, 30]], dtype=int64)