## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("winequality-red.csv")
dataset.shape

(1599, 12)

In [3]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

## Creating X and Y

In [4]:
X = dataset.iloc[:, 0:11].values
Y = dataset.iloc[:, 11].values

In [5]:
X

array([[  7.4  ,   0.7  ,   0.   , ...,   3.51 ,   0.56 ,   9.4  ],
       [  7.8  ,   0.88 ,   0.   , ...,   3.2  ,   0.68 ,   9.8  ],
       [  7.8  ,   0.76 ,   0.04 , ...,   3.26 ,   0.65 ,   9.8  ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   3.42 ,   0.75 ,  11.   ],
       [  5.9  ,   0.645,   0.12 , ...,   3.57 ,   0.71 ,  10.2  ],
       [  6.   ,   0.31 ,   0.47 , ...,   3.39 ,   0.66 ,  11.   ]])

In [6]:
Y

array([5, 5, 5, ..., 6, 5, 6], dtype=int64)

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [8]:
le_Y = LabelEncoder()

In [9]:
Y = le_Y.fit_transform(Y)
Y

array([2, 2, 2, ..., 3, 2, 3], dtype=int64)

In [10]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [11]:
Y = ohe_Y.fit_transform(Y).toarray()
Y

array([[ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.]])

In [12]:
sc_X = StandardScaler()

In [13]:
X = sc_X.fit_transform(X)
X

array([[-0.52835961,  0.96187667, -1.39147228, ...,  1.28864292,
        -0.57920652, -0.96024611],
       [-0.29854743,  1.96744245, -1.39147228, ..., -0.7199333 ,
         0.1289504 , -0.58477711],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.33117661,
        -0.04808883, -0.58477711],
       ..., 
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.70550789,
         0.54204194,  0.54162988],
       [-1.39015528,  0.65462046, -0.77526673, ...,  1.6773996 ,
         0.30598963, -0.20930812],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.51112954,
         0.01092425,  0.54162988]])

## Create Train and Test Data

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [15]:
X_train.shape

(1279, 11)

In [16]:
X_test.shape

(320, 11)

In [17]:
Y_train.shape

(1279, 6)

In [18]:
Y_test.shape

(320, 6)

## Create and train the Classifier

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 11))

# Output Layer
clf_ann.add(Dense(output_dim = 6, init = 'uniform', activation = 'softmax'))

clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=8, input_dim=11, activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:18: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=6, activation="softmax")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
1279/1279 [==============================] - 0s - loss: 1.6706 - acc: 0.4887     
Epoch 2/100
1279/1279 [==============================] - 0s - loss: 1.2849 - acc: 0.5168     
Epoch 3/100
1279/1279 [==============================] - 0s - loss: 1.1058 - acc: 0.5356     
Epoch 4/100
1279/1279 [==============================] - 0s - loss: 1.0441 - acc: 0.5645     
Epoch 5/100
1279/1279 [==============================] - 0s - loss: 1.0138 - acc: 0.5731     
Epoch 6/100
1279/1279 [==============================] - 0s - loss: 0.9955 - acc: 0.5887     
Epoch 7/100
1279/1279 [==============================] - 0s - loss: 0.9848 - acc: 0.5809     
Epoch 8/100
1279/1279 [==============================] - 0s - loss: 0.9763 - acc: 0.5895     
Epoch 9/100
1279/1279 [==============================] - 0s - loss: 0.9694 - acc: 0.5966     
Epoch 10/100
1279/1279 [==============================] - 0s - loss: 0.9646 - acc: 0.5973     
Epoch 11/100
1279/1279 [==============================] - 0

1279/1279 [==============================] - 0s - loss: 0.8807 - acc: 0.6138     
Epoch 88/100
1279/1279 [==============================] - 0s - loss: 0.8803 - acc: 0.6122     
Epoch 89/100
1279/1279 [==============================] - 0s - loss: 0.8795 - acc: 0.6106     
Epoch 90/100
1279/1279 [==============================] - 0s - loss: 0.8794 - acc: 0.6161     
Epoch 91/100
1279/1279 [==============================] - 0s - loss: 0.8789 - acc: 0.6153     
Epoch 92/100
1279/1279 [==============================] - 0s - loss: 0.8779 - acc: 0.6153     
Epoch 93/100
1279/1279 [==============================] - 0s - loss: 0.8778 - acc: 0.6099     
Epoch 94/100
1279/1279 [==============================] - 0s - loss: 0.8782 - acc: 0.6114     
Epoch 95/100
1279/1279 [==============================] - 0s - loss: 0.8772 - acc: 0.6122     
Epoch 96/100
1279/1279 [==============================] - 0s - loss: 0.8764 - acc: 0.6091     
Epoch 97/100
1279/1279 [==============================] - 0s - 

In [21]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred_class, Y_test_class)

0.61875000000000002

In [23]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[  0,   0,   0,   0,   0,   0],
       [  1,   0,   1,   0,   0,   0],
       [  0,   7, 112,  36,   0,   0],
       [  1,   4,  31,  75,  30,   2],
       [  0,   0,   2,   7,  11,   0],
       [  0,   0,   0,   0,   0,   0]], dtype=int64)