## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("winequality-red.csv")
dataset.shape

(1599, 12)

In [3]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

## Creating X and Y

In [5]:
X = dataset.iloc[:, 0:11].values
Y = dataset.iloc[:, 11].values

In [6]:
X

array([[  7.4  ,   0.7  ,   0.   , ...,   3.51 ,   0.56 ,   9.4  ],
       [  7.8  ,   0.88 ,   0.   , ...,   3.2  ,   0.68 ,   9.8  ],
       [  7.8  ,   0.76 ,   0.04 , ...,   3.26 ,   0.65 ,   9.8  ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   3.42 ,   0.75 ,  11.   ],
       [  5.9  ,   0.645,   0.12 , ...,   3.57 ,   0.71 ,  10.2  ],
       [  6.   ,   0.31 ,   0.47 , ...,   3.39 ,   0.66 ,  11.   ]])

In [7]:
Y

array([5, 5, 5, ..., 6, 5, 6], dtype=int64)

## Preprocess the Data

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [9]:
le_Y = LabelEncoder()

In [10]:
Y = le_Y.fit_transform(Y)
Y

array([2, 2, 2, ..., 3, 2, 3], dtype=int64)

In [11]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [12]:
Y = ohe_Y.fit_transform(Y).toarray()
Y

array([[ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.]])

In [13]:
sc_X = StandardScaler()

In [14]:
X = sc_X.fit_transform(X)
X

array([[-0.52835961,  0.96187667, -1.39147228, ...,  1.28864292,
        -0.57920652, -0.96024611],
       [-0.29854743,  1.96744245, -1.39147228, ..., -0.7199333 ,
         0.1289504 , -0.58477711],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.33117661,
        -0.04808883, -0.58477711],
       ..., 
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.70550789,
         0.54204194,  0.54162988],
       [-1.39015528,  0.65462046, -0.77526673, ...,  1.6773996 ,
         0.30598963, -0.20930812],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.51112954,
         0.01092425,  0.54162988]])

## Create Train and Test Data

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [16]:
X_train.shape

(1279, 11)

In [17]:
X_test.shape

(320, 11)

In [18]:
Y_train.shape

(1279, 6)

In [19]:
Y_test.shape

(320, 6)

## Create and train the Classifier

In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [63]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 36, init = 'uniform', activation = 'relu', input_dim = 11))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 72, init = 'uniform', activation = 'relu'))

clf_ann.add(Dense(output_dim = 108, init = 'uniform', activation = 'relu'))

clf_ann.add(Dense(output_dim = 144, init = 'uniform', activation = 'relu'))

clf_ann.add(Dense(output_dim = 180, init = 'uniform', activation = 'relu'))

clf_ann.add(Dense(output_dim = 216, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 6, init = 'uniform', activation = 'softmax'))

clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=36, kernel_initializer="uniform", input_dim=11)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=72, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=108, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=144, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=180, kernel_initializer="uniform")`
C:\Users\user\Anacond

Epoch 1/100
1279/1279 [==============================] - 0s - loss: 1.2918 - acc: 0.4144     
Epoch 2/100
1279/1279 [==============================] - 0s - loss: 1.1391 - acc: 0.4605     
Epoch 3/100
1279/1279 [==============================] - 0s - loss: 1.1285 - acc: 0.5340     
Epoch 4/100
1279/1279 [==============================] - 0s - loss: 1.0729 - acc: 0.5536     
Epoch 5/100
1279/1279 [==============================] - 0s - loss: 1.0059 - acc: 0.5825     
Epoch 6/100
1279/1279 [==============================] - 1s - loss: 0.9780 - acc: 0.5911     
Epoch 7/100
1279/1279 [==============================] - 1s - loss: 0.9628 - acc: 0.5864     
Epoch 8/100
1279/1279 [==============================] - 0s - loss: 0.9482 - acc: 0.6005     
Epoch 9/100
1279/1279 [==============================] - 1s - loss: 0.9483 - acc: 0.5887     
Epoch 10/100
1279/1279 [==============================] - 1s - loss: 0.9380 - acc: 0.6013     
Epoch 11/100
1279/1279 [==============================] - 1

1279/1279 [==============================] - 1s - loss: 0.2787 - acc: 0.9015     
Epoch 88/100
1279/1279 [==============================] - 1s - loss: 0.2972 - acc: 0.8960     
Epoch 89/100
1279/1279 [==============================] - 1s - loss: 0.2726 - acc: 0.9085     
Epoch 90/100
1279/1279 [==============================] - 1s - loss: 0.3195 - acc: 0.8812     - ETA: 1s - loss: 0.
Epoch 91/100
1279/1279 [==============================] - 1s - loss: 0.2893 - acc: 0.8952     
Epoch 92/100
1279/1279 [==============================] - 1s - loss: 0.2504 - acc: 0.9148     
Epoch 93/100
1279/1279 [==============================] - 1s - loss: 0.2614 - acc: 0.9077     
Epoch 94/100
1279/1279 [==============================] - 1s - loss: 0.2389 - acc: 0.9218     
Epoch 95/100
1279/1279 [==============================] - 1s - loss: 0.2512 - acc: 0.9109     
Epoch 96/100
1279/1279 [==============================] - 1s - loss: 0.2840 - acc: 0.8890     
Epoch 97/100
1279/1279 [===================

In [64]:
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [65]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_pred, Y_test)

0.66874999999999996