## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("winequality-red.csv")
dataset.shape

(1599, 12)

In [3]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

## Creating X and Y

In [4]:
X = dataset.iloc[:, 0:11].values
Y = dataset.iloc[:, 11].values

In [5]:
X[0]

array([  7.4   ,   0.7   ,   0.    ,   1.9   ,   0.076 ,  11.    ,
        34.    ,   0.9978,   3.51  ,   0.56  ,   9.4   ])

In [6]:
Y[0]

5

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [8]:
le_Y = LabelEncoder()

In [9]:
Y = le_Y.fit_transform(Y)
Y[0]

2

In [10]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [11]:
Y = ohe_Y.fit_transform(Y).toarray()
Y[0]

array([ 0.,  0.,  1.,  0.,  0.,  0.])

In [12]:
sc_X = StandardScaler()

In [13]:
X = sc_X.fit_transform(X)
X[0]

array([-0.52835961,  0.96187667, -1.39147228, -0.45321841, -0.24370669,
       -0.46619252, -0.37913269,  0.55827446,  1.28864292, -0.57920652,
       -0.96024611])

## Create Train and Test Data

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [15]:
X_train.shape

(1279, 11)

In [16]:
X_test.shape

(320, 11)

In [17]:
Y_train.shape

(1279, 6)

In [18]:
Y_test.shape

(320, 6)

## Create and train the Classifier

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 11))

# Output Layer
clf_ann.add(Dense(output_dim = 6, init = 'uniform', activation = 'softmax'))

clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=8, activation="relu", input_dim=11)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="softmax", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
1279/1279 [==============================] - 0s - loss: 1.6740 - acc: 0.5442     
Epoch 2/100
1279/1279 [==============================] - 0s - loss: 1.3084 - acc: 0.5528     
Epoch 3/100
1279/1279 [==============================] - 0s - loss: 1.1193 - acc: 0.5598     
Epoch 4/100
1279/1279 [==============================] - 0s - loss: 1.0532 - acc: 0.5723     
Epoch 5/100
1279/1279 [==============================] - 0s - loss: 1.0189 - acc: 0.5825     
Epoch 6/100
1279/1279 [==============================] - 0s - loss: 1.0001 - acc: 0.5833     
Epoch 7/100
1279/1279 [==============================] - 0s - loss: 0.9867 - acc: 0.5927     
Epoch 8/100
1279/1279 [==============================] - 0s - loss: 0.9756 - acc: 0.5997     
Epoch 9/100
1279/1279 [==============================] - 0s - loss: 0.9664 - acc: 0.5997     
Epoch 10/100
1279/1279 [==============================] - 0s - loss: 0.9585 - acc: 0.5958     
Epoch 11/100
1279/1279 [==============================] - 0

1279/1279 [==============================] - 0s - loss: 0.8769 - acc: 0.6216     
Epoch 88/100
1279/1279 [==============================] - 0s - loss: 0.8771 - acc: 0.6255     
Epoch 89/100
1279/1279 [==============================] - 0s - loss: 0.8761 - acc: 0.6216     
Epoch 90/100
1279/1279 [==============================] - 0s - loss: 0.8752 - acc: 0.6255     
Epoch 91/100
1279/1279 [==============================] - 0s - loss: 0.8759 - acc: 0.6224     
Epoch 92/100
1279/1279 [==============================] - 0s - loss: 0.8757 - acc: 0.6185     
Epoch 93/100
1279/1279 [==============================] - 0s - loss: 0.8748 - acc: 0.6247     
Epoch 94/100
1279/1279 [==============================] - 0s - loss: 0.8750 - acc: 0.6177     
Epoch 95/100
1279/1279 [==============================] - 0s - loss: 0.8747 - acc: 0.6231     
Epoch 96/100
1279/1279 [==============================] - 0s - loss: 0.8740 - acc: 0.6271     
Epoch 97/100
1279/1279 [==============================] - 0s - 

In [21]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test_class, Y_pred_class)

0.62187499999999996

In [23]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[  0,   1,   0,   1,   0,   0],
       [  0,   0,   7,   4,   0,   0],
       [  0,   2, 110,  32,   2,   0],
       [  0,   0,  35,  73,  10,   0],
       [  0,   0,   0,  25,  16,   0],
       [  0,   0,   0,   2,   0,   0]], dtype=int64)