## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("winequality-white.csv")
dataset.shape

(4898, 12)

In [3]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

## Creating X and Y

In [4]:
X = dataset.iloc[:, 0:11].values
Y = dataset.iloc[:, 11].values

In [5]:
X

array([[  7.  ,   0.27,   0.36, ...,   3.  ,   0.45,   8.8 ],
       [  6.3 ,   0.3 ,   0.34, ...,   3.3 ,   0.49,   9.5 ],
       [  8.1 ,   0.28,   0.4 , ...,   3.26,   0.44,  10.1 ],
       ..., 
       [  6.5 ,   0.24,   0.19, ...,   2.99,   0.46,   9.4 ],
       [  5.5 ,   0.29,   0.3 , ...,   3.34,   0.38,  12.8 ],
       [  6.  ,   0.21,   0.38, ...,   3.26,   0.32,  11.8 ]])

In [6]:
Y

array([6, 6, 6, ..., 6, 7, 6], dtype=int64)

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [8]:
le_Y = LabelEncoder()

In [9]:
Y = le_Y.fit_transform(Y)
Y

array([3, 3, 3, ..., 3, 4, 3], dtype=int64)

In [10]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [11]:
Y = ohe_Y.fit_transform(Y).toarray()
Y

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [12]:
sc_X = StandardScaler()

In [13]:
X = sc_X.fit_transform(X)
X

array([[  1.72096961e-01,  -8.17699008e-02,   2.13280202e-01, ...,
         -1.24692128e+00,  -3.49184257e-01,  -1.39315246e+00],
       [ -6.57501128e-01,   2.15895632e-01,   4.80011213e-02, ...,
          7.40028640e-01,   1.34184656e-03,  -8.24275678e-01],
       [  1.47575110e+00,   1.74519434e-02,   5.43838363e-01, ...,
          4.75101984e-01,  -4.36815783e-01,  -3.36667007e-01],
       ..., 
       [ -4.20473102e-01,  -3.79435433e-01,  -1.19159198e+00, ...,
         -1.31315295e+00,  -2.61552731e-01,  -9.05543789e-01],
       [ -1.60561323e+00,   1.16673788e-01,  -2.82557040e-01, ...,
          1.00495530e+00,  -9.62604939e-01,   1.85757201e+00],
       [ -1.01304317e+00,  -6.77100966e-01,   3.78559282e-01, ...,
          4.75101984e-01,  -1.48839409e+00,   1.04489089e+00]])

## Create Train and Test Data

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [15]:
X_train.shape

(3918, 11)

In [16]:
X_test.shape

(980, 11)

In [17]:
Y_train.shape

(3918, 7)

In [18]:
Y_test.shape

(980, 7)

## Create and train the Classifier

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [45]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 36, init = 'uniform', activation = 'relu', input_dim = 11))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 72, init = 'uniform', activation = 'relu'))

clf_ann.add(Dense(output_dim = 108, init = 'uniform', activation = 'relu'))

clf_ann.add(Dense(output_dim = 144, init = 'uniform', activation = 'relu'))

clf_ann.add(Dense(output_dim = 216, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 7, init = 'uniform', activation = 'softmax'))

clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=36, input_dim=11, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", units=72)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", units=108)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", units=144)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", units=216)`
C:\Users\user\Anacond

Epoch 1/100
3918/3918 [==============================] - 0s - loss: 1.3306 - acc: 0.4403     
Epoch 2/100
3918/3918 [==============================] - 1s - loss: 1.2315 - acc: 0.4630     
Epoch 3/100
3918/3918 [==============================] - 1s - loss: 1.1134 - acc: 0.5235     
Epoch 4/100
3918/3918 [==============================] - 1s - loss: 1.0643 - acc: 0.5401     
Epoch 5/100
3918/3918 [==============================] - 2s - loss: 1.0499 - acc: 0.5536     
Epoch 6/100
3918/3918 [==============================] - 2s - loss: 1.0326 - acc: 0.5646     
Epoch 7/100
3918/3918 [==============================] - 2s - loss: 1.0259 - acc: 0.5569     
Epoch 8/100
3918/3918 [==============================] - 2s - loss: 1.0090 - acc: 0.5727     
Epoch 9/100
3918/3918 [==============================] - 2s - loss: 1.0026 - acc: 0.5664     
Epoch 10/100
3918/3918 [==============================] - 2s - loss: 0.9888 - acc: 0.5753     
Epoch 11/100
3918/3918 [==============================] - 2

3918/3918 [==============================] - 4s - loss: 0.2455 - acc: 0.9040     
Epoch 87/100
3918/3918 [==============================] - 4s - loss: 0.2323 - acc: 0.9135     
Epoch 88/100
3918/3918 [==============================] - ETA: 0s - loss: 0.2515 - acc: 0.907 - 4s - loss: 0.2518 - acc: 0.9066     
Epoch 89/100
3918/3918 [==============================] - 4s - loss: 0.2559 - acc: 0.9048     
Epoch 90/100
3918/3918 [==============================] - 4s - loss: 0.2519 - acc: 0.9071     
Epoch 91/100
3918/3918 [==============================] - 4s - loss: 0.2421 - acc: 0.9051     
Epoch 92/100
3918/3918 [==============================] - 4s - loss: 0.2049 - acc: 0.9283     
Epoch 93/100
3918/3918 [==============================] - 4s - loss: 0.2231 - acc: 0.9173     
Epoch 94/100
3918/3918 [==============================] - 4s - loss: 0.2067 - acc: 0.9201     
Epoch 95/100
3918/3918 [==============================] - 4s - loss: 0.2513 - acc: 0.9091     
Epoch 96/100
3918/3918 [=

In [46]:
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_pred, Y_test)

0.59795918367346934