## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("winequality-white.csv")
dataset.shape

(4898, 12)

In [3]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

## Creating X and Y

In [4]:
X = dataset.iloc[:, 0:11].values
Y = dataset.iloc[:, 11].values

In [5]:
X[0]

array([  7.00000000e+00,   2.70000000e-01,   3.60000000e-01,
         2.07000000e+01,   4.50000000e-02,   4.50000000e+01,
         1.70000000e+02,   1.00100000e+00,   3.00000000e+00,
         4.50000000e-01,   8.80000000e+00])

In [6]:
Y[0]

6

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [8]:
le_Y = LabelEncoder()

In [9]:
Y = le_Y.fit_transform(Y)
Y[0]

3

In [10]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [11]:
Y = ohe_Y.fit_transform(Y).toarray()
Y[0]

array([ 0.,  0.,  0.,  1.,  0.,  0.,  0.])

In [12]:
sc_X = StandardScaler()

In [13]:
X = sc_X.fit_transform(X)
X[0]

array([ 0.17209696, -0.0817699 ,  0.2132802 ,  2.82134917, -0.035355  ,
        0.56993158,  0.74456503,  2.33151201, -1.24692128, -0.34918426,
       -1.39315246])

## Create Train and Test Data

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [15]:
X_train.shape

(3918, 11)

In [16]:
X_test.shape

(980, 11)

In [17]:
Y_train.shape

(3918, 7)

In [18]:
Y_test.shape

(980, 7)

## Create and train the Classifier

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu', input_dim = 11))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 18, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 7, init = 'uniform', activation = 'softmax'))

clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, kernel_initializer="uniform", activation="relu", units=9)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=18, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=7, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
3918/3918 [==============================] - 0s - loss: 1.4320 - acc: 0.4492     
Epoch 2/100
3918/3918 [==============================] - 0s - loss: 1.1899 - acc: 0.4898     
Epoch 3/100
3918/3918 [==============================] - 0s - loss: 1.1351 - acc: 0.5245     
Epoch 4/100
3918/3918 [==============================] - 0s - loss: 1.1102 - acc: 0.5426     
Epoch 5/100
3918/3918 [==============================] - 0s - loss: 1.0974 - acc: 0.5465     
Epoch 6/100
3918/3918 [==============================] - 0s - loss: 1.0908 - acc: 0.5465     
Epoch 7/100
3918/3918 [==============================] - 0s - loss: 1.0817 - acc: 0.5472     
Epoch 8/100
3918/3918 [==============================] - 0s - loss: 1.0769 - acc: 0.5508     
Epoch 9/100
3918/3918 [==============================] - 0s - loss: 1.0715 - acc: 0.5513     
Epoch 10/100
3918/3918 [==============================] - 0s - loss: 1.0665 - acc: 0.5587     
Epoch 11/100
3918/3918 [==============================] - 0

3918/3918 [==============================] - 0s - loss: 0.9907 - acc: 0.5712     
Epoch 88/100
3918/3918 [==============================] - 0s - loss: 0.9881 - acc: 0.5720     
Epoch 89/100
3918/3918 [==============================] - 0s - loss: 0.9889 - acc: 0.5733     
Epoch 90/100
3918/3918 [==============================] - 0s - loss: 0.9891 - acc: 0.5704     
Epoch 91/100
3918/3918 [==============================] - 0s - loss: 0.9878 - acc: 0.5722     
Epoch 92/100
3918/3918 [==============================] - 0s - loss: 0.9870 - acc: 0.5771     
Epoch 93/100
3918/3918 [==============================] - 0s - loss: 0.9885 - acc: 0.5740     
Epoch 94/100
3918/3918 [==============================] - 0s - loss: 0.9878 - acc: 0.5722     
Epoch 95/100
3918/3918 [==============================] - 0s - loss: 0.9886 - acc: 0.5720     
Epoch 96/100
3918/3918 [==============================] - 0s - loss: 0.9871 - acc: 0.5743     
Epoch 97/100
3918/3918 [==============================] - 0s - 

In [21]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test_class, Y_pred_class)

0.54387755102040813

In [23]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[  0,   0,   2,   1,   1,   0,   0],
       [  0,   2,  22,   8,   0,   0,   0],
       [  1,   3, 177, 100,   3,   0,   0],
       [  0,   0, 100, 277,  69,   0,   0],
       [  0,   0,   2,  92,  77,   0,   0],
       [  0,   0,   0,  17,  25,   0,   0],
       [  0,   0,   0,   1,   0,   0,   0]], dtype=int64)