## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("winequality-white.csv")
dataset.shape

(4898, 12)

In [3]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

## Creating X and Y

In [4]:
X = dataset.iloc[:, 0:11].values
Y = dataset.iloc[:, 11].values

In [5]:
X

array([[  7.  ,   0.27,   0.36, ...,   3.  ,   0.45,   8.8 ],
       [  6.3 ,   0.3 ,   0.34, ...,   3.3 ,   0.49,   9.5 ],
       [  8.1 ,   0.28,   0.4 , ...,   3.26,   0.44,  10.1 ],
       ..., 
       [  6.5 ,   0.24,   0.19, ...,   2.99,   0.46,   9.4 ],
       [  5.5 ,   0.29,   0.3 , ...,   3.34,   0.38,  12.8 ],
       [  6.  ,   0.21,   0.38, ...,   3.26,   0.32,  11.8 ]])

In [6]:
Y

array([6, 6, 6, ..., 6, 7, 6], dtype=int64)

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [8]:
le_Y = LabelEncoder()

In [9]:
Y = le_Y.fit_transform(Y)
Y

array([3, 3, 3, ..., 3, 4, 3], dtype=int64)

In [10]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [11]:
Y = ohe_Y.fit_transform(Y).toarray()
Y

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [12]:
sc_X = StandardScaler()

In [13]:
X = sc_X.fit_transform(X)
X

array([[  1.72096961e-01,  -8.17699008e-02,   2.13280202e-01, ...,
         -1.24692128e+00,  -3.49184257e-01,  -1.39315246e+00],
       [ -6.57501128e-01,   2.15895632e-01,   4.80011213e-02, ...,
          7.40028640e-01,   1.34184656e-03,  -8.24275678e-01],
       [  1.47575110e+00,   1.74519434e-02,   5.43838363e-01, ...,
          4.75101984e-01,  -4.36815783e-01,  -3.36667007e-01],
       ..., 
       [ -4.20473102e-01,  -3.79435433e-01,  -1.19159198e+00, ...,
         -1.31315295e+00,  -2.61552731e-01,  -9.05543789e-01],
       [ -1.60561323e+00,   1.16673788e-01,  -2.82557040e-01, ...,
          1.00495530e+00,  -9.62604939e-01,   1.85757201e+00],
       [ -1.01304317e+00,  -6.77100966e-01,   3.78559282e-01, ...,
          4.75101984e-01,  -1.48839409e+00,   1.04489089e+00]])

## Create Train and Test Data

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [15]:
X_train.shape

(3918, 11)

In [16]:
X_test.shape

(980, 11)

In [17]:
Y_train.shape

(3918, 7)

In [18]:
Y_test.shape

(980, 7)

## Create and train the Classifier

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu', input_dim = 11))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 18, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 7, init = 'uniform', activation = 'softmax'))

clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", input_dim=11, units=9)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=18, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=7, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
3918/3918 [==============================] - 0s - loss: 1.4228 - acc: 0.4484     
Epoch 2/100
3918/3918 [==============================] - 0s - loss: 1.1961 - acc: 0.4964     
Epoch 3/100
3918/3918 [==============================] - 0s - loss: 1.1343 - acc: 0.5309     
Epoch 4/100
3918/3918 [==============================] - 0s - loss: 1.1127 - acc: 0.5413     
Epoch 5/100
3918/3918 [==============================] - 0s - loss: 1.1027 - acc: 0.5426     
Epoch 6/100
3918/3918 [==============================] - 0s - loss: 1.0962 - acc: 0.5413     
Epoch 7/100
3918/3918 [==============================] - 0s - loss: 1.0911 - acc: 0.5465     
Epoch 8/100
3918/3918 [==============================] - 0s - loss: 1.0856 - acc: 0.5472     
Epoch 9/100
3918/3918 [==============================] - 0s - loss: 1.0797 - acc: 0.5472     
Epoch 10/100
3918/3918 [==============================] - 0s - loss: 1.0738 - acc: 0.5485     
Epoch 11/100
3918/3918 [==============================] - 0

3918/3918 [==============================] - 0s - loss: 0.9963 - acc: 0.5743     
Epoch 87/100
3918/3918 [==============================] - 0s - loss: 0.9948 - acc: 0.5755     
Epoch 88/100
3918/3918 [==============================] - 0s - loss: 0.9941 - acc: 0.5748     
Epoch 89/100
3918/3918 [==============================] - 0s - loss: 0.9960 - acc: 0.5755     
Epoch 90/100
3918/3918 [==============================] - 0s - loss: 0.9945 - acc: 0.5743     
Epoch 91/100
3918/3918 [==============================] - 0s - loss: 0.9945 - acc: 0.5730     
Epoch 92/100
3918/3918 [==============================] - 0s - loss: 0.9951 - acc: 0.5771     
Epoch 93/100
3918/3918 [==============================] - 0s - loss: 0.9938 - acc: 0.5725     
Epoch 94/100
3918/3918 [==============================] - 0s - loss: 0.9929 - acc: 0.5784     
Epoch 95/100
3918/3918 [==============================] - 0s - loss: 0.9927 - acc: 0.5755     
Epoch 96/100
3918/3918 [==============================] - 0s - 

In [21]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred_class, Y_test_class)

0.5357142857142857

In [23]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[  0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   1,   0,   0,   0,   0],
       [  2,  25, 202, 132,   5,   0,   1],
       [  1,   6,  78, 255,  99,  17,   0],
       [  1,   0,   3,  59,  67,  25,   0],
       [  0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0]], dtype=int64)