## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('bank.csv', delimiter=';', quoting=3)
dataset.shape

(4521, 17)

In [3]:
dataset.head()

"age""          ""job""  ""marital""  ""education"" ""default""  \
0    "30   ""unemployed""  ""married""    ""primary""      ""no""   
1    "33     ""services""  ""married""  ""secondary""      ""no""   
2    "35   ""management""   ""single""   ""tertiary""      ""no""   
3    "30   ""management""  ""married""   ""tertiary""      ""no""   
4    "59  ""blue-collar""  ""married""  ""secondary""      ""no""   

   ""balance"" ""housing"" ""loan""   ""contact""  ""day"" ""month""  \
0         1787      ""no""   ""no""  ""cellular""       19   ""oct""   
1         4789     ""yes""  ""yes""  ""cellular""       11   ""may""   
2         1350     ""yes""   ""no""  ""cellular""       16   ""apr""   
3         1476     ""yes""  ""yes""   ""unknown""        3   ""jun""   
4            0     ""yes""   ""no""   ""unknown""        5   ""may""   

   ""duration""  ""campaign""  ""pdays""  ""previous"" ""poutcome""   ""y"""  
0            79             1         -1             0  ""unknown""  ""no"""  
1           220             1        339             4  ""failure""  ""no"""  
2           185             1        330             1  ""failure""  ""no"""  
3           199             4         -1             0  ""unknown""  ""no"""  
4           226             1         -1             0  ""unknown""  ""no"""

In [4]:
dataset = dataset.rename(columns = lambda x : x.replace('"', ''))
dataset.head()

age              job      marital      education default  balance  housing  \
0  "30   ""unemployed""  ""married""    ""primary""  ""no""     1787   ""no""   
1  "33     ""services""  ""married""  ""secondary""  ""no""     4789  ""yes""   
2  "35   ""management""   ""single""   ""tertiary""  ""no""     1350  ""yes""   
3  "30   ""management""  ""married""   ""tertiary""  ""no""     1476  ""yes""   
4  "59  ""blue-collar""  ""married""  ""secondary""  ""no""        0  ""yes""   

      loan       contact  day    month  duration  campaign  pdays  previous  \
0   ""no""  ""cellular""   19  ""oct""        79         1     -1         0   
1  ""yes""  ""cellular""   11  ""may""       220         1    339         4   
2   ""no""  ""cellular""   16  ""apr""       185         1    330         1   
3  ""yes""   ""unknown""    3  ""jun""       199         4     -1         0   
4   ""no""   ""unknown""    5  ""may""       226         1     -1         0   

      poutcome        y  
0  ""unknown""  ""no"""  
1  ""failure""  ""no"""  
2  ""failure""  ""no"""  
3  ""unknown""  ""no"""  
4  ""unknown""  ""no"""

In [5]:
columns = ['age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']

for x in columns:
    dataset[x] = dataset[x].apply(lambda x : x.replace('"', ''))

In [6]:
dataset.head()

age          job  marital  education default  balance housing loan  \
0  30   unemployed  married    primary      no     1787      no   no   
1  33     services  married  secondary      no     4789     yes  yes   
2  35   management   single   tertiary      no     1350     yes   no   
3  30   management  married   tertiary      no     1476     yes  yes   
4  59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

In [7]:
dataset['age'] = pd.to_numeric(dataset['age'])

## Create X and Y

In [8]:
X = dataset.iloc[:, 0:16].values
Y = dataset.iloc[:, 16].values

In [9]:
X.shape

(4521, 16)

In [10]:
Y.shape

(4521,)

In [11]:
X

array([[30, 'unemployed', 'married', ..., -1, 0, 'unknown'],
       [33, 'services', 'married', ..., 339, 4, 'failure'],
       [35, 'management', 'single', ..., 330, 1, 'failure'],
       ..., 
       [57, 'technician', 'married', ..., -1, 0, 'unknown'],
       [28, 'blue-collar', 'married', ..., 211, 3, 'other'],
       [44, 'entrepreneur', 'single', ..., 249, 7, 'other']], dtype=object)

In [12]:
Y

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

## Preprocess the Data

In [13]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [14]:
le_Y = LabelEncoder()

In [15]:
Y = le_Y.fit_transform(Y)
Y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
cols_to_encode = [1, 2, 3, 4, 6, 7, 8, 10, 15]
def encoder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])
    return

In [17]:
for i in cols_to_encode:
    encoder_X(i)

In [18]:
X[0, :]

array([30, 10, 1, 0, 0, 1787, 0, 0, 0, 19, 10, 79, 1, -1, 0, 3], dtype=object)

In [19]:
ohe_X = OneHotEncoder(categorical_features = [15])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(4521, 18)

In [20]:
pd.DataFrame(pd.DataFrame(X[:, 13])[0].value_counts())

0
8.0   1398
5.0    706
1.0    633
6.0    531
9.0    389
0.0    293
3.0    222
4.0    148
10.0    80
11.0    52
7.0     49
2.0     20

In [21]:
ohe_X = OneHotEncoder(categorical_features = [13])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(4521, 28)

In [22]:
pd.DataFrame(pd.DataFrame(X[:, 22])[0].value_counts())

0
0.0  2896
2.0  1324
1.0   301

In [23]:
ohe_X = OneHotEncoder(categorical_features = [22])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(4521, 29)

In [24]:
pd.DataFrame(pd.DataFrame(X[:, 19])[0].value_counts())

0
1.0  2306
2.0  1350
0.0   678
3.0   187

In [25]:
ohe_X = OneHotEncoder(categorical_features = [19])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(4521, 31)

In [26]:
pd.DataFrame(pd.DataFrame(X[:, 21])[0].value_counts())

0
1.0  2797
2.0  1196
0.0   528

In [27]:
ohe_X = OneHotEncoder(categorical_features = [21])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(4521, 32)

In [28]:
pd.DataFrame(pd.DataFrame(X[:, 22])[0].value_counts())

0
4.0   969
1.0   946
9.0   768
0.0   478
7.0   417
5.0   230
6.0   183
2.0   168
10.0  128
3.0   112
8.0    84
11.0   38

In [29]:
ohe_X = OneHotEncoder(categorical_features = [22])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(4521, 42)

In [30]:
sc_X = StandardScaler()

In [31]:
X = sc_X.fit_transform(X)

In [32]:
X

array([[-0.5144078 , -0.19645374, -0.15938189, ..., -0.57682947,
        -0.4072183 , -0.32041282],
       [-0.5144078 , -0.19645374, -0.15938189, ..., -0.57682947,
         2.98904408,  2.04173372],
       [-0.5144078 , -0.19645374, -0.15938189, ..., -0.57682947,
         2.89914302,  0.27012381],
       ..., 
       [-0.5144078 , -0.19645374, -0.15938189, ...,  2.63916021,
        -0.4072183 , -0.32041282],
       [ 1.94398296, -0.19645374, -0.15938189, ...,  0.38796743,
         1.71045119,  1.45119709],
       [-0.5144078 ,  5.0902568 , -0.15938189, ..., -0.2552305 ,
         2.09003345,  3.81334363]])

## Create Train and Test Data

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [35]:
X_train.shape

(3616, 42)

In [36]:
X_test.shape

(905, 42)

In [37]:
Y_train.shape

(3616,)

In [38]:
Y_test.shape

(905,)

In [39]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  3194
1   422

In [40]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  806
1   99

## Create and train the ANN Classifier

In [41]:
from keras.models import Sequential
from keras.layers import Dense

In [42]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 84, init = 'uniform', activation = 'relu', input_dim = 42))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 84, init = 'uniform', activation = 'relu'))

#clf_ann.add(Dense(output_dim = 21, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=42, kernel_initializer="uniform", units=84)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=84)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="sigmoid", units=1)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
3616/3616 [==============================] - 0s - loss: 0.2999 - acc: 0.8827     
Epoch 2/100
3616/3616 [==============================] - 0s - loss: 0.2250 - acc: 0.9010     
Epoch 3/100
3616/3616 [==============================] - 0s - loss: 0.2131 - acc: 0.9076     
Epoch 4/100
3616/3616 [==============================] - 0s - loss: 0.2010 - acc: 0.9157     
Epoch 5/100
3616/3616 [==============================] - 0s - loss: 0.1933 - acc: 0.9231     - ETA: 0s - loss: 0.1886 - acc: 0.92
Epoch 6/100
3616/3616 [==============================] - 0s - loss: 0.1815 - acc: 0.9264     
Epoch 7/100
3616/3616 [==============================] - 0s - loss: 0.1729 - acc: 0.9314     
Epoch 8/100
3616/3616 [==============================] - 0s - loss: 0.1612 - acc: 0.9350     
Epoch 9/100
3616/3616 [==============================] - 0s - loss: 0.1517 - acc: 0.9389     
Epoch 10/100
3616/3616 [==============================] - 0s - loss: 0.1415 - acc: 0.9447     
Epoch 11/100
3616/3616 

3616/3616 [==============================] - 0s - loss: 0.0026 - acc: 0.9994     
Epoch 84/100
3616/3616 [==============================] - 0s - loss: 0.0025 - acc: 0.9997     - ETA: 0s - loss: 0.0019 - acc: 0.9
Epoch 85/100
3616/3616 [==============================] - 0s - loss: 0.0023 - acc: 0.9997     
Epoch 86/100
3616/3616 [==============================] - 0s - loss: 0.0052 - acc: 0.9986     
Epoch 87/100
3616/3616 [==============================] - 0s - loss: 0.0094 - acc: 0.9972     
Epoch 88/100
3616/3616 [==============================] - 0s - loss: 0.0298 - acc: 0.9895     
Epoch 89/100
3616/3616 [==============================] - 0s - loss: 0.0183 - acc: 0.9936     
Epoch 90/100
3616/3616 [==============================] - 0s - loss: 0.0232 - acc: 0.9950     
Epoch 91/100
3616/3616 [==============================] - 0s - loss: 0.0146 - acc: 0.9970     
Epoch 92/100
3616/3616 [==============================] - 0s - loss: 0.0084 - acc: 0.9986     
Epoch 93/100
3616/3616 [====

In [43]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [44]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [45]:
accuracy_score(Y_test, Y_pred)

0.89281767955801106

In [46]:
confusion_matrix(Y_test, Y_pred)

array([[753,  53],
       [ 44,  55]], dtype=int64)