In [1]:
import numpy as np
import pandas as pd

## Importing the Data

In [2]:
dataset = pd.read_csv("diagnosis.data", header = None, delimiter = r"\s+")
X = dataset.iloc[:, 0:6].values
Y1 = dataset.iloc[:, 6:7].values
Y2 = dataset.iloc[:, 7:8].values

In [3]:
dataset.head()

0   1    2    3    4    5    6   7
0  35.5  no  yes   no   no   no   no  no
1  35.9  no   no  yes  yes  yes  yes  no
2  35.9  no  yes   no   no   no   no  no
3  36.0  no   no  yes  yes  yes  yes  no
4  36.0  no  yes   no   no   no   no  no

In [5]:
Y1 = Y1.reshape(len(Y1), 1)
Y2 = Y2.reshape(len(Y2), 1)

In [6]:
Y1

array([['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['no'],
       ['yes'],
       ['no'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['no'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['no'],
       ['no'],
       ['no'],
       ['no'],


## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder
le_Y = LabelEncoder()
Y1 = le_Y.fit_transform(Y1)
Y2 = le_Y.transform(Y2)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
Y1

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0], dtype=int64)

In [9]:
Y2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1], dtype=int64)

In [10]:
le_X = LabelEncoder()
le_X.fit(X[:, 1])

X[:, 1] = le_X.transform(X[:, 1])
X[:, 2] = le_X.transform(X[:, 2])
X[:, 3] = le_X.transform(X[:, 3])
X[:, 4] = le_X.transform(X[:, 4])
X[:, 5] = le_X.transform(X[:, 5])

In [11]:
X

array([[35.5, 0, 1, 0, 0, 0],
       [35.9, 0, 0, 1, 1, 1],
       [35.9, 0, 1, 0, 0, 0],
       [36.0, 0, 0, 1, 1, 1],
       [36.0, 0, 1, 0, 0, 0],
       [36.0, 0, 1, 0, 0, 0],
       [36.2, 0, 0, 1, 1, 1],
       [36.2, 0, 1, 0, 0, 0],
       [36.3, 0, 0, 1, 1, 1],
       [36.6, 0, 0, 1, 1, 1],
       [36.6, 0, 0, 1, 1, 1],
       [36.6, 0, 1, 0, 0, 0],
       [36.6, 0, 1, 0, 0, 0],
       [36.7, 0, 0, 1, 1, 1],
       [36.7, 0, 1, 0, 0, 0],
       [36.7, 0, 1, 0, 0, 0],
       [36.8, 0, 0, 1, 1, 1],
       [36.8, 0, 0, 1, 1, 1],
       [36.9, 0, 0, 1, 1, 1],
       [36.9, 0, 1, 0, 0, 0],
       [37.0, 0, 0, 1, 1, 0],
       [37.0, 0, 0, 1, 1, 0],
       [37.0, 0, 1, 0, 0, 0],
       [37.0, 0, 0, 1, 1, 1],
       [37.0, 0, 0, 1, 1, 1],
       [37.0, 0, 0, 1, 1, 1],
       [37.0, 0, 0, 1, 1, 1],
       [37.0, 0, 0, 1, 0, 0],
       [37.1, 0, 1, 0, 0, 0],
       [37.1, 0, 0, 1, 1, 1],
       [37.1, 0, 0, 1, 0, 0],
       [37.2, 0, 0, 1, 1, 0],
       [37.2, 0, 1, 0, 0, 0],
       [37

## Create Train and Test Data

In [12]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X, Y1, test_size = 0.2, random_state = 4)
X2_train, X2_test, Y2_train, Y2_test = train_test_split(X, Y2, test_size = 0.2, random_state = 4)

## Create and Train the Classifier for Y1

In [13]:
import keras

Using Theano backend.


In [14]:
from keras.models import Sequential
from keras.layers import Dense

In [15]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'relu', input_dim = 6))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X1_train, Y1_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=6, activation="relu", units=3, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
96/96 [==============================] - 0s - loss: 0.6935 - acc: 0.5000     
Epoch 2/200
96/96 [==============================] - 0s - loss: 0.6928 - acc: 0.5000     
Epoch 3/200
96/96 [==============================] - 0s - loss: 0.6924 - acc: 0.5000     
Epoch 4/200
96/96 [==============================] - 0s - loss: 0.6919 - acc: 0.5000     
Epoch 5/200
96/96 [==============================] - 0s - loss: 0.6918 - acc: 0.6667     
Epoch 6/200
96/96 [==============================] - 0s - loss: 0.6916 - acc: 0.5729     
Epoch 7/200
96/96 [==============================] - 0s - loss: 0.6903 - acc: 0.5000     
Epoch 8/200
96/96 [==============================] - 0s - loss: 0.6894 - acc: 0.8438     
Epoch 9/200
96/96 [==============================] - 0s - loss: 0.6891 - acc: 0.7188     
Epoch 10/200
96/96 [==============================] - 0s - loss: 0.6878 - acc: 0.6979     
Epoch 11/200
96/96 [==============================] - 0s - loss: 0.6858 - acc: 0.5000     
Epoch 12

96/96 [==============================] - 0s - loss: 0.0320 - acc: 1.0000     
Epoch 179/200
96/96 [==============================] - 0s - loss: 0.0319 - acc: 1.0000     
Epoch 180/200
96/96 [==============================] - 0s - loss: 0.0329 - acc: 1.0000     
Epoch 181/200
96/96 [==============================] - 0s - loss: 0.0316 - acc: 1.0000     
Epoch 182/200
96/96 [==============================] - 0s - loss: 0.0308 - acc: 1.0000     
Epoch 183/200
96/96 [==============================] - ETA: 0s - loss: 0.0364 - acc: 1.000 - 0s - loss: 0.0316 - acc: 1.0000     
Epoch 184/200
96/96 [==============================] - 0s - loss: 0.0307 - acc: 1.0000     
Epoch 185/200
96/96 [==============================] - 0s - loss: 0.0294 - acc: 1.0000     
Epoch 186/200
96/96 [==============================] - 0s - loss: 0.0291 - acc: 1.0000     
Epoch 187/200
96/96 [==============================] - 0s - loss: 0.0282 - acc: 1.0000     
Epoch 188/200
96/96 [==============================] - 0

## Check the Accuracy of the model

In [16]:
# Test the ANN on the Test Data
Y1_pred = clf_ann.predict(X1_test)
Y1_pred = (Y1_pred > 0.5)

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y1_pred, Y1_test)

1.0

In [19]:
cm = confusion_matrix(Y1_pred, Y1_test)
cm

array([[13,  0],
       [ 0, 11]], dtype=int64)

## Create and Train the Classifier for Y2

In [20]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'relu', input_dim = 6))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X2_train, Y2_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=6, activation="relu", units=3, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
96/96 [==============================] - 0s - loss: 0.6931 - acc: 0.5104     
Epoch 2/200
96/96 [==============================] - 0s - loss: 0.6915 - acc: 0.5729     
Epoch 3/200
96/96 [==============================] - 0s - loss: 0.6901 - acc: 0.5729     
Epoch 4/200
96/96 [==============================] - 0s - loss: 0.6891 - acc: 0.5729     
Epoch 5/200
96/96 [==============================] - 0s - loss: 0.6876 - acc: 0.5729     
Epoch 6/200
96/96 [==============================] - 0s - loss: 0.6866 - acc: 0.5729     
Epoch 7/200
96/96 [==============================] - 0s - loss: 0.6849 - acc: 0.5729     
Epoch 8/200
96/96 [==============================] - 0s - loss: 0.6828 - acc: 0.5729     
Epoch 9/200
96/96 [==============================] - 0s - loss: 0.6813 - acc: 0.5729     
Epoch 10/200
96/96 [==============================] - 0s - loss: 0.6787 - acc: 0.5729     
Epoch 11/200
96/96 [==============================] - 0s - loss: 0.6775 - acc: 0.5729     
Epoch 12

96/96 [==============================] - 0s - loss: 0.2619 - acc: 1.0000     
Epoch 92/200
96/96 [==============================] - 0s - loss: 0.2572 - acc: 1.0000     
Epoch 93/200
96/96 [==============================] - ETA: 0s - loss: 0.0245 - acc: 1.000 - 0s - loss: 0.2553 - acc: 1.0000     
Epoch 94/200
96/96 [==============================] - 0s - loss: 0.2524 - acc: 1.0000     
Epoch 95/200
96/96 [==============================] - 0s - loss: 0.2507 - acc: 1.0000     
Epoch 96/200
96/96 [==============================] - 0s - loss: 0.2461 - acc: 1.0000     
Epoch 97/200
96/96 [==============================] - 0s - loss: 0.2453 - acc: 1.0000     
Epoch 98/200
96/96 [==============================] - 0s - loss: 0.2411 - acc: 1.0000     
Epoch 99/200
96/96 [==============================] - 0s - loss: 0.2383 - acc: 1.0000     
Epoch 100/200
96/96 [==============================] - 0s - loss: 0.2401 - acc: 1.0000     
Epoch 101/200
96/96 [==============================] - 0s - loss

In [21]:
# Test the ANN on the Test Data
Y2_pred = clf_ann.predict(X2_test)
Y2_pred = (Y2_pred > 0.5)

## Check the Accuracy of the Model

In [22]:
accuracy_score(Y2_pred, Y2_test)

1.0

In [24]:
cm = confusion_matrix(Y2_pred, Y2_test)
cm

array([[15,  0],
       [ 0,  9]], dtype=int64)