In [1]:
import numpy as np
import pandas as pd

## Importing the Data

In [2]:
dataset = pd.read_csv("diagnosis.data", header = None, delimiter = r"\s+")
X = dataset.iloc[:, 0:6].values
Y1 = dataset.iloc[:, 6:7].values
Y2 = dataset.iloc[:, 7:8].values

In [3]:
dataset.head()

0   1    2    3    4    5    6   7
0  35.5  no  yes   no   no   no   no  no
1  35.9  no   no  yes  yes  yes  yes  no
2  35.9  no  yes   no   no   no   no  no
3  36.0  no   no  yes  yes  yes  yes  no
4  36.0  no  yes   no   no   no   no  no

In [4]:
Y1 = Y1.reshape(len(Y1), 1)
Y2 = Y2.reshape(len(Y2), 1)

In [5]:
Y1[0]

array(['no'], dtype=object)

## Preprocess the Data

In [6]:
from sklearn.preprocessing import LabelEncoder
le_Y = LabelEncoder()
Y1 = le_Y.fit_transform(Y1)
Y2 = le_Y.transform(Y2)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
Y1

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0], dtype=int64)

In [8]:
Y2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1], dtype=int64)

In [9]:
le_X = LabelEncoder()
le_X.fit(X[:, 1])

X[:, 1] = le_X.transform(X[:, 1])
X[:, 2] = le_X.transform(X[:, 2])
X[:, 3] = le_X.transform(X[:, 3])
X[:, 4] = le_X.transform(X[:, 4])
X[:, 5] = le_X.transform(X[:, 5])

In [10]:
X[0]

array([35.5, 0, 1, 0, 0, 0], dtype=object)

## Create Train and Test Data

In [11]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X, Y1, test_size = 0.2, random_state = 4)
X2_train, X2_test, Y2_train, Y2_test = train_test_split(X, Y2, test_size = 0.2, random_state = 4)

## Create and Train the Classifier for Y1

In [12]:
import keras

Using Theano backend.


In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'relu', input_dim = 6))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X1_train, Y1_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=3, input_dim=6, activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="uniform", activation="sigmoid")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
96/96 [==============================] - 0s - loss: 0.6950 - acc: 0.5000     
Epoch 2/200
96/96 [==============================] - 0s - loss: 0.6938 - acc: 0.5000     
Epoch 3/200
96/96 [==============================] - 0s - loss: 0.6936 - acc: 0.5000     
Epoch 4/200
96/96 [==============================] - 0s - loss: 0.6923 - acc: 0.5000     
Epoch 5/200
96/96 [==============================] - 0s - loss: 0.6919 - acc: 0.5000     
Epoch 6/200
96/96 [==============================] - 0s - loss: 0.6907 - acc: 0.5000     
Epoch 7/200
96/96 [==============================] - 0s - loss: 0.6897 - acc: 0.5938     
Epoch 8/200
96/96 [==============================] - 0s - loss: 0.6887 - acc: 0.6563     
Epoch 9/200
96/96 [==============================] - 0s - loss: 0.6876 - acc: 0.7917     
Epoch 10/200
96/96 [==============================] - 0s - loss: 0.6856 - acc: 0.6458     
Epoch 11/200
96/96 [==============================] - 0s - loss: 0.6834 - acc: 0.6667     
Epoch 12

96/96 [==============================] - 0s - loss: 0.1055 - acc: 1.0000     
Epoch 91/200
96/96 [==============================] - 0s - loss: 0.1058 - acc: 1.0000     
Epoch 92/200
96/96 [==============================] - 0s - loss: 0.1024 - acc: 1.0000     
Epoch 93/200
96/96 [==============================] - 0s - loss: 0.0981 - acc: 1.0000     
Epoch 94/200
96/96 [==============================] - 0s - loss: 0.0987 - acc: 1.0000     
Epoch 95/200
96/96 [==============================] - 0s - loss: 0.0943 - acc: 1.0000     
Epoch 96/200
96/96 [==============================] - 0s - loss: 0.0926 - acc: 1.0000     
Epoch 97/200
96/96 [==============================] - 0s - loss: 0.0925 - acc: 1.0000     
Epoch 98/200
96/96 [==============================] - 0s - loss: 0.0907 - acc: 1.0000     
Epoch 99/200
96/96 [==============================] - 0s - loss: 0.0889 - acc: 1.0000     
Epoch 100/200
96/96 [==============================] - 0s - loss: 0.0850 - acc: 1.0000     
Epoch 101/2

96/96 [==============================] - 0s - loss: 0.0203 - acc: 1.0000     
Epoch 180/200
96/96 [==============================] - 0s - loss: 0.0200 - acc: 1.0000     
Epoch 181/200
96/96 [==============================] - 0s - loss: 0.0197 - acc: 1.0000     
Epoch 182/200
96/96 [==============================] - 0s - loss: 0.0198 - acc: 1.0000     
Epoch 183/200
96/96 [==============================] - 0s - loss: 0.0195 - acc: 1.0000     
Epoch 184/200
96/96 [==============================] - 0s - loss: 0.0189 - acc: 1.0000     
Epoch 185/200
96/96 [==============================] - 0s - loss: 0.0183 - acc: 1.0000     
Epoch 186/200
96/96 [==============================] - 0s - loss: 0.0185 - acc: 1.0000     
Epoch 187/200
96/96 [==============================] - 0s - loss: 0.0181 - acc: 1.0000     
Epoch 188/200
96/96 [==============================] - 0s - loss: 0.0178 - acc: 1.0000     
Epoch 189/200
96/96 [==============================] - 0s - loss: 0.0174 - acc: 1.0000     
Ep

## Check the Accuracy of the model

In [15]:
# Test the ANN on the Test Data
Y1_pred = clf_ann.predict(X1_test)
Y1_pred = (Y1_pred > 0.5)

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y1_test, Y1_pred)

1.0

In [17]:
confusion_matrix(Y1_test, Y1_pred)

array([[13,  0],
       [ 0, 11]], dtype=int64)

## Create and Train the Classifier for Y2

In [18]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 14, init = 'uniform', activation = 'relu', input_dim = 6))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X2_train, Y2_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=14, input_dim=6, activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="uniform", activation="sigmoid")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
96/96 [==============================] - 0s - loss: 0.6941 - acc: 0.4896     
Epoch 2/200
96/96 [==============================] - 0s - loss: 0.6896 - acc: 0.5729     
Epoch 3/200
96/96 [==============================] - 0s - loss: 0.6879 - acc: 0.5729     
Epoch 4/200
96/96 [==============================] - 0s - loss: 0.6842 - acc: 0.5729     
Epoch 5/200
96/96 [==============================] - 0s - loss: 0.6844 - acc: 0.5729     
Epoch 6/200
96/96 [==============================] - 0s - loss: 0.6840 - acc: 0.5729     
Epoch 7/200
96/96 [==============================] - 0s - loss: 0.6797 - acc: 0.5729     
Epoch 8/200
96/96 [==============================] - 0s - loss: 0.6791 - acc: 0.5729     
Epoch 9/200
96/96 [==============================] - 0s - loss: 0.6784 - acc: 0.5729     
Epoch 10/200
96/96 [==============================] - 0s - loss: 0.6721 - acc: 0.5729     
Epoch 11/200
96/96 [==============================] - 0s - loss: 0.6686 - acc: 0.5729     
Epoch 12

96/96 [==============================] - 0s - loss: 0.0666 - acc: 1.0000     
Epoch 92/200
96/96 [==============================] - 0s - loss: 0.0637 - acc: 1.0000     
Epoch 93/200
96/96 [==============================] - 0s - loss: 0.0623 - acc: 1.0000     
Epoch 94/200
96/96 [==============================] - 0s - loss: 0.0601 - acc: 1.0000     
Epoch 95/200
96/96 [==============================] - 0s - loss: 0.0593 - acc: 1.0000     
Epoch 96/200
96/96 [==============================] - 0s - loss: 0.0574 - acc: 1.0000     
Epoch 97/200
96/96 [==============================] - 0s - loss: 0.0561 - acc: 1.0000     
Epoch 98/200
96/96 [==============================] - 0s - loss: 0.0558 - acc: 1.0000     
Epoch 99/200
96/96 [==============================] - 0s - loss: 0.0534 - acc: 1.0000     
Epoch 100/200
96/96 [==============================] - 0s - loss: 0.0526 - acc: 1.0000     
Epoch 101/200
96/96 [==============================] - 0s - loss: 0.0517 - acc: 1.0000     
Epoch 102/

96/96 [==============================] - 0s - loss: 0.0103 - acc: 1.0000     
Epoch 181/200
96/96 [==============================] - 0s - loss: 0.0102 - acc: 1.0000     
Epoch 182/200
96/96 [==============================] - 0s - loss: 0.0101 - acc: 1.0000     
Epoch 183/200
96/96 [==============================] - 0s - loss: 0.0099 - acc: 1.0000     
Epoch 184/200
96/96 [==============================] - 0s - loss: 0.0099 - acc: 1.0000     
Epoch 185/200
96/96 [==============================] - 0s - loss: 0.0097 - acc: 1.0000     
Epoch 186/200
96/96 [==============================] - 0s - loss: 0.0093 - acc: 1.0000     
Epoch 187/200
96/96 [==============================] - 0s - loss: 0.0092 - acc: 1.0000     
Epoch 188/200
96/96 [==============================] - 0s - loss: 0.0091 - acc: 1.0000     
Epoch 189/200
96/96 [==============================] - 0s - loss: 0.0089 - acc: 1.0000     
Epoch 190/200
96/96 [==============================] - 0s - loss: 0.0088 - acc: 1.0000     
Ep

In [19]:
# Test the ANN on the Test Data
Y2_pred = clf_ann.predict(X2_test)
Y2_pred = (Y2_pred > 0.5)

## Check the Accuracy of the Model

In [20]:
accuracy_score(Y2_test, Y2_pred)

1.0

In [21]:
confusion_matrix(Y2_test, Y2_pred)

array([[15,  0],
       [ 0,  9]], dtype=int64)