## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df = pd.read_csv('tae.data', header = None)
df.shape

(151, 6)

In [6]:
df.head()

0   1   2  3   4  5
0  1  23   3  1  19  3
1  2  15   3  1  17  3
2  1  23   3  2  49  3
3  1   5   2  2  33  3
4  2   7  11  2  55  3

## Creating X and Y

In [7]:
X = df.iloc[:, 0:5].values
Y = df.iloc[:, 5].values

In [8]:
Y.shape

(151,)

In [9]:
X.shape

(151, 5)

In [10]:
X.shape[1]

5

In [11]:
X[0]

array([ 1, 23,  3,  1, 19], dtype=int64)

In [12]:
Y[0]

3

## Preprocess the Data

In [13]:
le_Y = LabelEncoder()

In [14]:
Y = le_Y.fit_transform(Y)
Y[0]

2

In [15]:
def encoder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])

In [16]:
for x in range(0, X.shape[1] - 1):
    encoder_X(x)

In [17]:
X[0]

array([ 0, 22,  2,  0, 19], dtype=int64)

In [18]:
ohe_X = OneHotEncoder(categorical_features = [2])

In [19]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(151, 29)

In [20]:
pd.DataFrame(pd.DataFrame(X[:, 26])[0].value_counts())

0
22.0  17
12.0  14
21.0  12
6.0   11
14.0   8
8.0    8
9.0    8
13.0   8
17.0   8
5.0    8
4.0    6
19.0   5
7.0    5
24.0   4
0.0    4
1.0    4
15.0   4
16.0   4
10.0   3
2.0    2
20.0   2
3.0    2
11.0   2
23.0   1
18.0   1

In [21]:
ohe_X = OneHotEncoder(categorical_features = [26])

In [22]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(151, 52)

In [23]:
sc_X = StandardScaler()

In [24]:
X = sc_X.fit_transform(X)
X[0]

array([-0.16495722, -0.11585689, -0.11585689, -0.20341905, -0.23652496,
       -0.28030596, -0.1850583 , -0.23652496, -0.23652496, -0.1423737 ,
       -0.11585689, -0.31967136, -0.23652496, -0.23652496, -0.16495722,
       -0.16495722, -0.23652496, -0.08164966, -0.1850583 , -0.11585689,
       -0.29382126,  2.80755284, -0.08164966, -0.16495722, -0.34426519,
        1.53478192, -0.08164966, -0.1850583 , -0.11585689, -0.22047928,
       -0.16495722, -0.1423737 , -0.08164966, -0.25175441, -0.08164966,
       -0.1423737 , -0.08164966, -0.26631182, -0.1423737 , -0.26631182,
       -0.11585689, -0.08164966, -0.08164966, -0.1423737 , -0.1423737 ,
       -0.08164966, -0.08164966, -0.1423737 , -0.08164966, -2.05107205,
       -2.3590713 , -0.69002837])

## Create Train and Test data

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [26]:
X_train.shape

(120, 52)

In [27]:
X_test.shape

(31, 52)

In [28]:
Y_train.shape

(120,)

In [29]:
Y_test.shape

(31,)

In [30]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  42
2  40
1  38

In [31]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
2  12
1  12
0   7

## Decision Tree Classifier

In [32]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [33]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [34]:
Y_pred_dt = clf_dt.predict(X_test)

In [35]:
confusion_matrix(Y_test, Y_pred_dt)

array([[5, 1, 1],
       [5, 6, 1],
       [3, 4, 5]], dtype=int64)

## Random Forest Classifier

In [36]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [37]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [38]:
Y_pred_rf = clf_rf.predict(X_test)

In [39]:
confusion_matrix(Y_test, Y_pred_rf)

array([[5, 1, 1],
       [5, 5, 2],
       [1, 2, 9]], dtype=int64)

## Naive Bayes Classifier

In [40]:
clf_nb = GaussianNB()

In [41]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [42]:
Y_pred_nb = clf_nb.predict(X_test)

In [43]:
confusion_matrix(Y_test, Y_pred_nb)

array([[ 0,  1,  6],
       [ 0,  2, 10],
       [ 0,  3,  9]], dtype=int64)

## KNN Classifier

In [44]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [45]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [46]:
Y_pred_knn = clf_knn.predict(X_test)

In [47]:
confusion_matrix(Y_test, Y_pred_knn)

array([[2, 2, 3],
       [3, 6, 3],
       [4, 3, 5]], dtype=int64)

## Logistic Regression

In [48]:
clf_lr = LogisticRegression()

In [49]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [50]:
Y_pred_lr = clf_lr.predict(X_test)

In [51]:
confusion_matrix(Y_test, Y_pred_lr)

array([[3, 1, 3],
       [6, 6, 0],
       [2, 3, 7]], dtype=int64)

## SVC Linear

In [52]:
clf_lsvc = SVC(kernel = "linear")

In [53]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [54]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [55]:
confusion_matrix(Y_test, Y_pred_lsvc)

array([[2, 1, 4],
       [5, 6, 1],
       [2, 4, 6]], dtype=int64)

## SVC Kernel

In [56]:
clf_ksvc = SVC(kernel = "rbf")

In [57]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [58]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [59]:
confusion_matrix(Y_test, Y_pred_ksvc)

array([[0, 2, 5],
       [7, 5, 0],
       [3, 2, 7]], dtype=int64)

## Accuracy of Various Classifiers

In [60]:
model_accuracies['DT'] = accuracy_score(Y_test, Y_pred_dt)
model_accuracies['KNN'] = accuracy_score(Y_test, Y_pred_knn)
model_accuracies['KernelSVC'] = accuracy_score(Y_test, Y_pred_ksvc)
model_accuracies['LinearSVC'] = accuracy_score(Y_test, Y_pred_lsvc)
model_accuracies['LogReg'] = accuracy_score(Y_test, Y_pred_lr)
model_accuracies['NB'] = accuracy_score(Y_test, Y_pred_nb)
model_accuracies['RF'] = accuracy_score(Y_test, Y_pred_rf)
model_accuracies

{'DT': 0.5161290322580645,
 'KNN': 0.41935483870967744,
 'KernelSVC': 0.38709677419354838,
 'LinearSVC': 0.45161290322580644,
 'LogReg': 0.5161290322580645,
 'NB': 0.35483870967741937,
 'RF': 0.61290322580645162}