## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('tae.data', header = None)
dataset.shape

(151, 6)

In [3]:
dataset.head()

0   1   2  3   4  5
0  1  23   3  1  19  3
1  2  15   3  1  17  3
2  1  23   3  2  49  3
3  1   5   2  2  33  3
4  2   7  11  2  55  3

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:5].values
Y = dataset.iloc[:, 5].values

In [5]:
X.shape

(151, 5)

In [6]:
Y.shape

(151,)

In [7]:
X[0]

array([ 1, 23,  3,  1, 19], dtype=int64)

In [8]:
Y[0]

3

## Preprocess the Data

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)
Y[0]

2

In [12]:
def encoder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])

In [13]:
for x in range(0, X.shape[1] - 1):
    encoder_X(x)

In [14]:
X[0]

array([ 0, 22,  2,  0, 19], dtype=int64)

In [15]:
ohe_X = OneHotEncoder(categorical_features = [2])

In [16]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(151, 29)

In [17]:
ohe_X = OneHotEncoder(categorical_features = [26])

In [18]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(151, 52)

In [19]:
sc_X = StandardScaler()

In [20]:
X = sc_X.fit_transform(X)
X

array([[-0.16495722, -0.11585689, -0.11585689, ..., -2.05107205,
        -2.3590713 , -0.69002837],
       [-0.16495722, -0.11585689, -0.11585689, ...,  0.48754991,
        -2.3590713 , -0.84565836],
       [-0.16495722, -0.11585689, -0.11585689, ..., -2.05107205,
         0.42389562,  1.6444216 ],
       ..., 
       [-0.16495722, -0.11585689, -0.11585689, ..., -2.05107205,
         0.42389562,  1.5666066 ],
       [-0.16495722, -0.11585689, -0.11585689, ...,  0.48754991,
         0.42389562,  1.80005159],
       [ 6.06217783, -0.11585689, -0.11585689, ...,  0.48754991,
         0.42389562, -0.06750838]])

In [21]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [22]:
Y = ohe_Y.fit_transform(Y).toarray()
Y[0]

array([ 0.,  0.,  1.])

## Create Train and Test Data

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [25]:
X_train.shape

(120, 52)

In [26]:
X_test.shape

(31, 52)

In [27]:
Y_train.shape

(120, 3)

In [28]:
Y_test.shape

(31, 3)

## Create and train the ANN Classifier

In [29]:
from keras.models import Sequential
from keras.layers import Dense

In [30]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 27, init = 'uniform', activation = 'relu', input_dim = 52))

# Output Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=27, input_dim=52, kernel_initializer="uniform", activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=3, kernel_initializer="uniform", activation="softmax")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
120/120 [==============================] - 0s - loss: 1.0950 - acc: 0.3750     
Epoch 2/200
120/120 [==============================] - 0s - loss: 1.0795 - acc: 0.5583     
Epoch 3/200
120/120 [==============================] - 0s - loss: 1.0588 - acc: 0.6000     
Epoch 4/200
120/120 [==============================] - 0s - loss: 1.0269 - acc: 0.6750     
Epoch 5/200
120/120 [==============================] - 0s - loss: 0.9823 - acc: 0.6750     
Epoch 6/200
120/120 [==============================] - 0s - loss: 0.9287 - acc: 0.7250     
Epoch 7/200
120/120 [==============================] - 0s - loss: 0.8694 - acc: 0.7417     
Epoch 8/200
120/120 [==============================] - 0s - loss: 0.8138 - acc: 0.7250     
Epoch 9/200
120/120 [==============================] - 0s - loss: 0.7625 - acc: 0.7583     
Epoch 10/200
120/120 [==============================] - 0s - loss: 0.7181 - acc: 0.7583     
Epoch 11/200
120/120 [==============================] - 0s - loss: 0.6795 - acc

120/120 [==============================] - 0s - loss: 0.2317 - acc: 0.8917     
Epoch 88/200
120/120 [==============================] - 0s - loss: 0.2315 - acc: 0.9000     
Epoch 89/200
120/120 [==============================] - 0s - loss: 0.2283 - acc: 0.9083     
Epoch 90/200
120/120 [==============================] - 0s - loss: 0.2285 - acc: 0.9000     
Epoch 91/200
120/120 [==============================] - 0s - loss: 0.2286 - acc: 0.9000     
Epoch 92/200
120/120 [==============================] - ETA: 0s - loss: 0.2032 - acc: 1.000 - 0s - loss: 0.2273 - acc: 0.9083     
Epoch 93/200
120/120 [==============================] - 0s - loss: 0.2257 - acc: 0.9167     
Epoch 94/200
120/120 [==============================] - ETA: 0s - loss: 0.2505 - acc: 0.800 - 0s - loss: 0.2281 - acc: 0.9000     
Epoch 95/200
120/120 [==============================] - 0s - loss: 0.2212 - acc: 0.9083     
Epoch 96/200
120/120 [==============================] - 0s - loss: 0.2217 - acc: 0.9083     
Epoch 9

120/120 [==============================] - 0s - loss: 0.1745 - acc: 0.9333     
Epoch 173/200
120/120 [==============================] - 0s - loss: 0.1665 - acc: 0.9417     
Epoch 174/200
120/120 [==============================] - 0s - loss: 0.1679 - acc: 0.9250     
Epoch 175/200
120/120 [==============================] - 0s - loss: 0.1649 - acc: 0.9250     
Epoch 176/200
120/120 [==============================] - 0s - loss: 0.1631 - acc: 0.9333     
Epoch 177/200
120/120 [==============================] - ETA: 0s - loss: 0.1750 - acc: 0.800 - 0s - loss: 0.1669 - acc: 0.9250     
Epoch 178/200
120/120 [==============================] - 0s - loss: 0.1634 - acc: 0.9333     
Epoch 179/200
120/120 [==============================] - 0s - loss: 0.1663 - acc: 0.9250     
Epoch 180/200
120/120 [==============================] - 0s - loss: 0.1598 - acc: 0.9417     
Epoch 181/200
120/120 [==============================] - 0s - loss: 0.1636 - acc: 0.9333     
Epoch 182/200
120/120 [=============

In [31]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [33]:
accuracy_score(Y_test_class, Y_pred_class)

0.61290322580645162

In [34]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[2, 4, 1],
       [4, 9, 1],
       [1, 1, 8]], dtype=int64)