## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('tae.data', header = None)
dataset.shape

(151, 6)

In [3]:
dataset.head()

0   1   2  3   4  5
0  1  23   3  1  19  3
1  2  15   3  1  17  3
2  1  23   3  2  49  3
3  1   5   2  2  33  3
4  2   7  11  2  55  3

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:5].values
Y = dataset.iloc[:, 5].values

In [5]:
X.shape

(151, 5)

In [6]:
Y.shape

(151,)

In [7]:
X

array([[ 1, 23,  3,  1, 19],
       [ 2, 15,  3,  1, 17],
       [ 1, 23,  3,  2, 49],
       [ 1,  5,  2,  2, 33],
       [ 2,  7, 11,  2, 55],
       [ 2, 23,  3,  1, 20],
       [ 2,  9,  5,  2, 19],
       [ 2, 10,  3,  2, 27],
       [ 1, 22,  3,  1, 58],
       [ 2, 15,  3,  1, 20],
       [ 2, 10, 22,  2,  9],
       [ 2, 13,  1,  2, 30],
       [ 2, 18, 21,  2, 29],
       [ 2,  6, 17,  2, 39],
       [ 2,  6, 17,  2, 42],
       [ 2,  6, 17,  2, 43],
       [ 2,  7, 11,  2, 10],
       [ 2, 22,  3,  2, 46],
       [ 2, 13,  3,  1, 10],
       [ 2,  7, 25,  2, 42],
       [ 2, 25,  7,  2, 27],
       [ 2, 25,  7,  2, 23],
       [ 2,  2,  9,  2, 31],
       [ 2,  1, 15,  1, 22],
       [ 2, 15, 13,  2, 37],
       [ 2,  7, 11,  2, 13],
       [ 2,  8,  3,  2, 24],
       [ 2, 14, 15,  2, 38],
       [ 2, 21,  2,  2, 42],
       [ 2, 22,  3,  2, 28],
       [ 2, 11,  1,  2, 51],
       [ 2, 18,  5,  2, 19],
       [ 2, 13,  1,  2, 31],
       [ 1, 13,  3,  1, 13],
       [ 2,  5

In [8]:
Y

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

## Preprocess the Data

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)
Y

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
def encoder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])

In [13]:
for x in range(0, X.shape[1] - 1):
    encoder_X(x)

In [14]:
X

array([[ 0, 22,  2,  0, 19],
       [ 1, 14,  2,  0, 17],
       [ 0, 22,  2,  1, 49],
       [ 0,  4,  1,  1, 33],
       [ 1,  6, 10,  1, 55],
       [ 1, 22,  2,  0, 20],
       [ 1,  8,  4,  1, 19],
       [ 1,  9,  2,  1, 27],
       [ 0, 21,  2,  0, 58],
       [ 1, 14,  2,  0, 20],
       [ 1,  9, 21,  1,  9],
       [ 1, 12,  0,  1, 30],
       [ 1, 17, 20,  1, 29],
       [ 1,  5, 16,  1, 39],
       [ 1,  5, 16,  1, 42],
       [ 1,  5, 16,  1, 43],
       [ 1,  6, 10,  1, 10],
       [ 1, 21,  2,  1, 46],
       [ 1, 12,  2,  0, 10],
       [ 1,  6, 24,  1, 42],
       [ 1, 24,  6,  1, 27],
       [ 1, 24,  6,  1, 23],
       [ 1,  1,  8,  1, 31],
       [ 1,  0, 14,  0, 22],
       [ 1, 14, 12,  1, 37],
       [ 1,  6, 10,  1, 13],
       [ 1,  7,  2,  1, 24],
       [ 1, 13, 14,  1, 38],
       [ 1, 20,  1,  1, 42],
       [ 1, 21,  2,  1, 28],
       [ 1, 10,  0,  1, 51],
       [ 1, 17,  4,  1, 19],
       [ 1, 12,  0,  1, 31],
       [ 0, 12,  2,  0, 13],
       [ 1,  4

In [15]:
ohe_X = OneHotEncoder(categorical_features = [2])

In [16]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(151, 29)

In [17]:
ohe_X = OneHotEncoder(categorical_features = [26])

In [18]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(151, 52)

In [19]:
sc_X = StandardScaler()

In [20]:
X = sc_X.fit_transform(X)
X

array([[-0.16495722, -0.11585689, -0.11585689, ..., -2.05107205,
        -2.3590713 , -0.69002837],
       [-0.16495722, -0.11585689, -0.11585689, ...,  0.48754991,
        -2.3590713 , -0.84565836],
       [-0.16495722, -0.11585689, -0.11585689, ..., -2.05107205,
         0.42389562,  1.6444216 ],
       ..., 
       [-0.16495722, -0.11585689, -0.11585689, ..., -2.05107205,
         0.42389562,  1.5666066 ],
       [-0.16495722, -0.11585689, -0.11585689, ...,  0.48754991,
         0.42389562,  1.80005159],
       [ 6.06217783, -0.11585689, -0.11585689, ...,  0.48754991,
         0.42389562, -0.06750838]])

In [21]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [22]:
Y = ohe_Y.fit_transform(Y).toarray()
Y

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.

## Create Train and Test Data

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [25]:
X_train.shape

(120, 52)

In [26]:
X_test.shape

(31, 52)

In [27]:
Y_train.shape

(120, 3)

In [28]:
Y_test.shape

(31, 3)

## Create and train the ANN Classifier

In [29]:
from keras.models import Sequential
from keras.layers import Dense

In [30]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 27, init = 'uniform', activation = 'relu', input_dim = 52))

# Output Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=52, activation="relu", kernel_initializer="uniform", units=27)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", kernel_initializer="uniform", units=3)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
120/120 [==============================] - 0s - loss: 1.0945 - acc: 0.4250     
Epoch 2/200
120/120 [==============================] - 0s - loss: 1.0798 - acc: 0.6000     
Epoch 3/200
120/120 [==============================] - 0s - loss: 1.0615 - acc: 0.6500     
Epoch 4/200
120/120 [==============================] - 0s - loss: 1.0340 - acc: 0.6583     
Epoch 5/200
120/120 [==============================] - 0s - loss: 0.9968 - acc: 0.6917     
Epoch 6/200
120/120 [==============================] - 0s - loss: 0.9507 - acc: 0.7000     
Epoch 7/200
120/120 [==============================] - 0s - loss: 0.8963 - acc: 0.7083     
Epoch 8/200
120/120 [==============================] - 0s - loss: 0.8460 - acc: 0.6917     
Epoch 9/200
120/120 [==============================] - 0s - loss: 0.7982 - acc: 0.7167     
Epoch 10/200
120/120 [==============================] - 0s - loss: 0.7547 - acc: 0.7417     
Epoch 11/200
120/120 [==============================] - 0s - loss: 0.7128 - acc

120/120 [==============================] - 0s - loss: 0.2357 - acc: 0.8917     
Epoch 90/200
120/120 [==============================] - 0s - loss: 0.2373 - acc: 0.8917     
Epoch 91/200
120/120 [==============================] - 0s - loss: 0.2355 - acc: 0.9000     
Epoch 92/200
120/120 [==============================] - 0s - loss: 0.2334 - acc: 0.9083     
Epoch 93/200
120/120 [==============================] - 0s - loss: 0.2314 - acc: 0.8917     
Epoch 94/200
120/120 [==============================] - 0s - loss: 0.2336 - acc: 0.8833     
Epoch 95/200
120/120 [==============================] - 0s - loss: 0.2290 - acc: 0.9083     
Epoch 96/200
120/120 [==============================] - 0s - loss: 0.2270 - acc: 0.9000     
Epoch 97/200
120/120 [==============================] - 0s - loss: 0.2220 - acc: 0.9083     
Epoch 98/200
120/120 [==============================] - 0s - loss: 0.2290 - acc: 0.8833     
Epoch 99/200
120/120 [==============================] - 0s - loss: 0.2203 - acc: 0.

120/120 [==============================] - 0s - loss: 0.1724 - acc: 0.9333     
Epoch 177/200
120/120 [==============================] - 0s - loss: 0.1758 - acc: 0.9083     
Epoch 178/200
120/120 [==============================] - 0s - loss: 0.1747 - acc: 0.9250     
Epoch 179/200
120/120 [==============================] - 0s - loss: 0.1691 - acc: 0.9250     
Epoch 180/200
120/120 [==============================] - 0s - loss: 0.1702 - acc: 0.9333     
Epoch 181/200
120/120 [==============================] - 0s - loss: 0.1690 - acc: 0.9250     
Epoch 182/200
120/120 [==============================] - 0s - loss: 0.1699 - acc: 0.9167     
Epoch 183/200
120/120 [==============================] - 0s - loss: 0.1730 - acc: 0.9167     
Epoch 184/200
120/120 [==============================] - 0s - loss: 0.1707 - acc: 0.9083     
Epoch 185/200
120/120 [==============================] - 0s - loss: 0.1679 - acc: 0.9250     
Epoch 186/200
120/120 [==============================] - 0s - loss: 0.1686

In [31]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
accuracy_score(Y_pred, Y_test)

0.58064516129032262