## Initialization

In [1]:
import numpy as np
import pandas as pd
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("iris.data", header = None)
dataset.shape

(150, 5)

In [3]:
dataset.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:4].values
Y = dataset.iloc[:, 4:5].values

In [5]:
X[0]

array([ 5.1,  3.5,  1.4,  0.2])

In [6]:
Y[0]

array(['Iris-setosa'], dtype=object)

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)
ohe = OneHotEncoder(categorical_features=[0])
Y = ohe.fit_transform(Y).toarray()
Y[0]

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([ 1.,  0.,  0.])

In [8]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [9]:
X[0]

array([-0.90068117,  1.03205722, -1.3412724 , -1.31297673])

## Create Train and Test Data

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [12]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 4))

# Output Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=4, units=8, activation="relu", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=3, activation="softmax", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
120/120 [==============================] - 0s - loss: 1.0977 - acc: 0.3750     
Epoch 2/200
120/120 [==============================] - 0s - loss: 1.0862 - acc: 0.6167         
Epoch 3/200
120/120 [==============================] - 0s - loss: 1.0644 - acc: 0.6917     
Epoch 4/200
120/120 [==============================] - 0s - loss: 1.0288 - acc: 0.7833     
Epoch 5/200
120/120 [==============================] - 0s - loss: 0.9749 - acc: 0.8500     
Epoch 6/200
120/120 [==============================] - 0s - loss: 0.9073 - acc: 0.8500     
Epoch 7/200
120/120 [==============================] - 0s - loss: 0.8326 - acc: 0.7917     
Epoch 8/200
120/120 [==============================] - 0s - loss: 0.7603 - acc: 0.7750     
Epoch 9/200
120/120 [==============================] - 0s - loss: 0.6977 - acc: 0.6917     
Epoch 10/200
120/120 [==============================] - 0s - loss: 0.6441 - acc: 0.6917     
Epoch 11/200
120/120 [==============================] - 0s - loss: 0.6033 -

120/120 [==============================] - 0s - loss: 0.0850 - acc: 0.9750     
Epoch 89/200
120/120 [==============================] - 0s - loss: 0.0831 - acc: 0.9750     
Epoch 90/200
120/120 [==============================] - 0s - loss: 0.0819 - acc: 0.9750     
Epoch 91/200
120/120 [==============================] - 0s - loss: 0.0802 - acc: 0.9750     
Epoch 92/200
120/120 [==============================] - 0s - loss: 0.0788 - acc: 0.9750     
Epoch 93/200
120/120 [==============================] - 0s - loss: 0.0772 - acc: 0.9750     
Epoch 94/200
120/120 [==============================] - 0s - loss: 0.0760 - acc: 0.9750     
Epoch 95/200
120/120 [==============================] - 0s - loss: 0.0750 - acc: 0.9750     
Epoch 96/200
120/120 [==============================] - 0s - loss: 0.0741 - acc: 0.9750     
Epoch 97/200
120/120 [==============================] - 0s - loss: 0.0726 - acc: 0.9750     
Epoch 98/200
120/120 [==============================] - 0s - loss: 0.0709 - acc: 0.

120/120 [==============================] - 0s - loss: 0.0367 - acc: 0.9833     
Epoch 176/200
120/120 [==============================] - 0s - loss: 0.0375 - acc: 0.9833     
Epoch 177/200
120/120 [==============================] - 0s - loss: 0.0366 - acc: 0.9917     
Epoch 178/200
120/120 [==============================] - 0s - loss: 0.0361 - acc: 0.9917     
Epoch 179/200
120/120 [==============================] - 0s - loss: 0.0359 - acc: 0.9917     
Epoch 180/200
120/120 [==============================] - 0s - loss: 0.0357 - acc: 0.9917     
Epoch 181/200
120/120 [==============================] - 0s - loss: 0.0356 - acc: 0.9917     
Epoch 182/200
120/120 [==============================] - 0s - loss: 0.0354 - acc: 0.9833     
Epoch 183/200
120/120 [==============================] - 0s - loss: 0.0357 - acc: 0.9917     
Epoch 184/200
120/120 [==============================] - 0s - loss: 0.0350 - acc: 0.9917     
Epoch 185/200
120/120 [==============================] - 0s - loss: 0.0352

In [13]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test_class, Y_pred_class)

0.93333333333333335

In [15]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[16,  0,  0],
       [ 0,  4,  1],
       [ 0,  1,  8]], dtype=int64)