## Initialization

In [1]:
import numpy as np
import pandas as pd
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("iris.data", header = None)
dataset.shape

(150, 5)

In [3]:
dataset.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:4].values
Y = dataset.iloc[:, 4:5].values

In [5]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [6]:
Y

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)
ohe = OneHotEncoder(categorical_features=[0])
Y = ohe.fit_transform(Y).toarray()
Y

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

In [8]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [9]:
X

array([[ -9.00681170e-01,   1.03205722e+00,  -1.34127240e+00,
         -1.31297673e+00],
       [ -1.14301691e+00,  -1.24957601e-01,  -1.34127240e+00,
         -1.31297673e+00],
       [ -1.38535265e+00,   3.37848329e-01,  -1.39813811e+00,
         -1.31297673e+00],
       [ -1.50652052e+00,   1.06445364e-01,  -1.28440670e+00,
         -1.31297673e+00],
       [ -1.02184904e+00,   1.26346019e+00,  -1.34127240e+00,
         -1.31297673e+00],
       [ -5.37177559e-01,   1.95766909e+00,  -1.17067529e+00,
         -1.05003079e+00],
       [ -1.50652052e+00,   8.00654259e-01,  -1.34127240e+00,
         -1.18150376e+00],
       [ -1.02184904e+00,   8.00654259e-01,  -1.28440670e+00,
         -1.31297673e+00],
       [ -1.74885626e+00,  -3.56360566e-01,  -1.34127240e+00,
         -1.31297673e+00],
       [ -1.14301691e+00,   1.06445364e-01,  -1.28440670e+00,
         -1.44444970e+00],
       [ -5.37177559e-01,   1.49486315e+00,  -1.28440670e+00,
         -1.31297673e+00],
       [ -1.26418478e

## Create Train and Test Data

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [12]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 4))

# Output Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=4, activation="relu", units=8, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=3, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
120/120 [==============================] - 0s - loss: 1.0936 - acc: 0.6250     
Epoch 2/200
120/120 [==============================] - 0s - loss: 1.0754 - acc: 0.7167     
Epoch 3/200
120/120 [==============================] - 0s - loss: 1.0410 - acc: 0.7333     
Epoch 4/200
120/120 [==============================] - 0s - loss: 0.9884 - acc: 0.6333     
Epoch 5/200
120/120 [==============================] - 0s - loss: 0.9207 - acc: 0.6417     
Epoch 6/200
120/120 [==============================] - 0s - loss: 0.8468 - acc: 0.6333     
Epoch 7/200
120/120 [==============================] - 0s - loss: 0.7765 - acc: 0.6417     
Epoch 8/200
120/120 [==============================] - 0s - loss: 0.7162 - acc: 0.6417     
Epoch 9/200
120/120 [==============================] - 0s - loss: 0.6671 - acc: 0.6417     
Epoch 10/200
120/120 [==============================] - 0s - loss: 0.6286 - acc: 0.6417     
Epoch 11/200
120/120 [==============================] - 0s - loss: 0.5988 - acc

120/120 [==============================] - 0s - loss: 0.1292 - acc: 0.9833     
Epoch 89/200
120/120 [==============================] - 0s - loss: 0.1271 - acc: 0.9833     
Epoch 90/200
120/120 [==============================] - 0s - loss: 0.1251 - acc: 0.9833     
Epoch 91/200
120/120 [==============================] - 0s - loss: 0.1229 - acc: 0.9833     
Epoch 92/200
120/120 [==============================] - 0s - loss: 0.1220 - acc: 0.9833     
Epoch 93/200
120/120 [==============================] - 0s - loss: 0.1195 - acc: 0.9833     
Epoch 94/200
120/120 [==============================] - 0s - loss: 0.1175 - acc: 0.9833     
Epoch 95/200
120/120 [==============================] - 0s - loss: 0.1161 - acc: 0.9833     
Epoch 96/200
120/120 [==============================] - 0s - loss: 0.1136 - acc: 0.9833     
Epoch 97/200
120/120 [==============================] - 0s - loss: 0.1121 - acc: 0.9833     
Epoch 98/200
120/120 [==============================] - 0s - loss: 0.1107 - acc: 0.

120/120 [==============================] - 0s - loss: 0.0531 - acc: 0.9833     
Epoch 175/200
120/120 [==============================] - 0s - loss: 0.0529 - acc: 0.9833     
Epoch 176/200
120/120 [==============================] - 0s - loss: 0.0526 - acc: 0.9833     
Epoch 177/200
120/120 [==============================] - 0s - loss: 0.0522 - acc: 0.9750     
Epoch 178/200
120/120 [==============================] - 0s - loss: 0.0519 - acc: 0.9750     
Epoch 179/200
120/120 [==============================] - 0s - loss: 0.0514 - acc: 0.9750     
Epoch 180/200
120/120 [==============================] - 0s - loss: 0.0510 - acc: 0.9833     
Epoch 181/200
120/120 [==============================] - 0s - loss: 0.0510 - acc: 0.9750     
Epoch 182/200
120/120 [==============================] - 0s - loss: 0.0505 - acc: 0.9833     
Epoch 183/200
120/120 [==============================] - 0s - loss: 0.0502 - acc: 0.9833     
Epoch 184/200
120/120 [==============================] - 0s - loss: 0.0501

In [13]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred_class, Y_test_class)

0.93333333333333335

In [15]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[16,  0,  0],
       [ 0,  4,  1],
       [ 0,  1,  8]], dtype=int64)