## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df = pd.read_csv('iris.data', header = None)
df.shape

(150, 5)

In [6]:
df.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [7]:
df.columns = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Class']

In [8]:
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth        Class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

## Creating X and Y

In [9]:
X = df.iloc[:, 0:4].values
Y = df.iloc[:, 4].values

In [10]:
X[0]

array([ 5.1,  3.5,  1.4,  0.2])

In [11]:
Y[0]

'Iris-setosa'

## Preprocess the Data

In [12]:
le_Y = LabelEncoder()

In [13]:
Y = le_Y.fit_transform(Y)
Y[0]

0

In [14]:
sc_X = StandardScaler()

In [15]:
X = sc_X.fit_transform(X)
X[0]

array([-0.90068117,  1.03205722, -1.3412724 , -1.31297673])

## Create Train and Test data

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [17]:
X_train.shape

(120, 4)

In [18]:
X_test.shape

(30, 4)

In [19]:
Y_train.shape

(120,)

In [20]:
Y_test.shape

(30,)

In [21]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
1  45
2  41
0  34

In [22]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  16
2   9
1   5

## Decision Tree Classifier

In [23]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [24]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
Y_pred_dt = clf_dt.predict(X_test)

In [26]:
confusion_matrix(Y_test, Y_pred_dt)

array([[16,  0,  0],
       [ 0,  4,  1],
       [ 0,  0,  9]], dtype=int64)

## Random Forest Classifier

In [27]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [28]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [29]:
Y_pred_rf = clf_rf.predict(X_test)

In [30]:
confusion_matrix(Y_test, Y_pred_rf)

array([[16,  0,  0],
       [ 0,  4,  1],
       [ 0,  0,  9]], dtype=int64)

## Naive Bayes Classifier

In [31]:
clf_nb = GaussianNB()

In [32]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [33]:
Y_pred_nb = clf_nb.predict(X_test)

In [34]:
confusion_matrix(Y_test, Y_pred_nb)

array([[16,  0,  0],
       [ 0,  5,  0],
       [ 0,  1,  8]], dtype=int64)

## KNN Classifier

In [35]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [36]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [37]:
Y_pred_knn = clf_knn.predict(X_test)

In [38]:
confusion_matrix(Y_test, Y_pred_knn)

array([[16,  0,  0],
       [ 0,  4,  1],
       [ 0,  1,  8]], dtype=int64)

## Logistic Regression

In [39]:
clf_lr = LogisticRegression()

In [40]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [41]:
Y_pred_lr = clf_lr.predict(X_test)

In [42]:
confusion_matrix(Y_test, Y_pred_lr)

array([[15,  1,  0],
       [ 0,  5,  0],
       [ 0,  1,  8]], dtype=int64)

## SVC Linear

In [43]:
clf_lsvc = SVC(kernel = "linear")

In [44]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [45]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [46]:
confusion_matrix(Y_test, Y_pred_lsvc)

array([[16,  0,  0],
       [ 0,  3,  2],
       [ 0,  1,  8]], dtype=int64)

## SVC Kernel

In [47]:
clf_ksvc = SVC(kernel = "rbf")

In [48]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [49]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [50]:
confusion_matrix(Y_test, Y_pred_ksvc)

array([[16,  0,  0],
       [ 0,  4,  1],
       [ 0,  1,  8]], dtype=int64)

## Accuracy of Various Classifiers

In [51]:
model_accuracies['DT'] = accuracy_score(Y_test, Y_pred_dt)
model_accuracies['KNN'] = accuracy_score(Y_test, Y_pred_knn)
model_accuracies['KernelSVC'] = accuracy_score(Y_test, Y_pred_ksvc)
model_accuracies['LinearSVC'] = accuracy_score(Y_test, Y_pred_lsvc)
model_accuracies['LogReg'] = accuracy_score(Y_test, Y_pred_lr)
model_accuracies['NB'] = accuracy_score(Y_test, Y_pred_nb)
model_accuracies['RF'] = accuracy_score(Y_test, Y_pred_rf)
model_accuracies

{'DT': 0.96666666666666667,
 'KNN': 0.93333333333333335,
 'KernelSVC': 0.93333333333333335,
 'LinearSVC': 0.90000000000000002,
 'LogReg': 0.93333333333333335,
 'NB': 0.96666666666666667,
 'RF': 0.96666666666666667}