## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df = pd.read_csv('iris.data', header = None)
df.shape

(150, 5)

In [6]:
df.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [7]:
df.columns = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Class']

In [8]:
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth        Class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

## Preprocess the Data

In [9]:
le_Class = LabelEncoder()

In [10]:
le_Class.fit(df['Class'])

LabelEncoder()

In [11]:
df['e_Class'] = df['Class'].map(lambda x : le_Class.transform([x]))

In [12]:
df['e_Class'] = df['e_Class'].map(lambda x : x[0])

In [13]:
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth        Class  e_Class
0          5.1         3.5          1.4         0.2  Iris-setosa        0
1          4.9         3.0          1.4         0.2  Iris-setosa        0
2          4.7         3.2          1.3         0.2  Iris-setosa        0
3          4.6         3.1          1.5         0.2  Iris-setosa        0
4          5.0         3.6          1.4         0.2  Iris-setosa        0

## Creating X and Y

In [14]:
Y = df['e_Class']
Y.shape

(150,)

In [15]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: e_Class, dtype: int64

In [16]:
X = df[['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']]
X.shape

(150, 4)

In [17]:
X.head()

SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

## Create Train and Test data

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 4)

In [26]:
X_train.shape

(112, 4)

In [27]:
X_test.shape

(38, 4)

In [28]:
Y_train.shape

(112,)

In [29]:
Y_test.shape

(38,)

In [30]:
pd.DataFrame(pd.DataFrame(Y_train)['e_Class'].value_counts())

e_Class
1       42
2       38
0       32

In [31]:
pd.DataFrame(pd.DataFrame(Y_test)['e_Class'].value_counts())

e_Class
0       18
2       12
1        8

## Decision Tree Classifier

In [32]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [33]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [34]:
Y_pred_dt = clf_dt.predict(X_test)

In [35]:
cm_dt = confusion_matrix(Y_pred_dt, Y_test)
cm_dt

array([[18,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 12]])

## Random Forest Classifier

In [36]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [37]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [38]:
Y_pred_rf = clf_rf.predict(X_test)

In [39]:
cm_rf = confusion_matrix(Y_pred_rf, Y_test)
cm_rf

array([[18,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 12]])

## Naive Bayes Classifier

In [40]:
clf_nb = GaussianNB()

In [41]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [42]:
Y_pred_nb = clf_nb.predict(X_test)

In [43]:
cm_nb = confusion_matrix(Y_pred_nb, Y_test)
cm_nb

array([[18,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 11]])

## KNN Classifier

In [44]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [45]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [46]:
Y_pred_knn = clf_knn.predict(X_test)

In [47]:
cm_knn = confusion_matrix(Y_pred_knn, Y_test)
cm_knn

array([[18,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 12]])

## Logistic Regression

In [48]:
clf_lr = LogisticRegression()

In [49]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [50]:
Y_pred_lr = clf_lr.predict(X_test)

In [51]:
cm_lr = confusion_matrix(Y_pred_lr, Y_test)
cm_lr

array([[18,  0,  0],
       [ 0,  6,  1],
       [ 0,  2, 11]])

## SVC Linear

In [52]:
clf_lsvc = SVC(kernel = "linear")

In [53]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [54]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [55]:
cm_lsvc = confusion_matrix(Y_pred_lsvc, Y_test)
cm_lsvc

array([[18,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 12]])

## SVC Kernel

In [56]:
clf_ksvc = SVC(kernel = "rbf")

In [57]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [58]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [59]:
cm_ksvc = confusion_matrix(Y_pred_ksvc, Y_test)
cm_ksvc

array([[18,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 12]])

## Accuracy of Various Classifiers

In [60]:
model_accuracies['DT'] = accuracy_score(Y_pred_dt, Y_test)
model_accuracies['KNN'] = accuracy_score(Y_pred_knn, Y_test)
model_accuracies['KernelSVC'] = accuracy_score(Y_pred_ksvc, Y_test)
model_accuracies['LinearSVC'] = accuracy_score(Y_pred_lsvc, Y_test)
model_accuracies['LogReg'] = accuracy_score(Y_pred_lr, Y_test)
model_accuracies['NB'] = accuracy_score(Y_pred_nb, Y_test)
model_accuracies['RF'] = accuracy_score(Y_pred_rf, Y_test)
model_accuracies

{'DT': 0.97368421052631582,
 'KNN': 0.97368421052631582,
 'KernelSVC': 0.97368421052631582,
 'LinearSVC': 0.97368421052631582,
 'LogReg': 0.92105263157894735,
 'NB': 0.97368421052631582,
 'RF': 0.97368421052631582}