## Initialization

In [1]:
import numpy as np
import pandas as pd
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("iris.data", header = None)
dataset.shape

(150, 5)

In [3]:
dataset.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:4].values
Y = dataset.iloc[:, 4:5].values

In [5]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [6]:
Y

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)
ohe = OneHotEncoder(categorical_features=[0])
Y = ohe.fit_transform(Y).toarray()
Y

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

In [8]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [9]:
X

array([[ -9.00681170e-01,   1.03205722e+00,  -1.34127240e+00,
         -1.31297673e+00],
       [ -1.14301691e+00,  -1.24957601e-01,  -1.34127240e+00,
         -1.31297673e+00],
       [ -1.38535265e+00,   3.37848329e-01,  -1.39813811e+00,
         -1.31297673e+00],
       [ -1.50652052e+00,   1.06445364e-01,  -1.28440670e+00,
         -1.31297673e+00],
       [ -1.02184904e+00,   1.26346019e+00,  -1.34127240e+00,
         -1.31297673e+00],
       [ -5.37177559e-01,   1.95766909e+00,  -1.17067529e+00,
         -1.05003079e+00],
       [ -1.50652052e+00,   8.00654259e-01,  -1.34127240e+00,
         -1.18150376e+00],
       [ -1.02184904e+00,   8.00654259e-01,  -1.28440670e+00,
         -1.31297673e+00],
       [ -1.74885626e+00,  -3.56360566e-01,  -1.34127240e+00,
         -1.31297673e+00],
       [ -1.14301691e+00,   1.06445364e-01,  -1.28440670e+00,
         -1.44444970e+00],
       [ -5.37177559e-01,   1.49486315e+00,  -1.28440670e+00,
         -1.31297673e+00],
       [ -1.26418478e

## Create Train and Test Data

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [19]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 4))

# Output Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=4, units=8, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="softmax", units=3)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
120/120 [==============================] - 0s - loss: 1.0961 - acc: 0.6083     
Epoch 2/200
120/120 [==============================] - 0s - loss: 1.0842 - acc: 0.6583     
Epoch 3/200
120/120 [==============================] - 0s - loss: 1.0606 - acc: 0.6583     
Epoch 4/200
120/120 [==============================] - 0s - loss: 1.0211 - acc: 0.7333     
Epoch 5/200
120/120 [==============================] - 0s - loss: 0.9633 - acc: 0.8833     
Epoch 6/200
120/120 [==============================] - 0s - loss: 0.8966 - acc: 0.7083     
Epoch 7/200
120/120 [==============================] - 0s - loss: 0.8242 - acc: 0.6667     
Epoch 8/200
120/120 [==============================] - 0s - loss: 0.7581 - acc: 0.6500     
Epoch 9/200
120/120 [==============================] - 0s - loss: 0.6996 - acc: 0.6500     
Epoch 10/200
120/120 [==============================] - 0s - loss: 0.6509 - acc: 0.6500     
Epoch 11/200
120/120 [==============================] - 0s - loss: 0.6133 - acc

120/120 [==============================] - 0s - loss: 0.1359 - acc: 0.9750     
Epoch 90/200
120/120 [==============================] - 0s - loss: 0.1332 - acc: 0.9750     
Epoch 91/200
120/120 [==============================] - 0s - loss: 0.1315 - acc: 0.9750     
Epoch 92/200
120/120 [==============================] - 0s - loss: 0.1288 - acc: 0.9750     
Epoch 93/200
120/120 [==============================] - 0s - loss: 0.1273 - acc: 0.9667     
Epoch 94/200
120/120 [==============================] - 0s - loss: 0.1252 - acc: 0.9750     
Epoch 95/200
120/120 [==============================] - 0s - loss: 0.1234 - acc: 0.9750     
Epoch 96/200
120/120 [==============================] - 0s - loss: 0.1215 - acc: 0.9750     
Epoch 97/200
120/120 [==============================] - 0s - loss: 0.1202 - acc: 0.9750     
Epoch 98/200
120/120 [==============================] - 0s - loss: 0.1182 - acc: 0.9833     
Epoch 99/200
120/120 [==============================] - 0s - loss: 0.1163 - acc: 0.

120/120 [==============================] - 0s - loss: 0.0556 - acc: 0.9833     
Epoch 177/200
120/120 [==============================] - 0s - loss: 0.0548 - acc: 0.9833     
Epoch 178/200
120/120 [==============================] - 0s - loss: 0.0545 - acc: 0.9833     
Epoch 179/200
120/120 [==============================] - 0s - loss: 0.0542 - acc: 0.9833     
Epoch 180/200
120/120 [==============================] - 0s - loss: 0.0539 - acc: 0.9833     
Epoch 181/200
120/120 [==============================] - 0s - loss: 0.0540 - acc: 0.9750     
Epoch 182/200
120/120 [==============================] - 0s - loss: 0.0531 - acc: 0.9833     
Epoch 183/200
120/120 [==============================] - 0s - loss: 0.0532 - acc: 0.9750     
Epoch 184/200
120/120 [==============================] - 0s - loss: 0.0525 - acc: 0.9833     
Epoch 185/200
120/120 [==============================] - 0s - loss: 0.0523 - acc: 0.9833     
Epoch 186/200
120/120 [==============================] - 0s - loss: 0.0520

In [20]:
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_pred, Y_test)

0.93333333333333335