## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("Car.data", header = None)
dataset.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

## Create X and Y

In [3]:
X = dataset.iloc[:, 0:6].values
Y = dataset.iloc[:, 6].values

In [4]:
X.shape

(1728, 6)

In [5]:
Y.shape

(1728,)

In [6]:
X

array([['vhigh', 'vhigh', '2', '2', 'small', 'low'],
       ['vhigh', 'vhigh', '2', '2', 'small', 'med'],
       ['vhigh', 'vhigh', '2', '2', 'small', 'high'],
       ..., 
       ['low', 'low', '5more', 'more', 'big', 'low'],
       ['low', 'low', '5more', 'more', 'big', 'med'],
       ['low', 'low', '5more', 'more', 'big', 'high']], dtype=object)

In [7]:
Y

array(['unacc', 'unacc', 'unacc', ..., 'unacc', 'good', 'vgood'], dtype=object)

## Preprocess the Data

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)

def encoder(index):
    le = LabelEncoder()
    X[:, index] = le.fit_transform(X[:, index])

In [9]:
for i in range(0, 6):
    encoder(i)

In [10]:
X

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ..., 
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]], dtype=object)

In [11]:
Y

array([[2],
       [2],
       [2],
       ..., 
       [2],
       [1],
       [3]], dtype=int64)

In [12]:
ohe_Y = OneHotEncoder(categorical_features = [0])
Y = ohe_Y.fit_transform(Y).toarray()

In [13]:
Y

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       ..., 
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [14]:
ohe_X = OneHotEncoder(categorical_features = [5])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [15]:
ohe_X = OneHotEncoder(categorical_features = [6])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [16]:
ohe_X = OneHotEncoder(categorical_features = [7])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [17]:
ohe_X = OneHotEncoder(categorical_features = [8])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [18]:
ohe_X = OneHotEncoder(categorical_features = [10])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [19]:
ohe_X = OneHotEncoder(categorical_features = [12])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [20]:
X.shape

(1728, 15)

## Create Train and Test Data

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [22]:
from keras.models import Sequential
from keras.layers import Dense
clf_ann = Sequential()

In [23]:
# First Hidden Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu', input_dim = 15))

# Output Layer
clf_ann.add(Dense(output_dim = 4, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=10, input_dim=15, kernel_initializer="uniform")`
  from ipykernel import kernelapp as app
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=4, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
1382/1382 [==============================] - 0s - loss: 0.9940 - acc: 0.6954       
Epoch 2/200
1382/1382 [==============================] - 0s - loss: 0.7109 - acc: 0.7012     
Epoch 3/200
1382/1382 [==============================] - 0s - loss: 0.6047 - acc: 0.7019     
Epoch 4/200
1382/1382 [==============================] - 0s - loss: 0.5304 - acc: 0.7373     
Epoch 5/200
1382/1382 [==============================] - 0s - loss: 0.4778 - acc: 0.7945     
Epoch 6/200
1382/1382 [==============================] - 0s - loss: 0.4386 - acc: 0.8111     
Epoch 7/200
1382/1382 [==============================] - 0s - loss: 0.4084 - acc: 0.8292     
Epoch 8/200
1382/1382 [==============================] - 0s - loss: 0.3851 - acc: 0.8452     
Epoch 9/200
1382/1382 [==============================] - 0s - loss: 0.3660 - acc: 0.8415     
Epoch 10/200
1382/1382 [==============================] - 0s - loss: 0.3489 - acc: 0.8560     
Epoch 11/200
1382/1382 [==============================] -

1382/1382 [==============================] - 0s - loss: 0.0792 - acc: 0.9790     
Epoch 88/200
1382/1382 [==============================] - 0s - loss: 0.0780 - acc: 0.9776     
Epoch 89/200
1382/1382 [==============================] - 0s - loss: 0.0766 - acc: 0.9812     
Epoch 90/200
1382/1382 [==============================] - 0s - loss: 0.0753 - acc: 0.9790     
Epoch 91/200
1382/1382 [==============================] - 0s - loss: 0.0744 - acc: 0.9776     
Epoch 92/200
1382/1382 [==============================] - 0s - loss: 0.0724 - acc: 0.9805     
Epoch 93/200
1382/1382 [==============================] - 0s - loss: 0.0712 - acc: 0.9812     
Epoch 94/200
1382/1382 [==============================] - 0s - loss: 0.0707 - acc: 0.9819     
Epoch 95/200
1382/1382 [==============================] - 0s - loss: 0.0684 - acc: 0.9826     - ETA: 0s - loss: 0.0724 - acc: 0.98
Epoch 96/200
1382/1382 [==============================] - 0s - loss: 0.0669 - acc: 0.9819     
Epoch 97/200
1382/1382 [===

1382/1382 [==============================] - 0s - loss: 0.0176 - acc: 1.0000     
Epoch 173/200
1382/1382 [==============================] - 0s - loss: 0.0174 - acc: 1.0000       
Epoch 174/200
1382/1382 [==============================] - 0s - loss: 0.0173 - acc: 1.0000     
Epoch 175/200
1382/1382 [==============================] - 0s - loss: 0.0166 - acc: 1.0000     
Epoch 176/200
1382/1382 [==============================] - 0s - loss: 0.0162 - acc: 1.0000     
Epoch 177/200
1382/1382 [==============================] - 0s - loss: 0.0161 - acc: 1.0000     
Epoch 178/200
1382/1382 [==============================] - 0s - loss: 0.0158 - acc: 1.0000     
Epoch 179/200
1382/1382 [==============================] - 0s - loss: 0.0156 - acc: 1.0000     
Epoch 180/200
1382/1382 [==============================] - 0s - loss: 0.0150 - acc: 1.0000     
Epoch 181/200
1382/1382 [==============================] - 0s - loss: 0.0152 - acc: 1.0000     
Epoch 182/200
1382/1382 [===========================

In [24]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred_class, Y_test_class)

0.98843930635838151

In [26]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[ 81,   0,   0,   0],
       [  2,  11,   0,   0],
       [  0,   0, 241,   0],
       [  0,   2,   0,   9]], dtype=int64)