## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("Car.data", header = None)
dataset.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

## Create X and Y

In [3]:
X = dataset.iloc[:, 0:6].values
Y = dataset.iloc[:, 6].values

In [4]:
X.shape

(1728, 6)

In [5]:
Y.shape

(1728,)

In [6]:
X[0]

array(['vhigh', 'vhigh', '2', '2', 'small', 'low'], dtype=object)

In [7]:
Y[0]

'unacc'

## Preprocess the Data

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)

def encoder(index):
    le = LabelEncoder()
    X[:, index] = le.fit_transform(X[:, index])

In [9]:
for i in range(0, 6):
    encoder(i)

In [10]:
X[0]

array([3, 3, 0, 0, 2, 1], dtype=object)

In [11]:
Y[0]

array([2], dtype=int64)

In [12]:
ohe_Y = OneHotEncoder(categorical_features = [0])
Y = ohe_Y.fit_transform(Y).toarray()

In [13]:
Y[0]

array([ 0.,  0.,  1.,  0.])

In [14]:
ohe_X = OneHotEncoder(categorical_features = [5])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [15]:
ohe_X = OneHotEncoder(categorical_features = [6])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [16]:
ohe_X = OneHotEncoder(categorical_features = [7])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [17]:
ohe_X = OneHotEncoder(categorical_features = [8])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [18]:
ohe_X = OneHotEncoder(categorical_features = [10])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [19]:
ohe_X = OneHotEncoder(categorical_features = [12])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [20]:
X.shape

(1728, 15)

## Create Train and Test Data

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [22]:
from keras.models import Sequential
from keras.layers import Dense
clf_ann = Sequential()

In [23]:
# First Hidden Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu', input_dim = 15))

# Output Layer
clf_ann.add(Dense(output_dim = 4, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=10, kernel_initializer="uniform", input_dim=15, activation="relu")`
  from ipykernel import kernelapp as app
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=4, kernel_initializer="uniform", activation="softmax")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
1382/1382 [==============================] - 0s - loss: 0.9904 - acc: 0.6968     
Epoch 2/200
1382/1382 [==============================] - 0s - loss: 0.7170 - acc: 0.7012     
Epoch 3/200
1382/1382 [==============================] - 0s - loss: 0.6122 - acc: 0.7012     
Epoch 4/200
1382/1382 [==============================] - 0s - loss: 0.5400 - acc: 0.7279     
Epoch 5/200
1382/1382 [==============================] - 0s - loss: 0.4844 - acc: 0.7815     
Epoch 6/200
1382/1382 [==============================] - 0s - loss: 0.4405 - acc: 0.8133     
Epoch 7/200
1382/1382 [==============================] - 0s - loss: 0.4092 - acc: 0.8314     
Epoch 8/200
1382/1382 [==============================] - 0s - loss: 0.3855 - acc: 0.8423     
Epoch 9/200
1382/1382 [==============================] - 0s - loss: 0.3655 - acc: 0.8452     
Epoch 10/200
1382/1382 [==============================] - 0s - loss: 0.3491 - acc: 0.8567     
Epoch 11/200
1382/1382 [==============================] - 0

1382/1382 [==============================] - 0s - loss: 0.0671 - acc: 0.9819     
Epoch 88/200
1382/1382 [==============================] - 0s - loss: 0.0675 - acc: 0.9826     
Epoch 89/200
1382/1382 [==============================] - 0s - loss: 0.0665 - acc: 0.9834     
Epoch 90/200
1382/1382 [==============================] - 0s - loss: 0.0663 - acc: 0.9834     
Epoch 91/200
1382/1382 [==============================] - 0s - loss: 0.0659 - acc: 0.9834     
Epoch 92/200
1382/1382 [==============================] - 0s - loss: 0.0645 - acc: 0.9841       
Epoch 93/200
1382/1382 [==============================] - 0s - loss: 0.0633 - acc: 0.9826     
Epoch 94/200
1382/1382 [==============================] - 0s - loss: 0.0637 - acc: 0.9863     
Epoch 95/200
1382/1382 [==============================] - 0s - loss: 0.0619 - acc: 0.9848     
Epoch 96/200
1382/1382 [==============================] - 0s - loss: 0.0639 - acc: 0.9855     
Epoch 97/200
1382/1382 [==============================] - 0s 

1382/1382 [==============================] - 0s - loss: 0.0362 - acc: 0.9913       
Epoch 172/200
1382/1382 [==============================] - 0s - loss: 0.0361 - acc: 0.9906     
Epoch 173/200
1382/1382 [==============================] - 0s - loss: 0.0352 - acc: 0.9913     
Epoch 174/200
1382/1382 [==============================] - 0s - loss: 0.0357 - acc: 0.9913       
Epoch 175/200
1382/1382 [==============================] - 0s - loss: 0.0348 - acc: 0.9935     
Epoch 176/200
1382/1382 [==============================] - 0s - loss: 0.0344 - acc: 0.9913     
Epoch 177/200
1382/1382 [==============================] - 0s - loss: 0.0339 - acc: 0.9906     
Epoch 178/200
1382/1382 [==============================] - 0s - loss: 0.0340 - acc: 0.9928     
Epoch 179/200
1382/1382 [==============================] - 0s - loss: 0.0330 - acc: 0.9913     
Epoch 180/200
1382/1382 [==============================] - 0s - loss: 0.0339 - acc: 0.9920       
Epoch 181/200
1382/1382 [=======================

In [24]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test_class, Y_pred_class)

0.99132947976878616

In [26]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[ 83,   0,   0,   0],
       [  0,  11,   0,   2],
       [  1,   0, 240,   0],
       [  0,   0,   0,   9]], dtype=int64)