## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("Car.data", header = None)
dataset.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

## Create X and Y

In [3]:
X = dataset.iloc[:, 0:6].values
Y = dataset.iloc[:, 6].values

In [4]:
X.shape

(1728, 6)

In [5]:
Y.shape

(1728,)

In [6]:
X

array([['vhigh', 'vhigh', '2', '2', 'small', 'low'],
       ['vhigh', 'vhigh', '2', '2', 'small', 'med'],
       ['vhigh', 'vhigh', '2', '2', 'small', 'high'],
       ..., 
       ['low', 'low', '5more', 'more', 'big', 'low'],
       ['low', 'low', '5more', 'more', 'big', 'med'],
       ['low', 'low', '5more', 'more', 'big', 'high']], dtype=object)

In [7]:
Y

array(['unacc', 'unacc', 'unacc', ..., 'unacc', 'good', 'vgood'], dtype=object)

## Preprocess the Data

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)

def encoder(index):
    le = LabelEncoder()
    X[:, index] = le.fit_transform(X[:, index])

In [9]:
for i in range(0, 6):
    encoder(i)

In [10]:
X

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ..., 
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]], dtype=object)

In [11]:
Y

array([[2],
       [2],
       [2],
       ..., 
       [2],
       [1],
       [3]], dtype=int64)

In [12]:
ohe_Y = OneHotEncoder(categorical_features = [0])
Y = ohe_Y.fit_transform(Y).toarray()

In [13]:
Y

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       ..., 
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [14]:
ohe_X = OneHotEncoder(categorical_features = [5])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [15]:
ohe_X = OneHotEncoder(categorical_features = [6])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [16]:
ohe_X = OneHotEncoder(categorical_features = [7])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [17]:
ohe_X = OneHotEncoder(categorical_features = [8])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [18]:
ohe_X = OneHotEncoder(categorical_features = [10])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [19]:
ohe_X = OneHotEncoder(categorical_features = [12])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [20]:
X.shape

(1728, 15)

## Create Train and Test Data

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [22]:
from keras.models import Sequential
from keras.layers import Dense
clf_ann = Sequential()

In [23]:
# First Hidden Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu', input_dim = 15))

# Output Layer
clf_ann.add(Dense(output_dim = 4, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=10, kernel_initializer="uniform", activation="relu", input_dim=15)`
  from ipykernel import kernelapp as app
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=4, kernel_initializer="uniform", activation="softmax")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
1382/1382 [==============================] - 0s - loss: 1.0123 - acc: 0.6968     
Epoch 2/200
1382/1382 [==============================] - 0s - loss: 0.6993 - acc: 0.7012     
Epoch 3/200
1382/1382 [==============================] - 0s - loss: 0.5757 - acc: 0.7041     
Epoch 4/200
1382/1382 [==============================] - 0s - loss: 0.5032 - acc: 0.7612     
Epoch 5/200
1382/1382 [==============================] - 0s - loss: 0.4558 - acc: 0.8032     
Epoch 6/200
1382/1382 [==============================] - 0s - loss: 0.4231 - acc: 0.8256     
Epoch 7/200
1382/1382 [==============================] - 0s - loss: 0.3959 - acc: 0.8350     
Epoch 8/200
1382/1382 [==============================] - 0s - loss: 0.3750 - acc: 0.8480     
Epoch 9/200
1382/1382 [==============================] - 0s - loss: 0.3580 - acc: 0.8466     
Epoch 10/200
1382/1382 [==============================] - 0s - loss: 0.3403 - acc: 0.8575     
Epoch 11/200
1382/1382 [==============================] - 0

1382/1382 [==============================] - 0s - loss: 0.0802 - acc: 0.9761     
Epoch 88/200
1382/1382 [==============================] - 0s - loss: 0.0787 - acc: 0.9776     
Epoch 89/200
1382/1382 [==============================] - 0s - loss: 0.0771 - acc: 0.9768     
Epoch 90/200
1382/1382 [==============================] - 0s - loss: 0.0765 - acc: 0.9740     
Epoch 91/200
1382/1382 [==============================] - 0s - loss: 0.0766 - acc: 0.9747     
Epoch 92/200
1382/1382 [==============================] - 0s - loss: 0.0749 - acc: 0.9768     
Epoch 93/200
1382/1382 [==============================] - 0s - loss: 0.0730 - acc: 0.9790       
Epoch 94/200
1382/1382 [==============================] - 0s - loss: 0.0734 - acc: 0.9790     
Epoch 95/200
1382/1382 [==============================] - 0s - loss: 0.0713 - acc: 0.9776     
Epoch 96/200
1382/1382 [==============================] - 0s - loss: 0.0713 - acc: 0.9776     
Epoch 97/200
1382/1382 [==============================] - 0s 

1382/1382 [==============================] - 0s - loss: 0.0320 - acc: 0.9935     
Epoch 173/200
1382/1382 [==============================] - 0s - loss: 0.0310 - acc: 0.9942     
Epoch 174/200
1382/1382 [==============================] - 0s - loss: 0.0311 - acc: 0.9942     
Epoch 175/200
1382/1382 [==============================] - 0s - loss: 0.0314 - acc: 0.9942     
Epoch 176/200
1382/1382 [==============================] - 0s - loss: 0.0305 - acc: 0.9949       
Epoch 177/200
1382/1382 [==============================] - 0s - loss: 0.0302 - acc: 0.9942       
Epoch 178/200
1382/1382 [==============================] - 0s - loss: 0.0305 - acc: 0.9949     
Epoch 179/200
1382/1382 [==============================] - 0s - loss: 0.0299 - acc: 0.9920     
Epoch 180/200
1382/1382 [==============================] - 0s - loss: 0.0300 - acc: 0.9942     
Epoch 181/200
1382/1382 [==============================] - 0s - loss: 0.0297 - acc: 0.9942     
Epoch 182/200
1382/1382 [=========================

In [24]:
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_pred, Y_test)

0.98554913294797686