## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
dataset.shape

(9568, 5)

In [3]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:4].values
Y = dataset.iloc[:, 4].values

In [5]:
X.shape

(9568, 4)

In [6]:
Y.shape

(9568,)

In [7]:
X

array([[   14.96,    41.76,  1024.07,    73.17],
       [   25.18,    62.96,  1020.04,    59.08],
       [    5.11,    39.4 ,  1012.16,    92.14],
       ..., 
       [   31.32,    74.33,  1012.92,    36.48],
       [   24.48,    69.45,  1013.86,    62.39],
       [   21.6 ,    62.52,  1017.23,    67.87]])

In [8]:
Y

array([ 463.26,  444.37,  488.56, ...,  429.57,  435.74,  453.28])

## Preprocess the Data

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
sc_X = StandardScaler()

In [11]:
X = sc_X.fit_transform(X)

In [12]:
X

array([[-0.62951938, -0.98729659,  1.8204884 , -0.00951935],
       [ 0.74190911,  0.68104512,  1.1418628 , -0.97462052],
       [-1.95129733, -1.17301765, -0.18507756,  1.2898397 ],
       ..., 
       [ 1.56583973,  1.57581141, -0.05709854, -2.52261812],
       [ 0.64797565,  1.19177803,  0.1011913 , -0.74790051],
       [ 0.26150656,  0.64641916,  0.66867722, -0.37254534]])

## Create Train and Test Data

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [15]:
X_train.shape

(7654, 4)

In [16]:
X_test.shape

(1914, 4)

In [17]:
Y_train.shape

(7654,)

In [18]:
Y_test.shape

(1914,)

## Create and train the ANN Regressor

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 64, init = 'uniform', activation = 'relu', input_dim = 4))

# Second Hidden Layer
#clf_ann.add(Dense(output_dim = 16, init = 'uniform', activation = 'relu'))

#clf_ann.add(Dense(output_dim = 24, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=64, input_dim=4, activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
7654/7654 [==============================] - 0s - loss: 132245.3959     
Epoch 2/100
7654/7654 [==============================] - 0s - loss: 17453.8293     
Epoch 3/100
7654/7654 [==============================] - 0s - loss: 4334.1073     
Epoch 4/100
7654/7654 [==============================] - 0s - loss: 487.7196     
Epoch 5/100
7654/7654 [==============================] - 0s - loss: 59.7128     
Epoch 6/100
7654/7654 [==============================] - 0s - loss: 24.6979     
Epoch 7/100
7654/7654 [==============================] - 0s - loss: 21.2363     
Epoch 8/100
7654/7654 [==============================] - 0s - loss: 20.6876     
Epoch 9/100
7654/7654 [==============================] - 0s - loss: 20.3010     
Epoch 10/100
7654/7654 [==============================] - 0s - loss: 20.1631     
Epoch 11/100
7654/7654 [==============================] - 0s - loss: 19.8953     
Epoch 12/100
7654/7654 [==============================] - 0s - loss: 19.8169     
Epoch 13/100
76

7654/7654 [==============================] - 0s - loss: 18.2816     
Epoch 99/100
7654/7654 [==============================] - 0s - loss: 18.2518     
Epoch 100/100
7654/7654 [==============================] - 0s - loss: 18.1988     


In [21]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)

## Check the Accuracy

In [22]:
from sklearn.metrics import mean_squared_error, r2_score

In [23]:
mean_squared_error(Y_pred, Y_test)

20.050237673338287

In [24]:
r2_score(Y_pred, Y_test)

0.93270840321723147