## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_excel('Blogger.xlsx')
dataset.shape

(100, 6)

In [3]:
dataset.head()

Degree caprice       topic  lmt lpss   pb
0    high    left  impression  yes  yes  yes
1    high    left   political  yes  yes  yes
2  medium  middle     tourism  yes  yes  yes
3    high    left   political  yes  yes  yes
4  medium  middle        news  yes  yes  yes

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:5].values
Y = dataset.iloc[:, 5].values

## Preprocess the Data

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)

In [6]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1], dtype=int64)

In [7]:
le0 = LabelEncoder()
le1 = LabelEncoder()
le2 = LabelEncoder()

X[:, 0] = le0.fit_transform(X[:, 0])
X[:, 1] = le1.fit_transform(X[:, 1])
X[:, 2] = le2.fit_transform(X[:, 2])
X[:, 3] = le_Y.transform(X[:, 3])
X[:, 4] = le_Y.transform(X[:, 4])

In [8]:
X[0]

array([0, 0, 0, 1, 1], dtype=object)

In [9]:
ohe0 = OneHotEncoder(categorical_features = [0])
X = ohe0.fit_transform(X).toarray()
X = X[:, 1:]

In [10]:
ohe1 = OneHotEncoder(categorical_features = [2])
X = ohe1.fit_transform(X).toarray()
X = X[:, 1:]

In [11]:
ohe1 = OneHotEncoder(categorical_features = [4])
X = ohe1.fit_transform(X).toarray()
X = X[:, 1:]

## Create Train and Test Data

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu', input_dim = 10))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=5, input_dim=10, kernel_initializer="uniform", activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=10, activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=1, activation="sigmoid")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
80/80 [==============================] - 0s - loss: 0.6921 - acc: 0.6875     
Epoch 2/200
80/80 [==============================] - 0s - loss: 0.6896 - acc: 0.7000     
Epoch 3/200
80/80 [==============================] - 0s - loss: 0.6869 - acc: 0.7000     
Epoch 4/200
80/80 [==============================] - 0s - loss: 0.6836 - acc: 0.7000     
Epoch 5/200
80/80 [==============================] - 0s - loss: 0.6794 - acc: 0.7000     
Epoch 6/200
80/80 [==============================] - 0s - loss: 0.6742 - acc: 0.7000     
Epoch 7/200
80/80 [==============================] - 0s - loss: 0.6673 - acc: 0.7000     
Epoch 8/200
80/80 [==============================] - 0s - loss: 0.6589 - acc: 0.7000     
Epoch 9/200
80/80 [==============================] - 0s - loss: 0.6484 - acc: 0.7000     
Epoch 10/200
80/80 [==============================] - 0s - loss: 0.6381 - acc: 0.7000     
Epoch 11/200
80/80 [==============================] - 0s - loss: 0.6274 - acc: 0.7000     
Epoch 12

80/80 [==============================] - 0s - loss: 0.4672 - acc: 0.7625     
Epoch 91/200
80/80 [==============================] - 0s - loss: 0.4659 - acc: 0.7750     
Epoch 92/200
80/80 [==============================] - 0s - loss: 0.4662 - acc: 0.7750     
Epoch 93/200
80/80 [==============================] - 0s - loss: 0.4652 - acc: 0.7750     
Epoch 94/200
80/80 [==============================] - 0s - loss: 0.4626 - acc: 0.7750     
Epoch 95/200
80/80 [==============================] - 0s - loss: 0.4607 - acc: 0.7750     
Epoch 96/200
80/80 [==============================] - 0s - loss: 0.4615 - acc: 0.7625     
Epoch 97/200
80/80 [==============================] - 0s - loss: 0.4584 - acc: 0.7875     
Epoch 98/200
80/80 [==============================] - 0s - loss: 0.4578 - acc: 0.7750     
Epoch 99/200
80/80 [==============================] - 0s - loss: 0.4564 - acc: 0.7750     
Epoch 100/200
80/80 [==============================] - 0s - loss: 0.4554 - acc: 0.7875     
Epoch 101/2

80/80 [==============================] - 0s - loss: 0.3966 - acc: 0.8625     
Epoch 180/200
80/80 [==============================] - 0s - loss: 0.3963 - acc: 0.8625     
Epoch 181/200
80/80 [==============================] - 0s - loss: 0.3959 - acc: 0.8625     
Epoch 182/200
80/80 [==============================] - 0s - loss: 0.3951 - acc: 0.8625     
Epoch 183/200
80/80 [==============================] - 0s - loss: 0.3948 - acc: 0.8625     
Epoch 184/200
80/80 [==============================] - 0s - loss: 0.3945 - acc: 0.8625     
Epoch 185/200
80/80 [==============================] - 0s - loss: 0.3923 - acc: 0.8625     
Epoch 186/200
80/80 [==============================] - 0s - loss: 0.3934 - acc: 0.8625     
Epoch 187/200
80/80 [==============================] - 0s - loss: 0.3911 - acc: 0.8625     
Epoch 188/200
80/80 [==============================] - 0s - loss: 0.3905 - acc: 0.8625     
Epoch 189/200
80/80 [==============================] - 0s - loss: 0.3896 - acc: 0.8625     
Ep

In [15]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test, Y_pred)

0.84999999999999998

In [17]:
confusion_matrix(Y_test, Y_pred)

array([[ 7,  1],
       [ 2, 10]], dtype=int64)