## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df = pd.read_excel('Blogger.xlsx')
df.shape

(100, 6)

In [6]:
df.head()

Degree caprice       topic  lmt lpss   pb
0    high    left  impression  yes  yes  yes
1    high    left   political  yes  yes  yes
2  medium  middle     tourism  yes  yes  yes
3    high    left   political  yes  yes  yes
4  medium  middle        news  yes  yes  yes

## Create X and Y

In [7]:
X = df.iloc[:, 0:5].values
Y = df.iloc[:, 5].values

## Preprocess the data

In [8]:
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1], dtype=int64)

In [9]:
le0 = LabelEncoder()
le1 = LabelEncoder()
le2 = LabelEncoder()

X[:, 0] = le0.fit_transform(X[:, 0])
X[:, 1] = le1.fit_transform(X[:, 1])
X[:, 2] = le2.fit_transform(X[:, 2])
X[:, 3] = le_Y.transform(X[:, 3])
X[:, 4] = le_Y.transform(X[:, 4])
X[0]

array([0, 0, 0, 1, 1], dtype=object)

In [10]:
ohe0 = OneHotEncoder(categorical_features = [0])
X = ohe0.fit_transform(X).toarray()
X = X[:, 1:]

In [11]:
ohe1 = OneHotEncoder(categorical_features = [2])
X = ohe1.fit_transform(X).toarray()
X = X[:, 1:]

In [12]:
ohe1 = OneHotEncoder(categorical_features = [4])
X = ohe1.fit_transform(X).toarray()
X = X[:, 1:]
X[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.])

## Create Train and Test data

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [14]:
X_train.shape

(80, 10)

In [15]:
X_test.shape

(20, 10)

In [16]:
Y_train.shape

(80,)

In [17]:
Y_test.shape

(20,)

In [18]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
1  56
0  24

In [19]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
1  12
0   8

## Decision Tree Classifier

In [20]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [21]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [22]:
Y_pred_dt = clf_dt.predict(X_test)

In [23]:
confusion_matrix(Y_test, Y_pred_dt)

array([[ 6,  2],
       [ 1, 11]], dtype=int64)

## Random Forest Classifier

In [24]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [25]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [26]:
Y_pred_rf = clf_rf.predict(X_test)

In [27]:
confusion_matrix(Y_test, Y_pred_rf)

array([[ 4,  4],
       [ 1, 11]], dtype=int64)

## Naive Bayes Classifier

In [28]:
clf_nb = GaussianNB()

In [29]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [30]:
Y_pred_nb = clf_nb.predict(X_test)

In [31]:
confusion_matrix(Y_test, Y_pred_nb)

array([[ 6,  2],
       [ 2, 10]], dtype=int64)

## KNN Classifier

In [32]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [33]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [34]:
Y_pred_knn = clf_knn.predict(X_test)

In [35]:
confusion_matrix(Y_test, Y_pred_knn)

array([[ 5,  3],
       [ 1, 11]], dtype=int64)

## Logistic Regression

In [36]:
clf_lr = LogisticRegression()

In [37]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [38]:
Y_pred_lr = clf_lr.predict(X_test)

In [39]:
confusion_matrix(Y_test, Y_pred_lr)

array([[ 4,  4],
       [ 2, 10]], dtype=int64)

## SVC Linear

In [40]:
clf_lsvc = SVC(kernel = "linear")

In [41]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [42]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [43]:
confusion_matrix(Y_test, Y_pred_lsvc)

array([[ 3,  5],
       [ 1, 11]], dtype=int64)

## SVC Kernel

In [44]:
clf_ksvc = SVC(kernel = "rbf")

In [45]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [46]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [47]:
confusion_matrix(Y_test, Y_pred_ksvc)

array([[ 0,  8],
       [ 0, 12]], dtype=int64)

## Accuracy of Various Classifiers

In [48]:
model_accuracies['DT'] = accuracy_score(Y_test, Y_pred_dt)
model_accuracies['KNN'] = accuracy_score(Y_test, Y_pred_knn)
model_accuracies['KernelSVC'] = accuracy_score(Y_test, Y_pred_ksvc)
model_accuracies['LinearSVC'] = accuracy_score(Y_test, Y_pred_lsvc)
model_accuracies['LogReg'] = accuracy_score(Y_test, Y_pred_lr)
model_accuracies['NB'] = accuracy_score(Y_test, Y_pred_nb)
model_accuracies['RF'] = accuracy_score(Y_test, Y_pred_rf)
model_accuracies

{'DT': 0.84999999999999998,
 'KNN': 0.80000000000000004,
 'KernelSVC': 0.59999999999999998,
 'LinearSVC': 0.69999999999999996,
 'LogReg': 0.69999999999999996,
 'NB': 0.80000000000000004,
 'RF': 0.75}