## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_excel('Blogger.xlsx')
dataset.shape

(100, 6)

In [3]:
dataset.head()

Degree caprice       topic  lmt lpss   pb
0    high    left  impression  yes  yes  yes
1    high    left   political  yes  yes  yes
2  medium  middle     tourism  yes  yes  yes
3    high    left   political  yes  yes  yes
4  medium  middle        news  yes  yes  yes

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:5].values
Y = dataset.iloc[:, 5].values

## Preprocess the Data

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)

In [6]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1], dtype=int64)

In [7]:
le0 = LabelEncoder()
le1 = LabelEncoder()
le2 = LabelEncoder()

X[:, 0] = le0.fit_transform(X[:, 0])
X[:, 1] = le1.fit_transform(X[:, 1])
X[:, 2] = le2.fit_transform(X[:, 2])
X[:, 3] = le_Y.transform(X[:, 3])
X[:, 4] = le_Y.transform(X[:, 4])

In [8]:
X

array([[0, 0, 0, 1, 1],
       [0, 0, 2, 1, 1],
       [2, 1, 4, 1, 1],
       [0, 0, 2, 1, 1],
       [2, 1, 1, 1, 1],
       [2, 1, 1, 1, 1],
       [0, 0, 2, 1, 1],
       [0, 2, 2, 1, 0],
       [0, 2, 2, 1, 0],
       [2, 2, 4, 1, 0],
       [0, 2, 4, 1, 1],
       [2, 0, 1, 1, 0],
       [0, 0, 2, 1, 1],
       [1, 2, 1, 0, 1],
       [0, 0, 2, 1, 1],
       [2, 0, 0, 1, 1],
       [2, 0, 2, 1, 1],
       [0, 2, 2, 1, 1],
       [2, 0, 0, 1, 1],
       [0, 2, 4, 1, 1],
       [0, 0, 2, 1, 1],
       [2, 0, 1, 1, 1],
       [0, 2, 2, 0, 1],
       [1, 0, 4, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 0, 2, 1, 1],
       [1, 2, 0, 0, 0],
       [0, 2, 2, 1, 1],
       [0, 0, 0, 0, 0],
       [2, 0, 3, 1, 1],
       [0, 2, 2, 1, 1],
       [1, 0, 3, 1, 1],
       [2, 2, 4, 1, 1],
       [1, 2, 2, 1, 1],
       [0, 0, 0, 1, 0],
       [2, 0, 4, 1, 0],
       [2, 1, 3, 1, 0],
       [2, 1, 0, 0, 1],
       [2, 2, 3, 1, 1],
       [2, 0, 0, 0, 0],
       [0, 0, 2, 1, 1],
       [2, 0, 1,

In [9]:
ohe0 = OneHotEncoder(categorical_features = [0])
X = ohe0.fit_transform(X).toarray()
X = X[:, 1:]

In [10]:
ohe1 = OneHotEncoder(categorical_features = [2])
X = ohe1.fit_transform(X).toarray()
X = X[:, 1:]

In [11]:
ohe1 = OneHotEncoder(categorical_features = [4])
X = ohe1.fit_transform(X).toarray()
X = X[:, 1:]

## Create Train and Test Data

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu', input_dim = 10))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=10, kernel_initializer="uniform", activation="relu", units=5)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=10)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="sigmoid", units=1)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
80/80 [==============================] - 0s - loss: 0.6918 - acc: 0.6625     
Epoch 2/200
80/80 [==============================] - 0s - loss: 0.6893 - acc: 0.7000     
Epoch 3/200
80/80 [==============================] - 0s - loss: 0.6862 - acc: 0.7000     
Epoch 4/200
80/80 [==============================] - 0s - loss: 0.6831 - acc: 0.7000     
Epoch 5/200
80/80 [==============================] - 0s - loss: 0.6792 - acc: 0.7000     
Epoch 6/200
80/80 [==============================] - 0s - loss: 0.6757 - acc: 0.7000     
Epoch 7/200
80/80 [==============================] - 0s - loss: 0.6716 - acc: 0.7000     
Epoch 8/200
80/80 [==============================] - 0s - loss: 0.6675 - acc: 0.7000     
Epoch 9/200
80/80 [==============================] - 0s - loss: 0.6635 - acc: 0.7000     
Epoch 10/200
80/80 [==============================] - 0s - loss: 0.6587 - acc: 0.7000     
Epoch 11/200
80/80 [==============================] - 0s - loss: 0.6540 - acc: 0.7000     
Epoch 12

80/80 [==============================] - 0s - loss: 0.3498 - acc: 0.8500     
Epoch 180/200
80/80 [==============================] - 0s - loss: 0.3501 - acc: 0.8500     
Epoch 181/200
80/80 [==============================] - 0s - loss: 0.3490 - acc: 0.8500     
Epoch 182/200
80/80 [==============================] - 0s - loss: 0.3496 - acc: 0.8500     
Epoch 183/200
80/80 [==============================] - 0s - loss: 0.3495 - acc: 0.8500     
Epoch 184/200
80/80 [==============================] - 0s - loss: 0.3481 - acc: 0.8500     
Epoch 185/200
80/80 [==============================] - 0s - loss: 0.3482 - acc: 0.8500     
Epoch 186/200
80/80 [==============================] - 0s - loss: 0.3479 - acc: 0.8500     
Epoch 187/200
80/80 [==============================] - 0s - loss: 0.3474 - acc: 0.8500     
Epoch 188/200
80/80 [==============================] - 0s - loss: 0.3472 - acc: 0.8500     
Epoch 189/200
80/80 [==============================] - 0s - loss: 0.3490 - acc: 0.8500     
Ep

In [15]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred, Y_test)

0.80000000000000004

In [17]:
confusion_matrix(Y_pred, Y_test)

array([[7, 3],
       [1, 9]], dtype=int64)