## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
df = pd.read_csv('ecoli.data', header = None, delimiter = r"\s+")
df.shape

(336, 9)

In [3]:
df.head()

0     1     2     3    4     5     6     7   8
0   AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35  cp
1  ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44  cp
2  ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46  cp
3  ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36  cp
4   ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35  cp

## Create X and Y

In [4]:
Y = df.iloc[:, 8].values
Y[0]

'cp'

In [5]:
X = df.iloc[:, 1:8].values
X[0]

array([ 0.49,  0.29,  0.48,  0.5 ,  0.56,  0.24,  0.35])

## Preprocess the Data

In [6]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [7]:
le_Y = LabelEncoder()

In [8]:
Y = le_Y.fit_transform(Y)
Y[0]

0

In [9]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])
Y = ohe_Y.fit_transform(Y).toarray()
Y[0]

array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
sc_X = StandardScaler()

In [11]:
X = sc_X.fit_transform(X)
X[0]

array([-0.0517614 , -1.41953086, -0.17514236, -0.05463584,  0.49078096,
       -1.20771743, -0.7160837 ])

## Create Train and Test Data

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 7))

# Output Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=7, kernel_initializer="uniform", activation="relu", units=8)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="softmax", units=8)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
268/268 [==============================] - 0s - loss: 2.0533 - acc: 0.4254     
Epoch 2/200
268/268 [==============================] - 0s - loss: 1.9438 - acc: 0.6045     
Epoch 3/200
268/268 [==============================] - 0s - loss: 1.7126 - acc: 0.6306     
Epoch 4/200
268/268 [==============================] - 0s - loss: 1.4360 - acc: 0.6194     
Epoch 5/200
268/268 [==============================] - 0s - loss: 1.2344 - acc: 0.6231     
Epoch 6/200
268/268 [==============================] - 0s - loss: 1.1121 - acc: 0.6269     
Epoch 7/200
268/268 [==============================] - 0s - loss: 1.0317 - acc: 0.6455     
Epoch 8/200
268/268 [==============================] - 0s - loss: 0.9718 - acc: 0.6642     
Epoch 9/200
268/268 [==============================] - 0s - loss: 0.9211 - acc: 0.6828     
Epoch 10/200
268/268 [==============================] - 0s - loss: 0.8739 - acc: 0.7015     
Epoch 11/200
268/268 [==============================] - 0s - loss: 0.8316 - acc

268/268 [==============================] - 0s - loss: 0.3821 - acc: 0.8694     
Epoch 90/200
268/268 [==============================] - 0s - loss: 0.3819 - acc: 0.8694     
Epoch 91/200
268/268 [==============================] - 0s - loss: 0.3803 - acc: 0.8694     
Epoch 92/200
268/268 [==============================] - 0s - loss: 0.3788 - acc: 0.8694     
Epoch 93/200
268/268 [==============================] - 0s - loss: 0.3791 - acc: 0.8694     
Epoch 94/200
268/268 [==============================] - 0s - loss: 0.3785 - acc: 0.8731     
Epoch 95/200
268/268 [==============================] - 0s - loss: 0.3784 - acc: 0.8731     
Epoch 96/200
268/268 [==============================] - 0s - loss: 0.3773 - acc: 0.8694     
Epoch 97/200
268/268 [==============================] - 0s - loss: 0.3754 - acc: 0.8769     
Epoch 98/200
268/268 [==============================] - 0s - loss: 0.3757 - acc: 0.8769     
Epoch 99/200
268/268 [==============================] - 0s - loss: 0.3737 - acc: 0.

268/268 [==============================] - 0s - loss: 0.3377 - acc: 0.8731     
Epoch 177/200
268/268 [==============================] - 0s - loss: 0.3377 - acc: 0.8806     
Epoch 178/200
268/268 [==============================] - 0s - loss: 0.3361 - acc: 0.8731     
Epoch 179/200
268/268 [==============================] - 0s - loss: 0.3365 - acc: 0.8769     
Epoch 180/200
268/268 [==============================] - 0s - loss: 0.3363 - acc: 0.8806     
Epoch 181/200
268/268 [==============================] - 0s - loss: 0.3358 - acc: 0.8731     
Epoch 182/200
268/268 [==============================] - 0s - loss: 0.3360 - acc: 0.8769     
Epoch 183/200
268/268 [==============================] - 0s - loss: 0.3346 - acc: 0.8806     
Epoch 184/200
268/268 [==============================] - 0s - loss: 0.3342 - acc: 0.8769     
Epoch 185/200
268/268 [==============================] - 0s - loss: 0.3349 - acc: 0.8806     
Epoch 186/200
268/268 [==============================] - 0s - loss: 0.3337

In [15]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [17]:
accuracy_score(Y_test_class, Y_pred_class)

0.91176470588235292

In [18]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[34,  0,  0,  0,  0],
       [ 0, 15,  2,  0,  1],
       [ 0,  2,  4,  0,  0],
       [ 0,  1,  0,  2,  0],
       [ 0,  0,  0,  0,  7]], dtype=int64)