## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df = pd.read_csv('ecoli.data', header = None, delimiter = r"\s+")
df.shape

(336, 9)

In [6]:
df.head()

0     1     2     3    4     5     6     7   8
0   AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35  cp
1  ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44  cp
2  ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46  cp
3  ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36  cp
4   ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35  cp

## Create X and Y

In [7]:
Y = df.iloc[:, 8].values
Y.shape

(336,)

In [8]:
Y

array(['cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'im', 'im', 'im', 'im', 'im', 'im', 'im', 'i

In [9]:
X = df.iloc[:, 1:8].values
X.shape

(336, 7)

In [10]:
X

array([[ 0.49,  0.29,  0.48, ...,  0.56,  0.24,  0.35],
       [ 0.07,  0.4 ,  0.48, ...,  0.54,  0.35,  0.44],
       [ 0.56,  0.4 ,  0.48, ...,  0.49,  0.37,  0.46],
       ..., 
       [ 0.61,  0.6 ,  0.48, ...,  0.44,  0.39,  0.38],
       [ 0.59,  0.61,  0.48, ...,  0.42,  0.42,  0.37],
       [ 0.74,  0.74,  0.48, ...,  0.31,  0.53,  0.52]])

## Preprocess the Data

In [11]:
le_Y = LabelEncoder()

In [12]:
Y = le_Y.fit_transform(Y)

In [13]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 2, 2, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7,

In [14]:
sc_X = StandardScaler()

In [15]:
X = sc_X.fit_transform(X)
X

array([[-0.0517614 , -1.41953086, -0.17514236, ...,  0.49078096,
        -1.20771743, -0.7160837 ],
       [-2.21287637, -0.67596708, -0.17514236, ...,  0.32710612,
        -0.69711074, -0.28566488],
       [ 0.30842443, -0.67596708, -0.17514236, ..., -0.08208098,
        -0.60427317, -0.19001625],
       ..., 
       [ 0.56570002,  0.67596708, -0.17514236, ..., -0.49126808,
        -0.51143559, -0.57261076],
       [ 0.46278978,  0.74356378, -0.17514236, ..., -0.65494292,
        -0.37217922, -0.62043507],
       [ 1.23461656,  1.62232098, -0.17514236, ..., -1.55515454,
         0.13842746,  0.09692964]])

## Create Train and Test data

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [17]:
X_train.shape

(268, 7)

In [18]:
X_test.shape

(68, 7)

In [19]:
Y_train.shape

(268,)

In [20]:
Y_test.shape

(68,)

In [21]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  109
1   59
7   45
4   29
5   17
6    5
3    2
2    2

In [22]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  34
1  18
7   7
4   6
5   3

## Decision Tree Classifier

In [23]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [24]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
Y_pred_dt = clf_dt.predict(X_test)

In [26]:
cm_dt = confusion_matrix(Y_pred_dt, Y_test)
cm_dt

array([[33,  0,  0,  0,  0,  1],
       [ 1, 15,  0,  3,  1,  1],
       [ 0,  1,  0,  0,  0,  0],
       [ 0,  2,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  5]], dtype=int64)

## Random Forest Classifier

In [27]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [28]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [29]:
Y_pred_rf = clf_rf.predict(X_test)

In [30]:
cm_rf = confusion_matrix(Y_pred_rf, Y_test)
cm_rf

array([[34,  1,  0,  0,  0],
       [ 0, 15,  5,  0,  0],
       [ 0,  2,  1,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  7]], dtype=int64)

## Naive Bayes Classifier

In [31]:
clf_nb = GaussianNB()

In [32]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [33]:
Y_pred_nb = clf_nb.predict(X_test)

In [34]:
cm_nb = confusion_matrix(Y_pred_nb, Y_test)
cm_nb

array([[34,  4,  0,  0,  0,  0,  0],
       [ 0,  7,  0,  2,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  2,  0,  0,  0],
       [ 0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0],
       [ 0,  2,  0,  2,  0,  0,  7]], dtype=int64)

## KNN Classifier

In [35]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [36]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [37]:
Y_pred_knn = clf_knn.predict(X_test)

In [38]:
cm_knn = confusion_matrix(Y_pred_knn, Y_test)
cm_knn

array([[34,  3,  0,  0,  0,  0],
       [ 0, 12,  3,  0,  0,  0],
       [ 0,  2,  3,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  1,  0,  0],
       [ 0,  1,  0,  0,  0,  7]], dtype=int64)

## Logistic Regression

In [39]:
clf_lr = LogisticRegression()

In [40]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [41]:
Y_pred_lr = clf_lr.predict(X_test)

In [42]:
cm_lr = confusion_matrix(Y_pred_lr, Y_test)
cm_lr

array([[34,  0,  0,  0,  0,  0],
       [ 0, 16,  1,  0,  0,  0],
       [ 0,  2,  5,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  7]], dtype=int64)

## SVC Linear

In [43]:
clf_lsvc = SVC(kernel = "linear")

In [44]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [45]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [46]:
cm_lsvc = confusion_matrix(Y_pred_lsvc, Y_test)
cm_lsvc

array([[34,  0,  0,  0,  0,  0],
       [ 0, 16,  2,  0,  0,  0],
       [ 0,  2,  4,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  7]], dtype=int64)

## SVC Kernel

In [47]:
clf_ksvc = SVC(kernel = "rbf")

In [48]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [49]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [50]:
cm_ksvc = confusion_matrix(Y_pred_ksvc, Y_test)
cm_ksvc

array([[34,  1,  0,  0,  0],
       [ 0, 14,  2,  1,  0],
       [ 0,  2,  4,  0,  0],
       [ 0,  0,  0,  2,  0],
       [ 0,  1,  0,  0,  7]], dtype=int64)

## Accuracy of Various Classifiers

In [51]:
model_accuracies['DT'] = accuracy_score(Y_pred_dt, Y_test)
model_accuracies['KNN'] = accuracy_score(Y_pred_knn, Y_test)
model_accuracies['KernelSVC'] = accuracy_score(Y_pred_ksvc, Y_test)
model_accuracies['LinearSVC'] = accuracy_score(Y_pred_lsvc, Y_test)
model_accuracies['LogReg'] = accuracy_score(Y_pred_lr, Y_test)
model_accuracies['NB'] = accuracy_score(Y_pred_nb, Y_test)
model_accuracies['RF'] = accuracy_score(Y_pred_rf, Y_test)
model_accuracies

{'DT': 0.8529411764705882,
 'KNN': 0.8529411764705882,
 'KernelSVC': 0.8970588235294118,
 'LinearSVC': 0.92647058823529416,
 'LogReg': 0.94117647058823528,
 'NB': 0.76470588235294112,
 'RF': 0.88235294117647056}