## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
df = pd.read_csv('ecoli.data', header = None, delimiter = r"\s+")
df.shape

(336, 9)

In [3]:
df.head()

0     1     2     3    4     5     6     7   8
0   AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35  cp
1  ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44  cp
2  ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46  cp
3  ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36  cp
4   ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35  cp

## Create X and Y

In [4]:
Y = df.iloc[:, 8].values
Y

array(['cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'im', 'im', 'im', 'im', 'im', 'im', 'im', 'i

In [5]:
X = df.iloc[:, 1:8].values
X

array([[ 0.49,  0.29,  0.48, ...,  0.56,  0.24,  0.35],
       [ 0.07,  0.4 ,  0.48, ...,  0.54,  0.35,  0.44],
       [ 0.56,  0.4 ,  0.48, ...,  0.49,  0.37,  0.46],
       ..., 
       [ 0.61,  0.6 ,  0.48, ...,  0.44,  0.39,  0.38],
       [ 0.59,  0.61,  0.48, ...,  0.42,  0.42,  0.37],
       [ 0.74,  0.74,  0.48, ...,  0.31,  0.53,  0.52]])

## Preprocess the Data

In [6]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [7]:
le_Y = LabelEncoder()

In [8]:
Y = le_Y.fit_transform(Y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 2, 2, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7,

In [9]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])
Y = ohe_Y.fit_transform(Y).toarray()
Y

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [10]:
sc_X = StandardScaler()

In [11]:
X = sc_X.fit_transform(X)
X

array([[-0.0517614 , -1.41953086, -0.17514236, ...,  0.49078096,
        -1.20771743, -0.7160837 ],
       [-2.21287637, -0.67596708, -0.17514236, ...,  0.32710612,
        -0.69711074, -0.28566488],
       [ 0.30842443, -0.67596708, -0.17514236, ..., -0.08208098,
        -0.60427317, -0.19001625],
       ..., 
       [ 0.56570002,  0.67596708, -0.17514236, ..., -0.49126808,
        -0.51143559, -0.57261076],
       [ 0.46278978,  0.74356378, -0.17514236, ..., -0.65494292,
        -0.37217922, -0.62043507],
       [ 1.23461656,  1.62232098, -0.17514236, ..., -1.55515454,
         0.13842746,  0.09692964]])

## Create Train and Test Data

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 7))

# Output Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=7, kernel_initializer="uniform", units=8)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", kernel_initializer="uniform", units=8)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
268/268 [==============================] - 0s - loss: 2.0533 - acc: 0.4104         
Epoch 2/200
268/268 [==============================] - 0s - loss: 1.9444 - acc: 0.5299     
Epoch 3/200
268/268 [==============================] - 0s - loss: 1.7314 - acc: 0.6007     
Epoch 4/200
268/268 [==============================] - 0s - loss: 1.4694 - acc: 0.6045     
Epoch 5/200
268/268 [==============================] - 0s - loss: 1.2544 - acc: 0.6082     
Epoch 6/200
268/268 [==============================] - 0s - loss: 1.1081 - acc: 0.6194     
Epoch 7/200
268/268 [==============================] - 0s - loss: 1.0075 - acc: 0.6493     
Epoch 8/200
268/268 [==============================] - 0s - loss: 0.9357 - acc: 0.6754     
Epoch 9/200
268/268 [==============================] - 0s - loss: 0.8822 - acc: 0.7015     
Epoch 10/200
268/268 [==============================] - 0s - loss: 0.8349 - acc: 0.7276     
Epoch 11/200
268/268 [==============================] - 0s - loss: 0.7981 -

268/268 [==============================] - 0s - loss: 0.3698 - acc: 0.8657     
Epoch 90/200
268/268 [==============================] - 0s - loss: 0.3688 - acc: 0.8657     
Epoch 91/200
268/268 [==============================] - 0s - loss: 0.3674 - acc: 0.8657     
Epoch 92/200
268/268 [==============================] - 0s - loss: 0.3669 - acc: 0.8657     
Epoch 93/200
268/268 [==============================] - 0s - loss: 0.3658 - acc: 0.8657     
Epoch 94/200
268/268 [==============================] - 0s - loss: 0.3667 - acc: 0.8657     
Epoch 95/200
268/268 [==============================] - 0s - loss: 0.3649 - acc: 0.8657     
Epoch 96/200
268/268 [==============================] - 0s - loss: 0.3657 - acc: 0.8619     
Epoch 97/200
268/268 [==============================] - 0s - loss: 0.3635 - acc: 0.8657     
Epoch 98/200
268/268 [==============================] - 0s - loss: 0.3630 - acc: 0.8657     
Epoch 99/200
268/268 [==============================] - 0s - loss: 0.3615 - acc: 0.

268/268 [==============================] - 0s - loss: 0.3229 - acc: 0.8918     
Epoch 177/200
268/268 [==============================] - 0s - loss: 0.3217 - acc: 0.8918     
Epoch 178/200
268/268 [==============================] - 0s - loss: 0.3222 - acc: 0.8918     
Epoch 179/200
268/268 [==============================] - 0s - loss: 0.3209 - acc: 0.8918     
Epoch 180/200
268/268 [==============================] - 0s - loss: 0.3201 - acc: 0.8918     
Epoch 181/200
268/268 [==============================] - 0s - loss: 0.3199 - acc: 0.8918     
Epoch 182/200
268/268 [==============================] - 0s - loss: 0.3182 - acc: 0.8918     
Epoch 183/200
268/268 [==============================] - 0s - loss: 0.3186 - acc: 0.8918     
Epoch 184/200
268/268 [==============================] - 0s - loss: 0.3183 - acc: 0.8918     
Epoch 185/200
268/268 [==============================] - 0s - loss: 0.3181 - acc: 0.8955     
Epoch 186/200
268/268 [==============================] - 0s - loss: 0.3183

In [17]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [19]:
accuracy_score(Y_pred_class, Y_test_class)

0.91176470588235292

In [20]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[34,  0,  0,  0,  0],
       [ 0, 15,  2,  0,  0],
       [ 0,  2,  4,  1,  0],
       [ 0,  0,  0,  2,  0],
       [ 0,  1,  0,  0,  7]], dtype=int64)