## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
df = pd.read_csv('ecoli.data', header = None, delimiter = r"\s+")
df.shape

(336, 9)

In [3]:
df.head()

0     1     2     3    4     5     6     7   8
0   AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35  cp
1  ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44  cp
2  ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46  cp
3  ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36  cp
4   ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35  cp

## Create X and Y

In [4]:
Y = df.iloc[:, 8].values
Y

array(['cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp', 'cp',
       'im', 'im', 'im', 'im', 'im', 'im', 'im', 'i

In [5]:
X = df.iloc[:, 1:8].values
X

array([[ 0.49,  0.29,  0.48, ...,  0.56,  0.24,  0.35],
       [ 0.07,  0.4 ,  0.48, ...,  0.54,  0.35,  0.44],
       [ 0.56,  0.4 ,  0.48, ...,  0.49,  0.37,  0.46],
       ..., 
       [ 0.61,  0.6 ,  0.48, ...,  0.44,  0.39,  0.38],
       [ 0.59,  0.61,  0.48, ...,  0.42,  0.42,  0.37],
       [ 0.74,  0.74,  0.48, ...,  0.31,  0.53,  0.52]])

## Preprocess the Data

In [6]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [7]:
le_Y = LabelEncoder()

In [8]:
Y = le_Y.fit_transform(Y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 2, 2, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7,

In [9]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])
Y = ohe_Y.fit_transform(Y).toarray()
Y

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [10]:
sc_X = StandardScaler()

In [11]:
X = sc_X.fit_transform(X)
X

array([[-0.0517614 , -1.41953086, -0.17514236, ...,  0.49078096,
        -1.20771743, -0.7160837 ],
       [-2.21287637, -0.67596708, -0.17514236, ...,  0.32710612,
        -0.69711074, -0.28566488],
       [ 0.30842443, -0.67596708, -0.17514236, ..., -0.08208098,
        -0.60427317, -0.19001625],
       ..., 
       [ 0.56570002,  0.67596708, -0.17514236, ..., -0.49126808,
        -0.51143559, -0.57261076],
       [ 0.46278978,  0.74356378, -0.17514236, ..., -0.65494292,
        -0.37217922, -0.62043507],
       [ 1.23461656,  1.62232098, -0.17514236, ..., -1.55515454,
         0.13842746,  0.09692964]])

## Create Train and Test Data

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [13]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0.0  159
1.0  109

In [14]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
1.0  34
0.0  34

## Create and Train the Classifier

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 7))

# Output Layer
clf_ann.add(Dense(output_dim = 8, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=7, units=8, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=8, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
268/268 [==============================] - 0s - loss: 2.0494 - acc: 0.5597     
Epoch 2/200
268/268 [==============================] - 0s - loss: 1.9240 - acc: 0.6045     
Epoch 3/200
268/268 [==============================] - 0s - loss: 1.6773 - acc: 0.6306     
Epoch 4/200
268/268 [==============================] - 0s - loss: 1.3904 - acc: 0.6493     
Epoch 5/200
268/268 [==============================] - 0s - loss: 1.1691 - acc: 0.6903     
Epoch 6/200
268/268 [==============================] - 0s - loss: 1.0250 - acc: 0.7015     
Epoch 7/200
268/268 [==============================] - 0s - loss: 0.9293 - acc: 0.7313     
Epoch 8/200
268/268 [==============================] - 0s - loss: 0.8603 - acc: 0.7351     
Epoch 9/200
268/268 [==============================] - 0s - loss: 0.8091 - acc: 0.7388     
Epoch 10/200
268/268 [==============================] - 0s - loss: 0.7676 - acc: 0.7425     
Epoch 11/200
268/268 [==============================] - 0s - loss: 0.7369 - acc

268/268 [==============================] - 0s - loss: 0.3871 - acc: 0.8806     
Epoch 90/200
268/268 [==============================] - 0s - loss: 0.3861 - acc: 0.8694     
Epoch 91/200
268/268 [==============================] - 0s - loss: 0.3855 - acc: 0.8769     
Epoch 92/200
268/268 [==============================] - 0s - loss: 0.3840 - acc: 0.8806     
Epoch 93/200
268/268 [==============================] - 0s - loss: 0.3836 - acc: 0.8769     
Epoch 94/200
268/268 [==============================] - 0s - loss: 0.3832 - acc: 0.8806     
Epoch 95/200
268/268 [==============================] - 0s - loss: 0.3830 - acc: 0.8694     
Epoch 96/200
268/268 [==============================] - 0s - loss: 0.3817 - acc: 0.8806     
Epoch 97/200
268/268 [==============================] - 0s - loss: 0.3813 - acc: 0.8769     
Epoch 98/200
268/268 [==============================] - 0s - loss: 0.3806 - acc: 0.8731     
Epoch 99/200
268/268 [==============================] - 0s - loss: 0.3794 - acc: 0.

268/268 [==============================] - 0s - loss: 0.3473 - acc: 0.8806     
Epoch 177/200
268/268 [==============================] - 0s - loss: 0.3487 - acc: 0.8769     
Epoch 178/200
268/268 [==============================] - 0s - loss: 0.3459 - acc: 0.8806     
Epoch 179/200
268/268 [==============================] - 0s - loss: 0.3462 - acc: 0.8806     
Epoch 180/200
268/268 [==============================] - 0s - loss: 0.3456 - acc: 0.8806     
Epoch 181/200
268/268 [==============================] - 0s - loss: 0.3451 - acc: 0.8806     
Epoch 182/200
268/268 [==============================] - 0s - loss: 0.3458 - acc: 0.8806     
Epoch 183/200
268/268 [==============================] - 0s - loss: 0.3451 - acc: 0.8881     
Epoch 184/200
268/268 [==============================] - 0s - loss: 0.3445 - acc: 0.8769     
Epoch 185/200
268/268 [==============================] - ETA: 0s - loss: 0.3596 - acc: 0.800 - 0s - loss: 0.3449 - acc: 0.8881     
Epoch 186/200
268/268 [=============

In [21]:
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy_score(Y_pred, Y_test)

0.92647058823529416