## Initialization

In [1]:
import numpy as np
import pandas as pd
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("yeast.data", header = None, delimiter = r"\s+")

In [3]:
dataset.shape

(1484, 10)

In [4]:
dataset.head()

0     1     2     3     4    5    6     7     8    9
0  ADT1_YEAST  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22  MIT
1  ADT2_YEAST  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22  MIT
2  ADT3_YEAST  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22  MIT
3  AAR2_YEAST  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22  NUC
4  AATM_YEAST  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22  MIT

## Create X and Y

In [5]:
X = dataset.iloc[:, 1:9].values
Y = dataset.iloc[:, 9].values

In [6]:
X

array([[ 0.58,  0.61,  0.47, ...,  0.  ,  0.48,  0.22],
       [ 0.43,  0.67,  0.48, ...,  0.  ,  0.53,  0.22],
       [ 0.64,  0.62,  0.49, ...,  0.  ,  0.53,  0.22],
       ..., 
       [ 0.67,  0.57,  0.36, ...,  0.  ,  0.56,  0.22],
       [ 0.43,  0.4 ,  0.6 , ...,  0.  ,  0.53,  0.39],
       [ 0.65,  0.54,  0.54, ...,  0.  ,  0.53,  0.22]])

In [7]:
Y

array(['MIT', 'MIT', 'MIT', ..., 'ME2', 'NUC', 'CYT'], dtype=object)

## Preprocess the Data

In [8]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)
ohe = OneHotEncoder(categorical_features=[0])
Y = ohe.fit_transform(Y).toarray()
Y

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.]])

In [9]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
X

array([[ 0.58198136,  0.88848148, -0.3466451 , ..., -0.0991314 ,
        -0.34417514, -0.5279193 ],
       [-0.51089067,  1.37281104, -0.23122636, ..., -0.0991314 ,
         0.52121948, -0.5279193 ],
       [ 1.01913017,  0.96920307, -0.11580762, ..., -0.0991314 ,
         0.52121948, -0.5279193 ],
       ..., 
       [ 1.23770457,  0.5655951 , -1.61625127, ..., -0.0991314 ,
         1.04045625, -0.5279193 ],
       [-0.51089067, -0.80667199,  1.15379854, ..., -0.0991314 ,
         0.52121948,  1.06900494],
       [ 1.0919883 ,  0.32343032,  0.46128609, ..., -0.0991314 ,
         0.52121948, -0.5279193 ]])

## Create Train and Test Data

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [12]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 24, init = 'uniform', activation = 'relu', input_dim = 8))

# Output Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=24, kernel_initializer="uniform", activation="relu", input_dim=8)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=10, kernel_initializer="uniform", activation="softmax")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
1187/1187 [==============================] - 0s - loss: 2.1185 - acc: 0.3926        
Epoch 2/100
1187/1187 [==============================] - 0s - loss: 1.5381 - acc: 0.4684     
Epoch 3/100
1187/1187 [==============================] - 0s - loss: 1.2893 - acc: 0.5476     
Epoch 4/100
1187/1187 [==============================] - 0s - loss: 1.1954 - acc: 0.5611     
Epoch 5/100
1187/1187 [==============================] - 0s - loss: 1.1513 - acc: 0.5661     
Epoch 6/100
1187/1187 [==============================] - 0s - loss: 1.1238 - acc: 0.5796     
Epoch 7/100
1187/1187 [==============================] - 0s - loss: 1.1053 - acc: 0.5889     
Epoch 8/100
1187/1187 [==============================] - 0s - loss: 1.0879 - acc: 0.5956     
Epoch 9/100
1187/1187 [==============================] - 0s - loss: 1.0749 - acc: 0.5981     
Epoch 10/100
1187/1187 [==============================] - 0s - loss: 1.0652 - acc: 0.6015     
Epoch 11/100
1187/1187 [==============================] 

1187/1187 [==============================] - 0s - loss: 0.9232 - acc: 0.6453     
Epoch 87/100
1187/1187 [==============================] - 0s - loss: 0.9234 - acc: 0.6495     
Epoch 88/100
1187/1187 [==============================] - 0s - loss: 0.9232 - acc: 0.6462     
Epoch 89/100
1187/1187 [==============================] - 0s - loss: 0.9224 - acc: 0.6411     
Epoch 90/100
1187/1187 [==============================] - 0s - loss: 0.9230 - acc: 0.6495     
Epoch 91/100
1187/1187 [==============================] - 0s - loss: 0.9216 - acc: 0.6512     
Epoch 92/100
1187/1187 [==============================] - 0s - loss: 0.9199 - acc: 0.6470     
Epoch 93/100
1187/1187 [==============================] - 0s - loss: 0.9204 - acc: 0.6512     
Epoch 94/100
1187/1187 [==============================] - 0s - loss: 0.9201 - acc: 0.6462     
Epoch 95/100
1187/1187 [==============================] - 0s - loss: 0.9179 - acc: 0.6487     
Epoch 96/100
1187/1187 [==============================] - 0s - 

In [13]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred_class, Y_test_class)

0.54545454545454541

In [15]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[55,  0,  1,  0,  0,  2,  8, 33,  3,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  2, 13,  5,  0,  1,  0,  0,  0],
       [ 1,  0,  2,  2,  2,  0,  1,  1,  0,  0],
       [ 1,  0,  0,  0,  2, 28,  3,  5,  0,  3],
       [ 8,  0,  0,  0,  1,  0, 21,  6,  2,  0],
       [25,  0,  0,  0,  1,  6,  5, 34,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int64)