## Initialization

In [1]:
import numpy as np
import pandas as pd
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("yeast.data", header = None, delimiter = r"\s+")

In [3]:
dataset.shape

(1484, 10)

In [4]:
dataset.head()

0     1     2     3     4    5    6     7     8    9
0  ADT1_YEAST  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22  MIT
1  ADT2_YEAST  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22  MIT
2  ADT3_YEAST  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22  MIT
3  AAR2_YEAST  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22  NUC
4  AATM_YEAST  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22  MIT

## Create X and Y

In [5]:
X = dataset.iloc[:, 1:9].values
Y = dataset.iloc[:, 9].values

In [6]:
X[0]

array([ 0.58,  0.61,  0.47,  0.13,  0.5 ,  0.  ,  0.48,  0.22])

In [7]:
Y[0]

'MIT'

## Preprocess the Data

In [8]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)
ohe = OneHotEncoder(categorical_features=[0])
Y = ohe.fit_transform(Y).toarray()
Y[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.])

In [9]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
X[0]

array([ 0.58198136,  0.88848148, -0.3466451 , -0.95720258, -0.09759001,
       -0.0991314 , -0.34417514, -0.5279193 ])

## Create Train and Test Data

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [12]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 24, init = 'uniform', activation = 'relu', input_dim = 8))

# Output Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", input_dim=8, units=24)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", kernel_initializer="uniform", units=10)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
1187/1187 [==============================] - 0s - loss: 2.0966 - acc: 0.4229     
Epoch 2/100
1187/1187 [==============================] - 0s - loss: 1.5458 - acc: 0.4356     
Epoch 3/100
1187/1187 [==============================] - 0s - loss: 1.3075 - acc: 0.5392     
Epoch 4/100
1187/1187 [==============================] - 0s - loss: 1.2056 - acc: 0.5628     
Epoch 5/100
1187/1187 [==============================] - 0s - loss: 1.1616 - acc: 0.5729     
Epoch 6/100
1187/1187 [==============================] - 0s - loss: 1.1346 - acc: 0.5670     
Epoch 7/100
1187/1187 [==============================] - 0s - loss: 1.1177 - acc: 0.5746     
Epoch 8/100
1187/1187 [==============================] - 0s - loss: 1.1022 - acc: 0.5855     
Epoch 9/100
1187/1187 [==============================] - 0s - loss: 1.0873 - acc: 0.5948     
Epoch 10/100
1187/1187 [==============================] - 0s - loss: 1.0761 - acc: 0.5864     
Epoch 11/100
1187/1187 [==============================] - 0

1187/1187 [==============================] - 0s - loss: 0.9278 - acc: 0.6352     
Epoch 87/100
1187/1187 [==============================] - 0s - loss: 0.9261 - acc: 0.6386     
Epoch 88/100
1187/1187 [==============================] - 0s - loss: 0.9269 - acc: 0.6487     
Epoch 89/100
1187/1187 [==============================] - 0s - loss: 0.9262 - acc: 0.6377     
Epoch 90/100
1187/1187 [==============================] - 0s - loss: 0.9260 - acc: 0.6369     
Epoch 91/100
1187/1187 [==============================] - 0s - loss: 0.9239 - acc: 0.6411     
Epoch 92/100
1187/1187 [==============================] - 0s - loss: 0.9231 - acc: 0.6352     
Epoch 93/100
1187/1187 [==============================] - 0s - loss: 0.9236 - acc: 0.6420     
Epoch 94/100
1187/1187 [==============================] - 0s - loss: 0.9218 - acc: 0.6403     
Epoch 95/100
1187/1187 [==============================] - 0s - loss: 0.9221 - acc: 0.6344     
Epoch 96/100
1187/1187 [==============================] - 0s - 

In [13]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test_class, Y_pred_class)

0.57239057239057234

In [15]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[58,  0,  0,  0,  1,  0,  7, 25,  1,  1],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  6,  2,  2,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 14,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  5,  1,  2,  2,  1,  0,  0],
       [ 3,  0,  0,  0,  0, 27,  0,  6,  0,  0],
       [10,  0,  0,  1,  1,  3, 19,  5,  0,  0],
       [27,  1,  0,  0,  1,  4,  5, 41,  0,  0],
       [ 3,  0,  0,  0,  0,  0,  1,  0,  3,  0],
       [ 0,  0,  0,  0,  0,  3,  0,  1,  0,  0]], dtype=int64)