## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
df = pd.read_excel('BreastTissue.xls', sheetname = 1)
df.shape

(106, 11)

In [3]:
df.head()

Case # Class          I0     PA500       HFS          DA          Area  \
0       1   car  524.794072  0.187448  0.032114  228.800228   6843.598481   
1       2   car  330.000000  0.226893  0.265290  121.154201   3163.239472   
2       3   car  551.879287  0.232478  0.063530  264.804935  11888.391827   
3       4   car  380.000000  0.240855  0.286234  137.640111   5402.171180   
4       5   car  362.831266  0.200713  0.244346  124.912559   3290.462446   

        A/DA     Max IP          DR           P  
0  29.910803  60.204880  220.737212  556.828334  
1  26.109202  69.717361   99.084964  400.225776  
2  44.894903  77.793297  253.785300  656.769449  
3  39.248524  88.758446  105.198568  493.701814  
4  26.342127  69.389389  103.866552  424.796503

## Create X and Y

In [4]:
X = df.iloc[:, 2:].values
Y = df.iloc[:, 1].values

## Preprocess the Data

In [5]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [6]:
X

array([[ -3.45765773e-01,   9.85995757e-01,  -8.18663989e-01,
          2.01325569e-01,  -2.65814600e-02,   2.76929535e-01,
         -1.87452440e-01,   2.99395634e-01,  -3.34219072e-01],
       [ -6.05357848e-01,   1.56375157e+00,   1.49303791e+00,
         -3.65532879e-01,  -2.25600861e-01,   1.13379349e-01,
         -6.99581450e-02,  -3.74756121e-01,  -5.40434762e-01],
       [ -3.09670694e-01,   1.64555771e+00,  -5.07207146e-01,
          3.90924509e-01,   2.46221206e-01,   9.21566460e-01,
          2.97925154e-02,   4.82535910e-01,  -2.02615691e-01],
       [ -5.38725411e-01,   1.76826691e+00,   1.70067581e+00,
         -2.78718923e-01,  -1.04528203e-01,   6.78651350e-01,
          1.65229563e-01,  -3.40876789e-01,  -4.17344655e-01],
       [ -5.61605302e-01,   1.18028532e+00,   1.28540002e+00,
         -3.45741555e-01,  -2.18721141e-01,   1.23400098e-01,
         -7.40091265e-02,  -3.48258330e-01,  -5.08079802e-01],
       [ -5.25568199e-01,   4.38917241e-01,  -1.68065250e-01,
   

In [7]:
le_Y = LabelEncoder()

In [8]:
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)
Y.shape

(106, 1)

In [9]:
ohey = OneHotEncoder(categorical_features = [0])

In [10]:
Y = ohey.fit_transform(Y).toarray()
Y

array([[ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1

## Create Train and Test Data

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 30, init = 'uniform', activation = 'relu', input_dim = 9))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 60, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 6, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=9, kernel_initializer="uniform", activation="relu", units=30)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", units=60)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", kernel_initializer="uniform", units=6)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
84/84 [==============================] - 0s - loss: 1.7872 - acc: 0.2619         
Epoch 2/200
84/84 [==============================] - 0s - loss: 1.7604 - acc: 0.4048     
Epoch 3/200
84/84 [==============================] - 0s - loss: 1.6841 - acc: 0.4524     
Epoch 4/200
84/84 [==============================] - 0s - loss: 1.5119 - acc: 0.4524     
Epoch 5/200
84/84 [==============================] - 0s - loss: 1.3467 - acc: 0.4524     
Epoch 6/200
84/84 [==============================] - 0s - loss: 1.2503 - acc: 0.4048     
Epoch 7/200
84/84 [==============================] - 0s - loss: 1.1812 - acc: 0.4048         
Epoch 8/200
84/84 [==============================] - 0s - loss: 1.1305 - acc: 0.5119     
Epoch 9/200
84/84 [==============================] - 0s - loss: 1.0758 - acc: 0.5357     
Epoch 10/200
84/84 [==============================] - 0s - loss: 1.0252 - acc: 0.5952     
Epoch 11/200
84/84 [==============================] - 0s - loss: 0.9857 - acc: 0.5952     


84/84 [==============================] - 0s - loss: 0.5274 - acc: 0.7857     
Epoch 91/200
84/84 [==============================] - 0s - loss: 0.5193 - acc: 0.7976     
Epoch 92/200
84/84 [==============================] - 0s - loss: 0.5230 - acc: 0.7857     
Epoch 93/200
84/84 [==============================] - 0s - loss: 0.5194 - acc: 0.7857     
Epoch 94/200
84/84 [==============================] - 0s - loss: 0.5172 - acc: 0.7976     
Epoch 95/200
84/84 [==============================] - 0s - loss: 0.5152 - acc: 0.7738     
Epoch 96/200
84/84 [==============================] - 0s - loss: 0.5173 - acc: 0.7738     
Epoch 97/200
84/84 [==============================] - 0s - loss: 0.5075 - acc: 0.7857     
Epoch 98/200
84/84 [==============================] - 0s - loss: 0.5077 - acc: 0.7976     
Epoch 99/200
84/84 [==============================] - 0s - loss: 0.5066 - acc: 0.7857     
Epoch 100/200
84/84 [==============================] - 0s - loss: 0.5063 - acc: 0.7857     
Epoch 101/2

84/84 [==============================] - 0s - loss: 0.3421 - acc: 0.8810     
Epoch 180/200
84/84 [==============================] - 0s - loss: 0.3480 - acc: 0.8810     
Epoch 181/200
84/84 [==============================] - 0s - loss: 0.3420 - acc: 0.8690     
Epoch 182/200
84/84 [==============================] - 0s - loss: 0.3325 - acc: 0.8810     
Epoch 183/200
84/84 [==============================] - 0s - loss: 0.3337 - acc: 0.8810     
Epoch 184/200
84/84 [==============================] - 0s - loss: 0.3299 - acc: 0.8690     
Epoch 185/200
84/84 [==============================] - 0s - loss: 0.3363 - acc: 0.8810     
Epoch 186/200
84/84 [==============================] - 0s - loss: 0.3354 - acc: 0.8810     
Epoch 187/200
84/84 [==============================] - 0s - loss: 0.3272 - acc: 0.8810     
Epoch 188/200
84/84 [==============================] - 0s - loss: 0.3291 - acc: 0.8452     
Epoch 189/200
84/84 [==============================] - 0s - loss: 0.3238 - acc: 0.8810     
Ep

In [15]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred_class, Y_test_class)

0.77272727272727271

In [17]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[3, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 1, 1, 3],
       [0, 1, 0, 0, 0, 2]], dtype=int64)