## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
df = pd.read_excel('BreastTissue.xls', sheetname = 1)
df.shape

(106, 11)

In [3]:
df.head()

Case # Class          I0     PA500       HFS          DA          Area  \
0       1   car  524.794072  0.187448  0.032114  228.800228   6843.598481   
1       2   car  330.000000  0.226893  0.265290  121.154201   3163.239472   
2       3   car  551.879287  0.232478  0.063530  264.804935  11888.391827   
3       4   car  380.000000  0.240855  0.286234  137.640111   5402.171180   
4       5   car  362.831266  0.200713  0.244346  124.912559   3290.462446   

        A/DA     Max IP          DR           P  
0  29.910803  60.204880  220.737212  556.828334  
1  26.109202  69.717361   99.084964  400.225776  
2  44.894903  77.793297  253.785300  656.769449  
3  39.248524  88.758446  105.198568  493.701814  
4  26.342127  69.389389  103.866552  424.796503

## Create X and Y

In [4]:
X = df.iloc[:, 2:].values
Y = df.iloc[:, 1].values

## Preprocess the Data

In [5]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [6]:
X[0]

array([-0.34576577,  0.98599576, -0.81866399,  0.20132557, -0.02658146,
        0.27692953, -0.18745244,  0.29939563, -0.33421907])

In [7]:
le_Y = LabelEncoder()

In [8]:
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)
Y.shape

(106, 1)

In [9]:
ohey = OneHotEncoder(categorical_features = [0])

In [10]:
Y = ohey.fit_transform(Y).toarray()
Y[0]

array([ 0.,  1.,  0.,  0.,  0.,  0.])

## Create Train and Test Data

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

## Create and Train the Classifier

In [12]:
from keras.models import Sequential
from keras.layers import Dense

In [13]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 30, init = 'uniform', activation = 'relu', input_dim = 9))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 60, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 6, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=9, activation="relu", kernel_initializer="uniform", units=30)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=60)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="softmax", units=6)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
84/84 [==============================] - 0s - loss: 1.7876 - acc: 0.4048     
Epoch 2/200
84/84 [==============================] - 0s - loss: 1.7684 - acc: 0.4881     
Epoch 3/200
84/84 [==============================] - 0s - loss: 1.6961 - acc: 0.4643     
Epoch 4/200
84/84 [==============================] - 0s - loss: 1.5276 - acc: 0.5238     
Epoch 5/200
84/84 [==============================] - 0s - loss: 1.3578 - acc: 0.4762     
Epoch 6/200
84/84 [==============================] - 0s - loss: 1.2444 - acc: 0.4524     
Epoch 7/200
84/84 [==============================] - 0s - loss: 1.1776 - acc: 0.4643         
Epoch 8/200
84/84 [==============================] - 0s - loss: 1.1289 - acc: 0.4881     
Epoch 9/200
84/84 [==============================] - 0s - loss: 1.0804 - acc: 0.5119     
Epoch 10/200
84/84 [==============================] - 0s - loss: 1.0421 - acc: 0.5833     
Epoch 11/200
84/84 [==============================] - 0s - loss: 0.9739 - acc: 0.5952     
Epoc

84/84 [==============================] - 0s - loss: 0.5167 - acc: 0.7857     
Epoch 92/200
84/84 [==============================] - 0s - loss: 0.5128 - acc: 0.7738     
Epoch 93/200
84/84 [==============================] - 0s - loss: 0.5144 - acc: 0.7857     
Epoch 94/200
84/84 [==============================] - 0s - loss: 0.5086 - acc: 0.7857     
Epoch 95/200
84/84 [==============================] - 0s - loss: 0.5196 - acc: 0.7857     
Epoch 96/200
84/84 [==============================] - 0s - loss: 0.5154 - acc: 0.7500     
Epoch 97/200
84/84 [==============================] - 0s - loss: 0.5057 - acc: 0.7857     
Epoch 98/200
84/84 [==============================] - 0s - loss: 0.5037 - acc: 0.7738     
Epoch 99/200
84/84 [==============================] - 0s - loss: 0.5017 - acc: 0.7738     
Epoch 100/200
84/84 [==============================] - 0s - loss: 0.4999 - acc: 0.7857     
Epoch 101/200
84/84 [==============================] - 0s - loss: 0.5013 - acc: 0.7738     
Epoch 102/

84/84 [==============================] - 0s - loss: 0.3946 - acc: 0.8690     
Epoch 181/200
84/84 [==============================] - 0s - loss: 0.4028 - acc: 0.8690     
Epoch 182/200
84/84 [==============================] - 0s - loss: 0.3917 - acc: 0.8452     
Epoch 183/200
84/84 [==============================] - 0s - loss: 0.3945 - acc: 0.8571     
Epoch 184/200
84/84 [==============================] - 0s - loss: 0.3954 - acc: 0.8452     
Epoch 185/200
84/84 [==============================] - 0s - loss: 0.3836 - acc: 0.8571     
Epoch 186/200
84/84 [==============================] - 0s - loss: 0.3838 - acc: 0.8452     
Epoch 187/200
84/84 [==============================] - 0s - loss: 0.3756 - acc: 0.8452     
Epoch 188/200
84/84 [==============================] - 0s - loss: 0.3811 - acc: 0.8452     
Epoch 189/200
84/84 [==============================] - 0s - loss: 0.3865 - acc: 0.8333     
Epoch 190/200
84/84 [==============================] - 0s - loss: 0.3797 - acc: 0.8690     
Ep

In [14]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test_class, Y_pred_class)

0.72727272727272729

In [16]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[2, 0, 1, 0, 0, 0],
       [0, 6, 0, 0, 0, 1],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 2, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 3, 2]], dtype=int64)