## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df = pd.read_excel('BreastTissue.xls', sheetname = 1)
df.shape

(106, 11)

In [6]:
df.head()

Case # Class          I0     PA500       HFS          DA          Area  \
0       1   car  524.794072  0.187448  0.032114  228.800228   6843.598481   
1       2   car  330.000000  0.226893  0.265290  121.154201   3163.239472   
2       3   car  551.879287  0.232478  0.063530  264.804935  11888.391827   
3       4   car  380.000000  0.240855  0.286234  137.640111   5402.171180   
4       5   car  362.831266  0.200713  0.244346  124.912559   3290.462446   

        A/DA     Max IP          DR           P  
0  29.910803  60.204880  220.737212  556.828334  
1  26.109202  69.717361   99.084964  400.225776  
2  44.894903  77.793297  253.785300  656.769449  
3  39.248524  88.758446  105.198568  493.701814  
4  26.342127  69.389389  103.866552  424.796503

## Create X and Y

In [7]:
Y = df.iloc[:, 1].values
Y.shape

(106,)

In [8]:
Y[0]

'car'

In [9]:
X = df.iloc[:, 2:].values
X.shape

(106, 9)

In [10]:
X[0]

array([  5.24794072e+02,   1.87448362e-01,   3.21140582e-02,
         2.28800228e+02,   6.84359848e+03,   2.99108027e+01,
         6.02048798e+01,   2.20737212e+02,   5.56828334e+02])

## Preprocess the Data

In [11]:
sc_X = StandardScaler()

In [12]:
X = sc_X.fit_transform(X)

In [13]:
le_Y = LabelEncoder()

In [14]:
Y = le_Y.fit_transform(Y)

In [15]:
X[0]

array([-0.34576577,  0.98599576, -0.81866399,  0.20132557, -0.02658146,
        0.27692953, -0.18745244,  0.29939563, -0.33421907])

In [16]:
Y[0]

1

## Create Train and Test data

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [18]:
X_train.shape

(84, 9)

In [19]:
X_test.shape

(22, 9)

In [20]:
Y_train.shape

(84,)

In [21]:
Y_test.shape

(22,)

In [22]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  19
4  15
1  14
5  13
3  12
2  11

In [23]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
1  7
5  5
3  3
2  3
0  3
4  1

## Decision Tree Classifier

In [24]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [25]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [26]:
Y_pred_dt = clf_dt.predict(X_test)

In [27]:
confusion_matrix(Y_test, Y_pred_dt)

array([[3, 0, 0, 0, 0, 0],
       [0, 7, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 3, 1]], dtype=int64)

## Random Forest Classifier

In [28]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [29]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [30]:
Y_pred_rf = clf_rf.predict(X_test)

In [31]:
confusion_matrix(Y_test, Y_pred_rf)

array([[2, 0, 1, 0, 0, 0],
       [0, 6, 0, 0, 0, 1],
       [1, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 3, 1]], dtype=int64)

## Naive Bayes Classifier

In [32]:
clf_nb = GaussianNB()

In [33]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [34]:
Y_pred_nb = clf_nb.predict(X_test)

In [35]:
confusion_matrix(Y_test, Y_pred_nb)

array([[2, 0, 1, 0, 0, 0],
       [0, 5, 0, 0, 0, 2],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 2, 2]], dtype=int64)

## KNN Classifier

In [36]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [37]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [38]:
Y_pred_knn = clf_knn.predict(X_test)

In [39]:
confusion_matrix(Y_test, Y_pred_knn)

array([[2, 0, 1, 0, 0, 0],
       [0, 6, 0, 0, 0, 1],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 2, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 2, 1, 2]], dtype=int64)

## Logistic Regression

In [40]:
clf_lr = LogisticRegression()

In [41]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [42]:
Y_pred_lr = clf_lr.predict(X_test)

In [43]:
confusion_matrix(Y_test, Y_pred_lr)

array([[3, 0, 0, 0, 0, 0],
       [0, 7, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 2, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 4, 0]], dtype=int64)

## SVC Linear

In [44]:
clf_lsvc = SVC(kernel = "linear")

In [45]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [46]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [47]:
confusion_matrix(Y_test, Y_pred_lsvc)

array([[3, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 1, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 3, 2]], dtype=int64)

## SVC Kernel

In [48]:
clf_ksvc = SVC(kernel = "rbf")

In [49]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [50]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [51]:
confusion_matrix(Y_test, Y_pred_ksvc)

array([[3, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 1, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 5, 0]], dtype=int64)

## Accuracy of Various Classifiers

In [52]:
model_accuracies['DT'] = accuracy_score(Y_test, Y_pred_dt)
model_accuracies['KNN'] = accuracy_score(Y_test, Y_pred_knn)
model_accuracies['KernelSVC'] = accuracy_score(Y_test, Y_pred_ksvc)
model_accuracies['LinearSVC'] = accuracy_score(Y_test, Y_pred_lsvc)
model_accuracies['LogReg'] = accuracy_score(Y_test, Y_pred_lr)
model_accuracies['NB'] = accuracy_score(Y_test, Y_pred_nb)
model_accuracies['RF'] = accuracy_score(Y_test, Y_pred_rf)
model_accuracies

{'DT': 0.63636363636363635,
 'KNN': 0.72727272727272729,
 'KernelSVC': 0.59090909090909094,
 'LinearSVC': 0.72727272727272729,
 'LogReg': 0.72727272727272729,
 'NB': 0.63636363636363635,
 'RF': 0.68181818181818177}