## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("data_banknote_authentication.txt", header=None)

In [3]:
dataset.columns = ["Variance", "Skewness", "Curtosis", "Entropy", "Class"]

In [4]:
dataset.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

## Creating X and Y

In [5]:
X = dataset.iloc[:, 0:4].values
Y = dataset.iloc[:, 4].values

In [6]:
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ..., 
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [7]:
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

## Create Train and Test Data

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 4)

In [9]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  566
1  463

In [10]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  196
1  147

## Create and Train the Classifier

In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [12]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu', input_dim = 4))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the Classifier on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", input_dim=4, activation="relu", units=5)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="sigmoid", units=1)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
1029/1029 [==============================] - 0s - loss: 0.6080 - acc: 0.7862     
Epoch 2/200
1029/1029 [==============================] - 0s - loss: 0.3126 - acc: 0.9320     
Epoch 3/200
1029/1029 [==============================] - 0s - loss: 0.1701 - acc: 0.9534     
Epoch 4/200
1029/1029 [==============================] - 0s - loss: 0.1141 - acc: 0.9747     
Epoch 5/200
1029/1029 [==============================] - 0s - loss: 0.0844 - acc: 0.9825     
Epoch 6/200
1029/1029 [==============================] - 0s - loss: 0.0662 - acc: 0.9864     
Epoch 7/200
1029/1029 [==============================] - 0s - loss: 0.0537 - acc: 0.9903     
Epoch 8/200
1029/1029 [==============================] - 0s - loss: 0.0450 - acc: 0.9922     
Epoch 9/200
1029/1029 [==============================] - 0s - loss: 0.0376 - acc: 0.9922     
Epoch 10/200
1029/1029 [==============================] - 0s - loss: 0.0319 - acc: 0.9971     
Epoch 11/200
1029/1029 [==============================] - 0

1029/1029 [==============================] - 0s - loss: 3.0335e-04 - acc: 1.0000     
Epoch 86/200
1029/1029 [==============================] - 0s - loss: 3.0278e-04 - acc: 1.0000     
Epoch 87/200
1029/1029 [==============================] - 0s - loss: 3.2121e-04 - acc: 1.0000     
Epoch 88/200
1029/1029 [==============================] - 0s - loss: 2.6262e-04 - acc: 1.0000     
Epoch 89/200
1029/1029 [==============================] - 0s - loss: 2.5925e-04 - acc: 1.0000     
Epoch 90/200
1029/1029 [==============================] - 0s - loss: 2.7716e-04 - acc: 1.0000     
Epoch 91/200
1029/1029 [==============================] - 0s - loss: 2.4485e-04 - acc: 1.0000     
Epoch 92/200
1029/1029 [==============================] - 0s - loss: 2.3662e-04 - acc: 1.0000     
Epoch 93/200
1029/1029 [==============================] - 0s - loss: 2.2803e-04 - acc: 1.0000     
Epoch 94/200
1029/1029 [==============================] - 0s - loss: 2.1057e-04 - acc: 1.0000     
Epoch 95/200
1029/1029 

1029/1029 [==============================] - 0s - loss: 1.2325e-05 - acc: 1.0000     
Epoch 168/200
1029/1029 [==============================] - 0s - loss: 1.2193e-05 - acc: 1.0000     
Epoch 169/200
1029/1029 [==============================] - 0s - loss: 1.1714e-05 - acc: 1.0000     
Epoch 170/200
1029/1029 [==============================] - 0s - loss: 1.1917e-05 - acc: 1.0000     
Epoch 171/200
1029/1029 [==============================] - 0s - loss: 1.0812e-05 - acc: 1.0000     
Epoch 172/200
1029/1029 [==============================] - 0s - loss: 1.1513e-05 - acc: 1.0000     
Epoch 173/200
1029/1029 [==============================] - 0s - loss: 1.0376e-05 - acc: 1.0000     
Epoch 174/200
1029/1029 [==============================] - 0s - loss: 1.0192e-05 - acc: 1.0000     
Epoch 175/200
1029/1029 [==============================] - 0s - loss: 9.9357e-06 - acc: 1.0000     
Epoch 176/200
1029/1029 [==============================] - 0s - loss: 9.6692e-06 - acc: 1.0000     
Epoch 177/200


In [13]:
# Test the Classifier on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [15]:
accuracy_score(Y_test, Y_pred)

1.0

In [16]:
confusion_matrix(Y_test, Y_pred)

array([[196,   0],
       [  0, 147]], dtype=int64)