## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("data_banknote_authentication.txt", header=None)

In [4]:
dataset.columns = ["Variance", "Skewness", "Curtosis", "Entropy", "Class"]

In [5]:
dataset.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

## Creating X and Y

In [6]:
X = dataset.iloc[:, 0:4].values
Y = dataset.iloc[:, 4].values

In [7]:
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ..., 
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

## Create Train and Test Data

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 4)

In [11]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  566
1  463

In [10]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  196
1  147

## Create and Train the Classifier

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [15]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 5, init = 'uniform', activation = 'relu', input_dim = 4))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the Classifier on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=5, activation="relu", input_dim=4, kernel_initializer="uniform")`
  if __name__ == '__main__':
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="uniform")`
  app.launch_new_instance()
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
1029/1029 [==============================] - 0s - loss: 0.6921 - acc: 0.5471     
Epoch 2/200
1029/1029 [==============================] - 0s - loss: 0.6808 - acc: 0.5500     
Epoch 3/200
1029/1029 [==============================] - 0s - loss: 0.6218 - acc: 0.5500     
Epoch 4/200
1029/1029 [==============================] - 0s - loss: 0.5354 - acc: 0.5578     
Epoch 5/200
1029/1029 [==============================] - 0s - loss: 0.4526 - acc: 0.9203     
Epoch 6/200
1029/1029 [==============================] - 0s - loss: 0.3837 - acc: 0.9893     
Epoch 7/200
1029/1029 [==============================] - 0s - loss: 0.3279 - acc: 0.9961     
Epoch 8/200
1029/1029 [==============================] - 0s - loss: 0.2823 - acc: 0.9990     
Epoch 9/200
1029/1029 [==============================] - 0s - loss: 0.2449 - acc: 0.9990     
Epoch 10/200
1029/1029 [==============================] - 0s - loss: 0.2136 - acc: 1.0000     
Epoch 11/200
1029/1029 [==============================] - 0

1029/1029 [==============================] - 0s - loss: 3.3679e-07 - acc: 1.0000     
Epoch 168/200
1029/1029 [==============================] - 0s - loss: 2.9468e-06 - acc: 1.0000     
Epoch 169/200
1029/1029 [==============================] - 0s - loss: 4.4617e-07 - acc: 1.0000     
Epoch 170/200
1029/1029 [==============================] - 0s - loss: 3.1180e-07 - acc: 1.0000     
Epoch 171/200
1029/1029 [==============================] - 0s - loss: 3.0870e-07 - acc: 1.0000     
Epoch 172/200
1029/1029 [==============================] - 0s - loss: 2.8997e-07 - acc: 1.0000     
Epoch 173/200
1029/1029 [==============================] - 0s - loss: 2.7835e-07 - acc: 1.0000     
Epoch 174/200
1029/1029 [==============================] - 0s - loss: 2.7719e-07 - acc: 1.0000     
Epoch 175/200
1029/1029 [==============================] - 0s - loss: 2.7643e-07 - acc: 1.0000     
Epoch 176/200
1029/1029 [==============================] - 0s - loss: 2.7578e-07 - acc: 1.0000     
Epoch 177/200


In [16]:
# Test the Classifier on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [18]:
accuracy_score(Y_pred, Y_test)

1.0

In [19]:
confusion_matrix(Y_pred, Y_test)

array([[196,   0],
       [  0, 147]], dtype=int64)