## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("Dataset.txt", header = None, delimiter = r"\s+")
dataset.shape

(846, 19)

In [3]:
dataset.head()

0   1    2    3    4   5    6   7   8    9    10   11   12   13  14  15  \
0   95  48   83  178   72  10  162  42  20  159  176  379  184   70   6  16   
1   91  41   84  141   57   9  149  45  19  143  170  330  158   72   9  14   
2  104  50  106  209   66  10  207  32  23  158  223  635  220   73  14   9   
3   93  41   82  159   63   9  144  46  19  143  160  309  127   63   6  10   
4   85  44   70  205  103  52  149  45  19  144  241  325  188  127   9  11   

    16   17    18  
0  187  197   van  
1  189  199   van  
2  188  196  saab  
3  199  207   van  
4  180  183   bus

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:18].values
Y = dataset.iloc[:, 18].values

In [5]:
X[0]

array([ 95,  48,  83, 178,  72,  10, 162,  42,  20, 159, 176, 379, 184,
        70,   6,  16, 187, 197], dtype=int64)

In [6]:
Y[0]

'van'

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [8]:
le_Y = LabelEncoder()

In [9]:
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)
Y[0]

array([3], dtype=int64)

In [10]:
ohe_Y = OneHotEncoder(categorical_features = [0])

In [11]:
Y = ohe_Y.fit_transform(Y).toarray()
Y[0]

array([ 0.,  0.,  0.,  1.])

In [12]:
sc_X = StandardScaler()

In [13]:
X = sc_X.fit_transform(X)
X[0]

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([ 0.16058035,  0.5089502 ,  0.05781852,  0.27080578,  1.30729142,
        0.31154185, -0.2058443 ,  0.13656998, -0.22494441,  0.75833245,
       -0.40238349, -0.3449345 ,  0.28581238, -0.32905569, -0.07671097,
        0.38099086, -0.31372213,  0.18395733])

## Create Train and Test Data

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [15]:
X_train.shape

(676, 18)

In [16]:
X_test.shape

(170, 18)

In [17]:
Y_train.shape

(676, 4)

In [18]:
Y_test.shape

(170, 4)

## Create and train the Classifier

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 11, init = 'uniform', activation = 'relu', input_dim = 18))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 11, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 4, init = 'uniform', activation = 'softmax'))

clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=11, kernel_initializer="uniform", input_dim=18, activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=11)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="softmax", units=4)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
676/676 [==============================] - 0s - loss: 1.3804 - acc: 0.3151     
Epoch 2/200
676/676 [==============================] - 0s - loss: 1.2979 - acc: 0.4038     
Epoch 3/200
676/676 [==============================] - 0s - loss: 1.1966 - acc: 0.3905     
Epoch 4/200
676/676 [==============================] - 0s - loss: 1.1421 - acc: 0.4142     
Epoch 5/200
676/676 [==============================] - 0s - loss: 1.0960 - acc: 0.4334     
Epoch 6/200
676/676 [==============================] - 0s - loss: 1.0565 - acc: 0.4571     
Epoch 7/200
676/676 [==============================] - 0s - loss: 1.0210 - acc: 0.4793     
Epoch 8/200
676/676 [==============================] - 0s - loss: 0.9845 - acc: 0.4941     
Epoch 9/200
676/676 [==============================] - 0s - loss: 0.9453 - acc: 0.5385     
Epoch 10/200
676/676 [==============================] - 0s - loss: 0.9019 - acc: 0.5814     
Epoch 11/200
676/676 [==============================] - 0s - loss: 0.8507 - acc

676/676 [==============================] - 0s - loss: 0.3017 - acc: 0.8595     
Epoch 90/200
676/676 [==============================] - 0s - loss: 0.2977 - acc: 0.8565     
Epoch 91/200
676/676 [==============================] - 0s - loss: 0.2940 - acc: 0.8565     
Epoch 92/200
676/676 [==============================] - 0s - loss: 0.2992 - acc: 0.8550     
Epoch 93/200
676/676 [==============================] - 0s - loss: 0.2977 - acc: 0.8565     
Epoch 94/200
676/676 [==============================] - 0s - loss: 0.2956 - acc: 0.8669     
Epoch 95/200
676/676 [==============================] - 0s - loss: 0.2880 - acc: 0.8654     
Epoch 96/200
676/676 [==============================] - 0s - loss: 0.2920 - acc: 0.8669     
Epoch 97/200
676/676 [==============================] - 0s - loss: 0.2935 - acc: 0.8609     
Epoch 98/200
676/676 [==============================] - 0s - loss: 0.2924 - acc: 0.8654     
Epoch 99/200
676/676 [==============================] - 0s - loss: 0.2883 - acc: 0.

676/676 [==============================] - 0s - loss: 0.2250 - acc: 0.8979     
Epoch 177/200
676/676 [==============================] - 0s - loss: 0.2249 - acc: 0.8935     
Epoch 178/200
676/676 [==============================] - 0s - loss: 0.2185 - acc: 0.9038     
Epoch 179/200
676/676 [==============================] - 0s - loss: 0.2244 - acc: 0.8950     
Epoch 180/200
676/676 [==============================] - 0s - loss: 0.2181 - acc: 0.9142     
Epoch 181/200
676/676 [==============================] - 0s - loss: 0.2199 - acc: 0.9068     
Epoch 182/200
676/676 [==============================] - 0s - loss: 0.2184 - acc: 0.8994     
Epoch 183/200
676/676 [==============================] - 0s - loss: 0.2179 - acc: 0.9053     
Epoch 184/200
676/676 [==============================] - 0s - loss: 0.2203 - acc: 0.9024     
Epoch 185/200
676/676 [==============================] - 0s - loss: 0.2188 - acc: 0.9068     
Epoch 186/200
676/676 [==============================] - 0s - loss: 0.2228

In [21]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test_class, Y_pred_class)

0.80588235294117649

In [23]:
confusion_matrix(Y_test_class, Y_pred_class)

array([[40,  0,  1,  1],
       [ 1, 31, 17,  0],
       [ 0, 12, 27,  0],
       [ 1,  0,  0, 39]], dtype=int64)