## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv("Dataset.txt", header = None, delimiter = r"\s+")
dataset.shape

(846, 19)

In [3]:
dataset.head()

0   1    2    3    4   5    6   7   8    9    10   11   12   13  14  15  \
0   95  48   83  178   72  10  162  42  20  159  176  379  184   70   6  16   
1   91  41   84  141   57   9  149  45  19  143  170  330  158   72   9  14   
2  104  50  106  209   66  10  207  32  23  158  223  635  220   73  14   9   
3   93  41   82  159   63   9  144  46  19  143  160  309  127   63   6  10   
4   85  44   70  205  103  52  149  45  19  144  241  325  188  127   9  11   

    16   17    18  
0  187  197   van  
1  189  199   van  
2  188  196  saab  
3  199  207   van  
4  180  183   bus

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:18].values
Y = dataset.iloc[:, 18].values

In [5]:
X

array([[ 95,  48,  83, ...,  16, 187, 197],
       [ 91,  41,  84, ...,  14, 189, 199],
       [104,  50, 106, ...,   9, 188, 196],
       ..., 
       [106,  54, 101, ...,   4, 187, 201],
       [ 86,  36,  78, ...,  25, 190, 195],
       [ 85,  36,  66, ...,  18, 186, 190]], dtype=int64)

In [6]:
Y

array(['van', 'van', 'saab', 'van', 'bus', 'bus', 'bus', 'van', 'van',
       'saab', 'van', 'saab', 'bus', 'van', 'bus', 'opel', 'van', 'bus',
       'saab', 'opel', 'bus', 'van', 'bus', 'bus', 'saab', 'van', 'saab',
       'saab', 'bus', 'saab', 'van', 'saab', 'opel', 'opel', 'opel', 'van',
       'bus', 'van', 'saab', 'bus', 'opel', 'van', 'van', 'saab', 'saab',
       'van', 'van', 'bus', 'van', 'saab', 'saab', 'saab', 'opel', 'bus',
       'bus', 'van', 'saab', 'van', 'opel', 'van', 'opel', 'opel', 'van',
       'bus', 'bus', 'opel', 'bus', 'opel', 'van', 'bus', 'opel', 'opel',
       'opel', 'opel', 'van', 'opel', 'saab', 'saab', 'bus', 'bus', 'bus',
       'bus', 'van', 'opel', 'bus', 'bus', 'van', 'van', 'bus', 'opel',
       'saab', 'opel', 'saab', 'van', 'bus', 'opel', 'saab', 'bus', 'opel',
       'bus', 'bus', 'van', 'van', 'van', 'bus', 'saab', 'opel', 'opel',
       'bus', 'bus', 'van', 'van', 'opel', 'opel', 'van', 'van', 'opel',
       'saab', 'bus', 'bus', 'saab', 'van

## Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [8]:
le_Y = LabelEncoder()

In [9]:
Y = le_Y.fit_transform(Y)
Y = Y.reshape(len(Y), 1)
Y

array([[3],
       [3],
       [2],
       [3],
       [0],
       [0],
       [0],
       [3],
       [3],
       [2],
       [3],
       [2],
       [0],
       [3],
       [0],
       [1],
       [3],
       [0],
       [2],
       [1],
       [0],
       [3],
       [0],
       [0],
       [2],
       [3],
       [2],
       [2],
       [0],
       [2],
       [3],
       [2],
       [1],
       [1],
       [1],
       [3],
       [0],
       [3],
       [2],
       [0],
       [1],
       [3],
       [3],
       [2],
       [2],
       [3],
       [3],
       [0],
       [3],
       [2],
       [2],
       [2],
       [1],
       [0],
       [0],
       [3],
       [2],
       [3],
       [1],
       [3],
       [1],
       [1],
       [3],
       [0],
       [0],
       [1],
       [0],
       [1],
       [3],
       [0],
       [1],
       [1],
       [1],
       [1],
       [3],
       [1],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [3],
    

In [10]:
ohe_Y = OneHotEncoder(categorical_features = [0])

In [11]:
Y = ohe_Y.fit_transform(Y).toarray()
Y

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.],
       ..., 
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [12]:
sc_X = StandardScaler()

In [13]:
X = sc_X.fit_transform(X)
X

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.16058035,  0.5089502 ,  0.05781852, ...,  0.38099086,
        -0.31372213,  0.18395733],
       [-0.32546965, -0.62626753,  0.1212614 , ...,  0.15692533,
         0.0109371 ,  0.45297703],
       [ 1.25419283,  0.83329812,  1.51700488, ..., -0.4032385 ,
        -0.15139252,  0.04944748],
       ..., 
       [ 1.49721783,  1.48199396,  1.19979045, ..., -0.96340232,
        -0.31372213,  0.72199673],
       [-0.93303214, -1.43713733, -0.25939591, ...,  1.38928574,
         0.17326672, -0.08506238],
       [-1.05454464, -1.43713733, -1.02071053, ...,  0.60505639,
        -0.47605175, -0.75761164]])

## Create Train and Test Data

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [15]:
X_train.shape

(676, 18)

In [16]:
X_test.shape

(170, 18)

In [17]:
Y_train.shape

(676, 4)

In [18]:
Y_test.shape

(170, 4)

## Create and train the Classifier

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 11, init = 'uniform', activation = 'relu', input_dim = 18))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 11, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 4, init = 'uniform', activation = 'softmax'))

clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", input_dim=18, units=11)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=11, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=4, kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
676/676 [==============================] - 0s - loss: 1.3813 - acc: 0.3269     
Epoch 2/200
676/676 [==============================] - 0s - loss: 1.2964 - acc: 0.4260     
Epoch 3/200
676/676 [==============================] - 0s - loss: 1.2018 - acc: 0.4112     
Epoch 4/200
676/676 [==============================] - 0s - loss: 1.1425 - acc: 0.4260     
Epoch 5/200
676/676 [==============================] - 0s - loss: 1.0899 - acc: 0.4512     
Epoch 6/200
676/676 [==============================] - 0s - loss: 1.0424 - acc: 0.4911     
Epoch 7/200
676/676 [==============================] - 0s - loss: 0.9906 - acc: 0.5547     
Epoch 8/200
676/676 [==============================] - 0s - loss: 0.9355 - acc: 0.5962     
Epoch 9/200
676/676 [==============================] - 0s - loss: 0.8745 - acc: 0.6464     
Epoch 10/200
676/676 [==============================] - 0s - loss: 0.8138 - acc: 0.6642     
Epoch 11/200
676/676 [==============================] - 0s - loss: 0.7552 - acc

676/676 [==============================] - 0s - loss: 0.2939 - acc: 0.8580     
Epoch 90/200
676/676 [==============================] - 0s - loss: 0.2948 - acc: 0.8521     
Epoch 91/200
676/676 [==============================] - 0s - loss: 0.2901 - acc: 0.8506     
Epoch 92/200
676/676 [==============================] - 0s - loss: 0.2897 - acc: 0.8521     
Epoch 93/200
676/676 [==============================] - 0s - loss: 0.2905 - acc: 0.8580     
Epoch 94/200
676/676 [==============================] - 0s - loss: 0.2896 - acc: 0.8654     
Epoch 95/200
676/676 [==============================] - 0s - loss: 0.2857 - acc: 0.8654     
Epoch 96/200
676/676 [==============================] - 0s - loss: 0.2884 - acc: 0.8595     
Epoch 97/200
676/676 [==============================] - 0s - loss: 0.2865 - acc: 0.8609     
Epoch 98/200
676/676 [==============================] - ETA: 0s - loss: 0.3910 - acc: 0.600 - 0s - loss: 0.2797 - acc: 0.8683     
Epoch 99/200
676/676 [=======================

676/676 [==============================] - 0s - loss: 0.2059 - acc: 0.9127     
Epoch 177/200
676/676 [==============================] - 0s - loss: 0.2162 - acc: 0.9053     
Epoch 178/200
676/676 [==============================] - 0s - loss: 0.2083 - acc: 0.9083     
Epoch 179/200
676/676 [==============================] - 0s - loss: 0.2050 - acc: 0.9201     
Epoch 180/200
676/676 [==============================] - 0s - loss: 0.2121 - acc: 0.9112     
Epoch 181/200
676/676 [==============================] - 0s - loss: 0.2059 - acc: 0.9053     
Epoch 182/200
676/676 [==============================] - 0s - loss: 0.2066 - acc: 0.9053     
Epoch 183/200
676/676 [==============================] - 0s - loss: 0.2029 - acc: 0.9068     
Epoch 184/200
676/676 [==============================] - 0s - loss: 0.2010 - acc: 0.9186     
Epoch 185/200
676/676 [==============================] - 0s - loss: 0.2051 - acc: 0.9053     
Epoch 186/200
676/676 [==============================] - 0s - loss: 0.2007

In [21]:
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred_class, Y_test_class)

0.81764705882352939

In [23]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[40,  2,  0,  0],
       [ 0, 26,  6,  0],
       [ 2, 20, 33,  0],
       [ 0,  1,  0, 40]], dtype=int64)