## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('ThoraricSurgery.csv', header = None)
dataset.shape

(470, 17)

In [3]:
dataset.head()

0     1     2     3  4  5  6  7  8     9  10 11 12 13 14  15 16
0  DGN2  2.88  2.16  PRZ1  F  F  F  T  T  OC14  F  F  F  T  F  60  F
1  DGN3  3.40  1.88  PRZ0  F  F  F  F  F  OC12  F  F  F  T  F  51  F
2  DGN3  2.76  2.08  PRZ1  F  F  F  T  F  OC11  F  F  F  T  F  59  F
3  DGN3  3.68  3.04  PRZ0  F  F  F  F  F  OC11  F  F  F  F  F  54  F
4  DGN3  2.44  0.96  PRZ2  F  T  F  T  T  OC11  F  F  F  T  F  73  T

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:16].values
Y = dataset.iloc[:, 16].values

In [5]:
X.shape

(470, 16)

In [6]:
Y.shape

(470,)

In [7]:
X

array([['DGN2', 2.88, 2.16, ..., 'T', 'F', 60],
       ['DGN3', 3.4, 1.88, ..., 'T', 'F', 51],
       ['DGN3', 2.76, 2.08, ..., 'T', 'F', 59],
       ..., 
       ['DGN3', 3.04, 2.08, ..., 'F', 'F', 52],
       ['DGN3', 1.96, 1.68, ..., 'T', 'F', 79],
       ['DGN3', 4.72, 3.56, ..., 'T', 'F', 51]], dtype=object)

## Preprocess the Data

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [9]:
le_Y = LabelEncoder()

In [10]:
Y = le_Y.fit_transform(Y)
Y

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0,

In [11]:
def enocder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])

In [12]:
X_indices = [0] + list(range(3,15))
X_indices

[0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [13]:
for x in X_indices:
    enocder_X(x)

In [14]:
X.shape

(470, 16)

In [15]:
pd.DataFrame(pd.DataFrame(X[:, 9])[0].value_counts())

0
1  257
0  177
2   19
3   17

In [16]:
ohe_X = OneHotEncoder(categorical_features = [9])

In [17]:
X = ohe_X.fit_transform(X).toarray()
X.shape

(470, 19)

In [18]:
X = X[:, 1:]
X.shape

(470, 18)

In [19]:
pd.DataFrame(pd.DataFrame(X[:, 6])[0].value_counts())

0
1.0  313
0.0  130
2.0   27

In [20]:
ohe_X = OneHotEncoder(categorical_features = [6])

In [21]:
X = ohe_X.fit_transform(X).toarray()
X.shape

(470, 20)

In [22]:
X = X[:, 1:]
X.shape

(470, 19)

In [23]:
pd.DataFrame(pd.DataFrame(X[:, 5])[0].value_counts())

0
2.0  349
1.0   52
3.0   47
4.0   15
5.0    4
6.0    2
0.0    1

In [24]:
ohe_X = OneHotEncoder(categorical_features = [5])

In [25]:
X = ohe_X.fit_transform(X).toarray()
X.shape

(470, 25)

In [26]:
X = X[:, 1:]
X.shape

(470, 24)

In [27]:
sc_X = StandardScaler()

In [28]:
X = sc_X.fit_transform(X)
X

array([[ 2.83521808, -1.69832197, -0.33333333, ...,  0.46649392,
        -0.06537205, -0.29134848],
       [-0.35270655,  0.5888165 , -0.33333333, ...,  0.46649392,
        -0.06537205, -1.32611263],
       [-0.35270655,  0.5888165 , -0.33333333, ...,  0.46649392,
        -0.06537205, -0.40632228],
       ..., 
       [-0.35270655,  0.5888165 , -0.33333333, ..., -2.14365065,
        -0.06537205, -1.21113883],
       [-0.35270655,  0.5888165 , -0.33333333, ...,  0.46649392,
        -0.06537205,  1.89315359],
       [-0.35270655,  0.5888165 , -0.33333333, ...,  0.46649392,
        -0.06537205, -1.32611263]])

## Create Train and Test Data

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [31]:
X_train.shape

(376, 24)

In [32]:
X_test.shape

(94, 24)

In [33]:
Y_train.shape

(376,)

In [34]:
Y_test.shape

(94,)

## Create and train the ANN Classifier

In [35]:
from keras.models import Sequential
from keras.layers import Dense

In [36]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 13, init = 'uniform', activation = 'relu', input_dim = 24))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 13, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=13, input_dim=24)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=13, kernel_initializer="uniform", activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="uniform", activation="sigmoid")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
376/376 [==============================] - 0s - loss: 0.6690 - acc: 0.8484     
Epoch 2/200
376/376 [==============================] - 0s - loss: 0.5151 - acc: 0.8617     
Epoch 3/200
376/376 [==============================] - 0s - loss: 0.3687 - acc: 0.8617     
Epoch 4/200
376/376 [==============================] - 0s - loss: 0.3472 - acc: 0.8617     
Epoch 5/200
376/376 [==============================] - 0s - loss: 0.3384 - acc: 0.8617     
Epoch 6/200
376/376 [==============================] - 0s - loss: 0.3320 - acc: 0.8617     
Epoch 7/200
376/376 [==============================] - 0s - loss: 0.3274 - acc: 0.8617     
Epoch 8/200
376/376 [==============================] - 0s - loss: 0.3223 - acc: 0.8617     
Epoch 9/200
376/376 [==============================] - 0s - loss: 0.3192 - acc: 0.8617     
Epoch 10/200
376/376 [==============================] - 0s - loss: 0.3145 - acc: 0.8617     
Epoch 11/200
376/376 [==============================] - 0s - loss: 0.3104 - acc

376/376 [==============================] - 0s - loss: 0.1351 - acc: 0.9574     
Epoch 90/200
376/376 [==============================] - 0s - loss: 0.1343 - acc: 0.9574     
Epoch 91/200
376/376 [==============================] - 0s - loss: 0.1342 - acc: 0.9574     
Epoch 92/200
376/376 [==============================] - 0s - loss: 0.1380 - acc: 0.9574     
Epoch 93/200
376/376 [==============================] - 0s - loss: 0.1329 - acc: 0.9574     
Epoch 94/200
376/376 [==============================] - 0s - loss: 0.1303 - acc: 0.9574     
Epoch 95/200
376/376 [==============================] - 0s - loss: 0.1290 - acc: 0.9574     
Epoch 96/200
376/376 [==============================] - 0s - loss: 0.1299 - acc: 0.9601     
Epoch 97/200
376/376 [==============================] - 0s - loss: 0.1292 - acc: 0.9574     
Epoch 98/200
376/376 [==============================] - 0s - loss: 0.1287 - acc: 0.9601     
Epoch 99/200
376/376 [==============================] - 0s - loss: 0.1310 - acc: 0.

376/376 [==============================] - 0s - loss: 0.0930 - acc: 0.9681         
Epoch 177/200
376/376 [==============================] - 0s - loss: 0.0952 - acc: 0.9654     
Epoch 178/200
376/376 [==============================] - 0s - loss: 0.0934 - acc: 0.9654         
Epoch 179/200
376/376 [==============================] - 0s - loss: 0.0935 - acc: 0.9628     
Epoch 180/200
376/376 [==============================] - 0s - loss: 0.0943 - acc: 0.9707     
Epoch 181/200
376/376 [==============================] - 0s - loss: 0.0940 - acc: 0.9654         
Epoch 182/200
376/376 [==============================] - 0s - loss: 0.0902 - acc: 0.9681     
Epoch 183/200
376/376 [==============================] - 0s - loss: 0.0923 - acc: 0.9707     
Epoch 184/200
376/376 [==============================] - 0s - loss: 0.0938 - acc: 0.9601     
Epoch 185/200
376/376 [==============================] - 0s - loss: 0.0932 - acc: 0.9681     
Epoch 186/200
376/376 [==============================] - 0s - 

In [37]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [38]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [39]:
accuracy_score(Y_pred, Y_test)

0.75531914893617025

In [40]:
confusion_matrix(Y_pred, Y_test)

array([[71, 18],
       [ 5,  0]], dtype=int64)