## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
dataset = pd.read_excel('Dataset.xls')
dataset.shape

(30000, 24)

In [6]:
dataset.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   

   PAY_5             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0     -2             ...                      0          0          0   
1      0             ...                   3272       3455       3261   
2      0             ...                  14331      14948      15549   
3      0             ...                  28314      28959      29547   
4      0             ...                  20940      19146      19131   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         0       689         0         0         0         0   
1         0      1000      1000      1000         0      2000   
2      1518      1500      1000      1000      1000      5000   
3      2000      2019      1200      1100      1069      1000   
4      2000     36681     10000      9000       689       679   

   default payment next month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 24 columns]

## Create X and Y

In [7]:
Y = dataset.iloc[:, 23].values
Y.shape

(30000,)

In [8]:
Y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [9]:
X = dataset.iloc[:, 0:23].values
X.shape

(30000, 23)

In [10]:
X

array([[ 20000,      2,      2, ...,      0,      0,      0],
       [120000,      2,      2, ...,   1000,      0,   2000],
       [ 90000,      2,      2, ...,   1000,   1000,   5000],
       ..., 
       [ 30000,      1,      2, ...,   4200,   2000,   3100],
       [ 80000,      1,      3, ...,   1926,  52964,   1804],
       [ 50000,      1,      2, ...,   1000,   1000,   1000]], dtype=int64)

##  Preprocess the Data

In [11]:
le_X = LabelEncoder()
X[:, 1] = le_X.fit_transform(X[:, 1])

In [12]:
le_X = LabelEncoder()
X[:, 2] = le_X.fit_transform(X[:, 2])

In [13]:
le_X = LabelEncoder()
X[:, 3] = le_X.fit_transform(X[:, 3])

In [14]:
ohe_X = OneHotEncoder(categorical_features = [1])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [15]:
ohe_X = OneHotEncoder(categorical_features = [2])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [16]:
ohe_X = OneHotEncoder(categorical_features = [8])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [17]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [18]:
pd.DataFrame(X)

0         1         2         3         4         5         6   \
0      1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
1     -0.914261  0.937672 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
2     -0.914261  0.937672 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
3      1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
4      1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
5     -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
6     -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
7     -0.914261  0.937672 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
8      1.093780 -1.066471 -0.104326 -0.738375 -0.937295  2.258602 -0.064163   
9     -0.914261  0.937672 -0.104326 -0.738375 -0.937295  2.258602 -0.064163   
10    -0.914261  0.937672 -0.104326 -0.738375 -0.937295  2.258602 -0.064163   
11    -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
12    -0.914261  0.937672 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
13    -0.914261  0.937672 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
14    -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
15    -0.914261 -1.066471  9.585367 -0.738375 -0.937295  2.258602 -0.064163   
16    -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
17     1.093780 -1.066471 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
18     1.093780 -1.066471 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
19    -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
20    -0.914261  0.937672 -0.104326 -0.738375 -0.937295  2.258602 -0.064163   
21     1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
22    -0.914261  0.937672 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
23     1.093780 -1.066471 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
24    -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
25    -0.914261  0.937672 -0.104326 -0.738375 -0.937295  2.258602 -0.064163   
26    -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
27    -0.914261  0.937672 -0.104326 -0.738375 -0.937295  2.258602 -0.064163   
28     1.093780 -1.066471 -0.104326 -0.738375 -0.937295  2.258602 -0.064163   
29    -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
...         ...       ...       ...       ...       ...       ...       ...   
29970  1.093780 -1.066471 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
29971  1.093780 -1.066471 -0.104326 -0.738375 -0.937295  2.258602 -0.064163   
29972  1.093780 -1.066471 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
29973  1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
29974  1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
29975  1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
29976 -0.914261  0.937672 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
29977 -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
29978  1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
29979  1.093780 -1.066471 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
29980 -0.914261  0.937672 -0.104326 -0.738375 -0.937295  2.258602 -0.064163   
29981  1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
29982  1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
29983  1.093780 -1.066471 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
29984 -0.914261  0.937672 -0.104326 -0.738375  1.066900 -0.442752 -0.064163   
29985 -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
29986 -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
29987 -0.914261  0.937672 -0.104326  1.354326 -0.937295 -0.442752 -0.064163   
29988  1.093780 -1.066471 -0.104326  1.354326 -0.937295 -0.4427

## Create Train and Test data

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [20]:
X_train.shape

(24000, 30)

In [21]:
X_test.shape

(6000, 30)

In [22]:
Y_train.shape

(24000,)

In [23]:
Y_test.shape

(6000,)

In [24]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  18726
1   5274

In [25]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  4638
1  1362

## Decision Tree Classifier

In [26]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [27]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [28]:
Y_pred_dt = clf_dt.predict(X_test)

In [29]:
cm_dt = confusion_matrix(Y_pred_dt, Y_test)
cm_dt

array([[3831,  829],
       [ 807,  533]], dtype=int64)

## Random Forest Classifier

In [30]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [31]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [32]:
Y_pred_rf = clf_rf.predict(X_test)

In [33]:
cm_rf = confusion_matrix(Y_pred_rf, Y_test)
cm_rf

array([[4385,  920],
       [ 253,  442]], dtype=int64)

## Naive Bayes Classifier

In [34]:
clf_nb = GaussianNB()

In [35]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [36]:
Y_pred_nb = clf_nb.predict(X_test)

In [37]:
cm_nb = confusion_matrix(Y_pred_nb, Y_test)
cm_nb

array([[1610,  231],
       [3028, 1131]], dtype=int64)

## KNN Classifier

In [38]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [39]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [40]:
Y_pred_knn = clf_knn.predict(X_test)

In [41]:
cm_knn = confusion_matrix(Y_pred_knn, Y_test)
cm_knn

array([[4253,  899],
       [ 385,  463]], dtype=int64)

## Logistic Regression

In [42]:
clf_lr = LogisticRegression()

In [43]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [44]:
Y_pred_lr = clf_lr.predict(X_test)

In [45]:
cm_lr = confusion_matrix(Y_pred_lr, Y_test)
cm_lr

array([[4504, 1049],
       [ 134,  313]], dtype=int64)

## SVC Linear

In [46]:
clf_lsvc = SVC(kernel = "linear")

In [47]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [48]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [49]:
cm_lsvc = confusion_matrix(Y_pred_lsvc, Y_test)
cm_lsvc

array([[4515, 1054],
       [ 123,  308]], dtype=int64)

## SVC Kernel

In [50]:
clf_ksvc = SVC(kernel = "rbf")

In [51]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [52]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [53]:
cm_ksvc = confusion_matrix(Y_pred_ksvc, Y_test)
cm_ksvc

array([[4454,  916],
       [ 184,  446]], dtype=int64)

## Accuracy of Various Classifiers

In [54]:
model_accuracies['DT'] = accuracy_score(Y_pred_dt, Y_test)
model_accuracies['KNN'] = accuracy_score(Y_pred_knn, Y_test)
model_accuracies['KernelSVC'] = accuracy_score(Y_pred_ksvc, Y_test)
model_accuracies['LinearSVC'] = accuracy_score(Y_pred_lsvc, Y_test)
model_accuracies['LogReg'] = accuracy_score(Y_pred_lr, Y_test)
model_accuracies['NB'] = accuracy_score(Y_pred_nb, Y_test)
model_accuracies['RF'] = accuracy_score(Y_pred_rf, Y_test)
model_accuracies

{'DT': 0.72733333333333339,
 'KNN': 0.78600000000000003,
 'KernelSVC': 0.81666666666666665,
 'LinearSVC': 0.80383333333333329,
 'LogReg': 0.80283333333333329,
 'NB': 0.45683333333333331,
 'RF': 0.80449999999999999}