## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [3]:
dataset = pd.read_excel('Dataset.xls')
dataset.shape

(30000, 24)

In [4]:
dataset.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   

   PAY_5             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0     -2             ...                      0          0          0   
1      0             ...                   3272       3455       3261   
2      0             ...                  14331      14948      15549   
3      0             ...                  28314      28959      29547   
4      0             ...                  20940      19146      19131   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         0       689         0         0         0         0   
1         0      1000      1000      1000         0      2000   
2      1518      1500      1000      1000      1000      5000   
3      2000      2019      1200      1100      1069      1000   
4      2000     36681     10000      9000       689       679   

   default payment next month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 24 columns]

## Create X and Y

In [5]:
Y = dataset.iloc[:, 23].values
Y.shape

(30000,)

In [6]:
Y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [7]:
X = dataset.iloc[:, 0:23].values
X.shape

(30000, 23)

In [8]:
X

array([[ 20000,      2,      2, ...,      0,      0,      0],
       [120000,      2,      2, ...,   1000,      0,   2000],
       [ 90000,      2,      2, ...,   1000,   1000,   5000],
       ..., 
       [ 30000,      1,      2, ...,   4200,   2000,   3100],
       [ 80000,      1,      3, ...,   1926,  52964,   1804],
       [ 50000,      1,      2, ...,   1000,   1000,   1000]], dtype=int64)

## Preprocess the Data

In [9]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [11]:
le_X = LabelEncoder()
X[:, 1] = le_X.fit_transform(X[:, 1])

In [12]:
le_X = LabelEncoder()
X[:, 2] = le_X.fit_transform(X[:, 2])

In [13]:
le_X = LabelEncoder()
X[:, 3] = le_X.fit_transform(X[:, 3])

In [14]:
ohe_X = OneHotEncoder(categorical_features = [1])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [15]:
ohe_X = OneHotEncoder(categorical_features = [2])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [16]:
ohe_X = OneHotEncoder(categorical_features = [8])
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]

In [113]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [114]:
pd.DataFrame(X).head()

0         1         2         3       4         5         6   \
0  1.093780 -1.066471 -0.104326 -0.738375  1.0669 -0.442752 -0.064163   
1 -0.914261  0.937672 -0.104326 -0.738375  1.0669 -0.442752 -0.064163   
2 -0.914261  0.937672 -0.104326 -0.738375  1.0669 -0.442752 -0.064163   
3  1.093780 -1.066471 -0.104326 -0.738375  1.0669 -0.442752 -0.064163   
4  1.093780 -1.066471 -0.104326 -0.738375  1.0669 -0.442752 -0.064163   

         7         8         9     ...           20        21        22  \
0 -0.097063 -0.041266  0.810161    ...    -0.667993 -0.672497 -0.663059   
1 -0.097063 -0.041266  0.810161    ...    -0.639254 -0.621636 -0.606229   
2 -0.097063 -0.041266  0.810161    ...    -0.482408 -0.449730 -0.417188   
3 -0.097063 -0.041266  0.810161    ...     0.032846 -0.232373 -0.186729   
4 -0.097063 -0.041266 -1.234323    ...    -0.161189 -0.346997 -0.348137   

         23        24        25        26        27        28        29  
0 -0.652724 -0.341942 -0.227086 -0.296801 -0.308063 -0.314136 -0.293382  
1 -0.597966 -0.341942 -0.213588 -0.240005 -0.244230 -0.314136 -0.180878  
2 -0.391630 -0.250292 -0.191887 -0.240005 -0.244230 -0.248683 -0.012122  
3 -0.156579 -0.221191 -0.169361 -0.228645 -0.237846 -0.244166 -0.237130  
4 -0.331482 -0.221191  1.335034  0.271165  0.266434 -0.269039 -0.255187  

[5 rows x 30 columns]

## Create Train and Test Data

In [115]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [116]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  18726
1   5274

In [117]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  4638
1  1362

## Create and train the Classifier

In [118]:
from keras.models import Sequential
from keras.layers import Dense

In [159]:
clf_ann = Sequential()

clf_ann.add(Dense(output_dim = 15, init = 'uniform', activation = 'relu', input_dim = 30))

clf_ann.add(Dense(output_dim = 15, init = 'uniform', activation = 'relu'))

clf_ann.add(Dense(output_dim = 15, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=15, activation="relu", kernel_initializer="uniform", input_dim=30)`
  app.launch_new_instance()
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=15, activation="relu", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=15, activation="relu", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '

Epoch 1/100
24000/24000 [==============================] - 1s - loss: 0.4865 - acc: 0.7834     
Epoch 2/100
24000/24000 [==============================] - 1s - loss: 0.4689 - acc: 0.8043     
Epoch 3/100
24000/24000 [==============================] - 1s - loss: 0.4664 - acc: 0.8088     
Epoch 4/100
24000/24000 [==============================] - 1s - loss: 0.4659 - acc: 0.8109     
Epoch 5/100
24000/24000 [==============================] - 1s - loss: 0.4644 - acc: 0.8107     
Epoch 6/100
24000/24000 [==============================] - 1s - loss: 0.4647 - acc: 0.8111     
Epoch 7/100
24000/24000 [==============================] - 1s - loss: 0.4639 - acc: 0.8128     
Epoch 8/100
24000/24000 [==============================] - 1s - loss: 0.4641 - acc: 0.8121     
Epoch 9/100
24000/24000 [==============================] - 1s - loss: 0.4644 - acc: 0.8115     - ETA: 1s - l
Epoch 10/100
24000/24000 [==============================] - 1s - loss: 0.4640 - acc: 0.8131     - ETA: 0s - loss: 0.4652 - 

24000/24000 [==============================] - 1s - loss: 0.4220 - acc: 0.8242     - ETA: 0s - loss: 0.4237 - acc: 0 - ETA: 0s - loss: 0.4238 - acc: 
Epoch 73/100
24000/24000 [==============================] - 1s - loss: 0.4218 - acc: 0.8252     - ETA: 1s - loss: 0.4258 -  - ETA: 1s - los
Epoch 74/100
24000/24000 [==============================] - 1s - loss: 0.4219 - acc: 0.8241     - ETA: 0s - loss: 0.4258 - acc: - ETA: 0s - loss: 0.4228 - ac
Epoch 75/100
24000/24000 [==============================] - 1s - loss: 0.4212 - acc: 0.8238     - ETA: 0s - loss: 0.41
Epoch 76/100
24000/24000 [==============================] - 1s - loss: 0.4218 - acc: 0.8236     - ETA: 1s - loss: 0.4207 - acc:  - ETA: 0s - loss: 0.4225 - acc: 0 - ETA: 0s - loss: 0.4239 - acc: - ETA: 0s - loss: 0.4216 - acc: 0.823 - ETA: 0s - loss: 0.4222 - acc: 0.8
Epoch 77/100
24000/24000 [==============================] - 1s - loss: 0.4212 - acc: 0.8237     - ETA: 1s - loss: 0.4116 - acc: 0.82 - ETA: 1s - loss - ETA: 0s - lo

In [160]:
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [161]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [162]:
accuracy_score(Y_pred, Y_test)

0.81599999999999995

In [163]:
confusion_matrix(Y_pred, Y_test)

array([[4432,  898],
       [ 206,  464]], dtype=int64)