## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df = pd.read_csv('Qualitative_Bankruptcy.data.txt', header = None)
df.shape

(250, 7)

In [6]:
df.head()

0  1  2  3  4  5   6
0  P  P  A  A  A  P  NB
1  N  N  A  A  A  N  NB
2  A  A  A  A  A  A  NB
3  P  P  P  P  P  P  NB
4  N  N  P  P  P  N  NB

## Create X and Y

In [7]:
X = df.iloc[:, 0:6].values
Y = df.iloc[:, 6].values

In [8]:
Y.shape

(250,)

In [9]:
X.shape

(250, 6)

In [10]:
X[0]

array(['P', 'P', 'A', 'A', 'A', 'P'], dtype=object)

In [11]:
Y[0]

'NB'

## Preprocess the data

In [12]:
le_Y = LabelEncoder()

In [13]:
Y = le_Y.fit_transform(Y)

In [14]:
Y[0]

1

In [15]:
def encoder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])

In [16]:
for i in range(0, 6):
    encoder_X(i)

In [17]:
X[0]

array([2, 2, 0, 0, 0, 2], dtype=object)

In [18]:
ohe_X = OneHotEncoder(categorical_features = [5])

In [19]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 7)

In [20]:
ohe_X = OneHotEncoder(categorical_features = [6])

In [21]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 8)

In [22]:
ohe_X = OneHotEncoder(categorical_features = [7])

In [23]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 9)

In [24]:
ohe_X = OneHotEncoder(categorical_features = [8])

In [25]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 10)

In [26]:
ohe_X = OneHotEncoder(categorical_features = [9])

In [27]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 11)

In [28]:
ohe_X = OneHotEncoder(categorical_features = [10])

In [29]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 12)

## Create Train and Test data

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [31]:
X_train.shape

(200, 12)

In [32]:
X_test.shape

(50, 12)

In [33]:
Y_train.shape

(200,)

In [34]:
Y_test.shape

(50,)

In [35]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
1  114
0   86

In [36]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
1  29
0  21

## Decision Tree Classifier

In [37]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [38]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [39]:
Y_pred_dt = clf_dt.predict(X_test)

In [40]:
confusion_matrix(Y_test, Y_pred_dt)

array([[21,  0],
       [ 0, 29]], dtype=int64)

## Random Forest Classifier

In [41]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [42]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [43]:
Y_pred_rf = clf_rf.predict(X_test)

In [44]:
confusion_matrix(Y_test, Y_pred_rf)

array([[21,  0],
       [ 0, 29]], dtype=int64)

## Naive Bayes Classifier

In [45]:
clf_nb = GaussianNB()

In [46]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [47]:
Y_pred_nb = clf_nb.predict(X_test)

In [48]:
confusion_matrix(Y_test, Y_pred_nb)

array([[21,  0],
       [ 0, 29]], dtype=int64)

## KNN Classifier

In [49]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [50]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [51]:
Y_pred_knn = clf_knn.predict(X_test)

In [52]:
confusion_matrix(Y_test, Y_pred_knn)

array([[21,  0],
       [ 0, 29]], dtype=int64)

## Logistic Regression

In [53]:
clf_lr = LogisticRegression()

In [54]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [55]:
Y_pred_lr = clf_lr.predict(X_test)

In [56]:
confusion_matrix(Y_test, Y_pred_lr)

array([[21,  0],
       [ 0, 29]], dtype=int64)

## SVC Linear

In [57]:
clf_lsvc = SVC(kernel = "linear")

In [58]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [59]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [60]:
confusion_matrix(Y_test, Y_pred_lsvc)

array([[21,  0],
       [ 0, 29]], dtype=int64)

## SVC Kernel

In [61]:
clf_ksvc = SVC(kernel = "rbf")

In [62]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [63]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [64]:
confusion_matrix(Y_test, Y_pred_ksvc)

array([[21,  0],
       [ 0, 29]], dtype=int64)

## Accuracy of Various Classifiers

In [65]:
model_accuracies['DT'] = accuracy_score(Y_test, Y_pred_dt)
model_accuracies['KNN'] = accuracy_score(Y_test, Y_pred_knn)
model_accuracies['KernelSVC'] = accuracy_score(Y_test, Y_pred_ksvc)
model_accuracies['LinearSVC'] = accuracy_score(Y_test, Y_pred_lsvc)
model_accuracies['LogReg'] = accuracy_score(Y_test, Y_pred_lr)
model_accuracies['NB'] = accuracy_score(Y_test, Y_pred_nb)
model_accuracies['RF'] = accuracy_score(Y_test, Y_pred_rf)
model_accuracies

{'DT': 1.0,
 'KNN': 1.0,
 'KernelSVC': 1.0,
 'LinearSVC': 1.0,
 'LogReg': 1.0,
 'NB': 1.0,
 'RF': 1.0}