## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('Qualitative_Bankruptcy.data.txt', header = None)
dataset.shape

(250, 7)

In [3]:
dataset.head()

0  1  2  3  4  5   6
0  P  P  A  A  A  P  NB
1  N  N  A  A  A  N  NB
2  A  A  A  A  A  A  NB
3  P  P  P  P  P  P  NB
4  N  N  P  P  P  N  NB

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:6].values
Y = dataset.iloc[:, 6].values

In [5]:
X.shape

(250, 6)

In [6]:
Y.shape

(250,)

In [7]:
X

array([['P', 'P', 'A', 'A', 'A', 'P'],
       ['N', 'N', 'A', 'A', 'A', 'N'],
       ['A', 'A', 'A', 'A', 'A', 'A'],
       ..., 
       ['A', 'N', 'N', 'N', 'N', 'N'],
       ['N', 'N', 'N', 'N', 'N', 'N'],
       ['P', 'N', 'N', 'N', 'A', 'A']], dtype=object)

In [8]:
Y

array(['NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB', 'NB',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',

## Preprocess the Data

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
def encoder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])

In [13]:
for i in range(0, 6):
    encoder_X(i)

In [14]:
X

array([[2, 2, 0, 0, 0, 2],
       [1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       ..., 
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [2, 1, 1, 1, 0, 0]], dtype=object)

In [15]:
ohe_X = OneHotEncoder(categorical_features = [5])

In [16]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 7)

In [17]:
ohe_X = OneHotEncoder(categorical_features = [6])

In [18]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 8)

In [19]:
ohe_X = OneHotEncoder(categorical_features = [7])

In [20]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 9)

In [21]:
ohe_X = OneHotEncoder(categorical_features = [8])

In [22]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 10)

In [23]:
ohe_X = OneHotEncoder(categorical_features = [9])

In [24]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 11)

In [25]:
ohe_X = OneHotEncoder(categorical_features = [10])

In [26]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(250, 12)

## Create Train and Test Data

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [29]:
X_train.shape

(200, 12)

In [30]:
X_test.shape

(50, 12)

In [31]:
Y_train.shape

(200,)

In [32]:
Y_test.shape

(50,)

In [33]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
1  114
0   86

In [34]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
1  29
0  21

## Create and train the ANN Classifier

In [35]:
from keras.models import Sequential
from keras.layers import Dense

In [36]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 12))

# Second Hidden Layer
#clf_ann.add(Dense(output_dim = , init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", input_dim=12, activation="relu", units=6)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="sigmoid", units=1)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
200/200 [==============================] - 0s - loss: 0.6873 - acc: 0.8200     
Epoch 2/200
200/200 [==============================] - 0s - loss: 0.6645 - acc: 0.9850     
Epoch 3/200
200/200 [==============================] - 0s - loss: 0.6192 - acc: 0.9850     
Epoch 4/200
200/200 [==============================] - 0s - loss: 0.5547 - acc: 0.9900     
Epoch 5/200
200/200 [==============================] - 0s - loss: 0.4820 - acc: 0.9900     
Epoch 6/200
200/200 [==============================] - 0s - loss: 0.4068 - acc: 0.9950     
Epoch 7/200
200/200 [==============================] - 0s - loss: 0.3402 - acc: 0.9950     
Epoch 8/200
200/200 [==============================] - 0s - loss: 0.2815 - acc: 0.9950     
Epoch 9/200
200/200 [==============================] - 0s - loss: 0.2342 - acc: 0.9950     
Epoch 10/200
200/200 [==============================] - 0s - loss: 0.1962 - acc: 0.9950     
Epoch 11/200
200/200 [==============================] - 0s - loss: 0.1660 - acc

200/200 [==============================] - 0s - loss: 0.0037 - acc: 1.0000     
Epoch 89/200
200/200 [==============================] - 0s - loss: 0.0036 - acc: 1.0000     
Epoch 90/200
200/200 [==============================] - 0s - loss: 0.0035 - acc: 1.0000         
Epoch 91/200
200/200 [==============================] - 0s - loss: 0.0034 - acc: 1.0000         
Epoch 92/200
200/200 [==============================] - 0s - loss: 0.0033 - acc: 1.0000         
Epoch 93/200
200/200 [==============================] - 0s - loss: 0.0032 - acc: 1.0000         
Epoch 94/200
200/200 [==============================] - 0s - loss: 0.0031 - acc: 1.0000     
Epoch 95/200
200/200 [==============================] - 0s - loss: 0.0030 - acc: 1.0000         
Epoch 96/200
200/200 [==============================] - 0s - loss: 0.0029 - acc: 1.0000         
Epoch 97/200
200/200 [==============================] - 0s - loss: 0.0029 - acc: 1.0000         
Epoch 98/200
200/200 [==============================] -

200/200 [==============================] - 0s - loss: 4.3953e-04 - acc: 1.0000     
Epoch 173/200
200/200 [==============================] - 0s - loss: 4.2930e-04 - acc: 1.0000     
Epoch 174/200
200/200 [==============================] - 0s - loss: 4.2114e-04 - acc: 1.0000     
Epoch 175/200
200/200 [==============================] - 0s - loss: 4.0997e-04 - acc: 1.0000 
Epoch 176/200
200/200 [==============================] - 0s - loss: 4.0273e-04 - acc: 1.0000     
Epoch 177/200
200/200 [==============================] - 0s - loss: 3.9343e-04 - acc: 1.0000     
Epoch 178/200
200/200 [==============================] - 0s - loss: 3.8236e-04 - acc: 1.0000     
Epoch 179/200
200/200 [==============================] - 0s - loss: 3.7452e-04 - acc: 1.0000 
Epoch 180/200
200/200 [==============================] - 0s - loss: 3.6436e-04 - acc: 1.0000     
Epoch 181/200
200/200 [==============================] - 0s - loss: 3.5860e-04 - acc: 1.0000     
Epoch 182/200
200/200 [===================

In [37]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [39]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [40]:
accuracy_score(Y_pred, Y_test)

1.0

In [41]:
confusion_matrix(Y_pred, Y_test)

array([[21,  0],
       [ 0, 29]], dtype=int64)