## Initialization

In [1]:
import numpy as np
import pandas as pd
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset_train = pd.read_csv("training.csv")
dataset_test = pd.read_csv("testing.csv")

In [3]:
dataset_test.head()

class    GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0     n  109.828571  183.700000   82.950000  251.750000  16.079412
1     n  130.284483  212.637931   96.896552  482.396552  21.210295
2     n  131.386555  185.466667   85.466667  419.666667  13.339998
3     n  141.345098  180.875000   81.500000  348.062500  18.213577
4     w  121.383408  218.357143  112.017857  426.607143  19.083196

In [4]:
dataset_train.head()

class    GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0     w  120.362774  205.500000  119.395349  416.581395  20.676318
1     w  124.739583  202.800000  115.333333  354.333333  16.707151
2     w  134.691964  199.285714  116.857143  477.857143  22.496712
3     w  127.946309  178.368421   92.368421  278.473684  14.977453
4     w  135.431548  197.000000  112.690476  532.952381  17.604193

In [5]:
dataset_test.shape

(500, 6)

In [6]:
dataset_train.shape

(4339, 6)

## Create X and Y

In [7]:
X_train = dataset_train.iloc[:, 1:6].values
X_test = dataset_test.iloc[:, 1:6].values
Y_train = dataset_train.iloc[:, 0].values
Y_test = dataset_test.iloc[:, 0].values

In [8]:
X_train.shape

(4339, 5)

In [9]:
X_test.shape

(500, 5)

In [10]:
Y_train.shape

(4339,)

In [11]:
Y_test.shape

(500,)

## Preprocess the Data

In [12]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
le_Y = LabelEncoder()
Y_train = le_Y.fit_transform(Y_train)
Y_test = le_Y.transform(Y_test)

In [13]:
Y_train

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [14]:
Y_test

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1,

In [15]:
# Scale the Data
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [16]:
X_train

array([[-0.47097751, -0.46759814,  0.03464194, -0.76077836, -0.38595952],
       [-0.15229913, -0.51204208, -0.032273  , -1.16373661, -0.74656234],
       [ 0.57234026, -0.56988976, -0.00717077, -0.36411431, -0.22057497],
       ..., 
       [ 0.38535484,  3.80961698,  2.9329273 , -0.22562923,  1.25723046],
       [-0.17196142, -0.30870888, -0.30983424,  0.91800376,  0.32542412],
       [-0.12081983,  5.35205636,  4.09651583, -0.6138924 , -0.86601588]])

In [17]:
X_test

array([[-1.23797968, -0.82644183, -0.5657345 , -1.82780227, -0.80359301],
       [ 0.25142864, -0.35010266, -0.33598828, -0.33472878, -0.33744717],
       [ 0.33167121, -0.79736122, -0.5242766 , -0.74080608, -1.05247149],
       ..., 
       [-0.56461831,  0.23117948, -0.06468395,  1.77319907, -0.00858807],
       [-1.3751642 , -0.60751426, -0.44959748, -0.53797205, -1.5180929 ],
       [-0.51690982, -0.85050583, -0.70846418, -1.50451627, -0.1799131 ]])

## Create and Train the Classifier

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [24]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'relu', input_dim = 5))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=5, kernel_initializer="uniform", units=3, activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=3, activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=1, activation="sigmoid")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
4339/4339 [==============================] - 0s - loss: 0.3717 - acc: 0.9829     
Epoch 2/100
4339/4339 [==============================] - 0s - loss: 0.0840 - acc: 0.9829     
Epoch 3/100
4339/4339 [==============================] - 0s - loss: 0.0740 - acc: 0.9829     
Epoch 4/100
4339/4339 [==============================] - 0s - loss: 0.0697 - acc: 0.9829     
Epoch 5/100
4339/4339 [==============================] - 0s - loss: 0.0662 - acc: 0.9829     
Epoch 6/100
4339/4339 [==============================] - 0s - loss: 0.0623 - acc: 0.9829     
Epoch 7/100
4339/4339 [==============================] - 0s - loss: 0.0582 - acc: 0.9829     
Epoch 8/100
4339/4339 [==============================] - 0s - loss: 0.0536 - acc: 0.9829     
Epoch 9/100
4339/4339 [==============================] - 0s - loss: 0.0489 - acc: 0.9829     
Epoch 10/100
4339/4339 [==============================] - 0s - loss: 0.0441 - acc: 0.9829     
Epoch 11/100
4339/4339 [==============================] - 0

4339/4339 [==============================] - 0s - loss: 0.0080 - acc: 0.9972     
Epoch 87/100
4339/4339 [==============================] - 0s - loss: 0.0082 - acc: 0.9968     
Epoch 88/100
4339/4339 [==============================] - 0s - loss: 0.0087 - acc: 0.9972     
Epoch 89/100
4339/4339 [==============================] - 0s - loss: 0.0083 - acc: 0.9972     - ETA: 0s - loss: 0.0063 - acc: 0.
Epoch 90/100
4339/4339 [==============================] - 0s - loss: 0.0081 - acc: 0.9975     
Epoch 91/100
4339/4339 [==============================] - 0s - loss: 0.0084 - acc: 0.9970     
Epoch 92/100
4339/4339 [==============================] - 0s - loss: 0.0082 - acc: 0.9970     
Epoch 93/100
4339/4339 [==============================] - 0s - loss: 0.0085 - acc: 0.9968     
Epoch 94/100
4339/4339 [==============================] - 0s - loss: 0.0083 - acc: 0.9970     
Epoch 95/100
4339/4339 [==============================] - 0s - loss: 0.0086 - acc: 0.9970     
Epoch 96/100
4339/4339 [=====

In [25]:
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_pred, Y_test)

0.86199999999999999

In [27]:
confusion_matrix(Y_pred, Y_test)

array([[300,  56],
       [ 13, 131]], dtype=int64)