## Initialization

In [1]:
import numpy as np
import pandas as pd
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset_train = pd.read_csv("training.csv")
dataset_test = pd.read_csv("testing.csv")

In [3]:
dataset_test.head()

class    GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0     n  109.828571  183.700000   82.950000  251.750000  16.079412
1     n  130.284483  212.637931   96.896552  482.396552  21.210295
2     n  131.386555  185.466667   85.466667  419.666667  13.339998
3     n  141.345098  180.875000   81.500000  348.062500  18.213577
4     w  121.383408  218.357143  112.017857  426.607143  19.083196

In [4]:
dataset_train.head()

class    GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0     w  120.362774  205.500000  119.395349  416.581395  20.676318
1     w  124.739583  202.800000  115.333333  354.333333  16.707151
2     w  134.691964  199.285714  116.857143  477.857143  22.496712
3     w  127.946309  178.368421   92.368421  278.473684  14.977453
4     w  135.431548  197.000000  112.690476  532.952381  17.604193

In [5]:
dataset_test.shape

(500, 6)

In [6]:
dataset_train.shape

(4339, 6)

## Create X and Y

In [7]:
X_train = dataset_train.iloc[:, 1:6].values
X_test = dataset_test.iloc[:, 1:6].values
Y_train = dataset_train.iloc[:, 0].values
Y_test = dataset_test.iloc[:, 0].values

In [8]:
X_train.shape

(4339, 5)

In [9]:
X_test.shape

(500, 5)

In [10]:
Y_train.shape

(4339,)

In [11]:
Y_test.shape

(500,)

## Preprocess the Data

In [12]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
le_Y = LabelEncoder()
Y_train = le_Y.fit_transform(Y_train)
Y_test = le_Y.transform(Y_test)

In [13]:
Y_train[0]

1

In [14]:
Y_test[0]

0

In [15]:
# Scale the Data
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [16]:
X_train[0]

array([-0.47097751, -0.46759814,  0.03464194, -0.76077836, -0.38595952])

In [17]:
X_test[0]

array([-1.23797968, -0.82644183, -0.5657345 , -1.82780227, -0.80359301])

## Create and Train the Classifier

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [19]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'relu', input_dim = 5))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Training Set
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", input_dim=5, units=3, activation="relu")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=3, activation="relu", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
4339/4339 [==============================] - 0s - loss: 0.4365 - acc: 0.9825     
Epoch 2/100
4339/4339 [==============================] - 0s - loss: 0.0927 - acc: 0.9829     
Epoch 3/100
4339/4339 [==============================] - 0s - loss: 0.0760 - acc: 0.9829     
Epoch 4/100
4339/4339 [==============================] - 0s - loss: 0.0730 - acc: 0.9829     
Epoch 5/100
4339/4339 [==============================] - 0s - loss: 0.0707 - acc: 0.9829     
Epoch 6/100
4339/4339 [==============================] - 0s - loss: 0.0680 - acc: 0.9829     
Epoch 7/100
4339/4339 [==============================] - 0s - loss: 0.0651 - acc: 0.9829     
Epoch 8/100
4339/4339 [==============================] - 0s - loss: 0.0618 - acc: 0.9829     
Epoch 9/100
4339/4339 [==============================] - 0s - loss: 0.0585 - acc: 0.9829     
Epoch 10/100
4339/4339 [==============================] - 0s - loss: 0.0547 - acc: 0.9829     
Epoch 11/100
4339/4339 [==============================] - 0

4339/4339 [==============================] - 0s - loss: 0.0080 - acc: 0.9979     
Epoch 86/100
4339/4339 [==============================] - 0s - loss: 0.0080 - acc: 0.9972     
Epoch 87/100
4339/4339 [==============================] - 0s - loss: 0.0077 - acc: 0.9975     
Epoch 88/100
4339/4339 [==============================] - 0s - loss: 0.0078 - acc: 0.9977     
Epoch 89/100
4339/4339 [==============================] - 0s - loss: 0.0078 - acc: 0.9970     
Epoch 90/100
4339/4339 [==============================] - 0s - loss: 0.0080 - acc: 0.9970     
Epoch 91/100
4339/4339 [==============================] - 0s - loss: 0.0078 - acc: 0.9970     
Epoch 92/100
4339/4339 [==============================] - 0s - loss: 0.0077 - acc: 0.9972     
Epoch 93/100
4339/4339 [==============================] - 0s - loss: 0.0078 - acc: 0.9972     
Epoch 94/100
4339/4339 [==============================] - 0s - loss: 0.0071 - acc: 0.9972     
Epoch 95/100
4339/4339 [==============================] - 0s - 

In [20]:
Y_pred = clf_ann.predict(X_test)
Y_pred = (Y_pred > 0.5)

## Check the Accuracy

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test, Y_pred)

0.86199999999999999

In [22]:
confusion_matrix(Y_test, Y_pred)

array([[307,   6],
       [ 63, 124]], dtype=int64)