## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df_train = pd.read_csv('training.csv')
df_train.shape

(4339, 6)

In [6]:
df_train.head()

class    GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0     w  120.362774  205.500000  119.395349  416.581395  20.676318
1     w  124.739583  202.800000  115.333333  354.333333  16.707151
2     w  134.691964  199.285714  116.857143  477.857143  22.496712
3     w  127.946309  178.368421   92.368421  278.473684  14.977453
4     w  135.431548  197.000000  112.690476  532.952381  17.604193

In [7]:
df_test = pd.read_csv('testing.csv')
df_test.shape

(500, 6)

In [8]:
df_test.head()

class    GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0     n  109.828571  183.700000   82.950000  251.750000  16.079412
1     n  130.284483  212.637931   96.896552  482.396552  21.210295
2     n  131.386555  185.466667   85.466667  419.666667  13.339998
3     n  141.345098  180.875000   81.500000  348.062500  18.213577
4     w  121.383408  218.357143  112.017857  426.607143  19.083196

## Create Train and Test data

In [9]:
X_train = df_train.iloc[:, 1:6].values
X_test = df_test.iloc[:, 1:6].values
Y_train = df_train.iloc[:, 0].values
Y_test = df_test.iloc[:, 0].values

In [10]:
X_train[0]

array([ 120.3627737 ,  205.5       ,  119.3953488 ,  416.5813953 ,
         20.67631835])

In [11]:
X_test[0]

array([ 109.8285714,  183.7      ,   82.95     ,  251.75     ,   16.0794123])

In [12]:
Y_train[0]

'w'

In [13]:
Y_test[0]

'n'

## Preprocess the data

In [14]:
le_Y = LabelEncoder()
Y_train = le_Y.fit_transform(Y_train)
Y_test = le_Y.transform(Y_test)

In [15]:
Y_train[0]

1

In [16]:
Y_test[0]

0

In [17]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  4265
1    74

In [18]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  313
1  187

In [19]:
# Scale the Data
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [20]:
X_train[0]

array([-0.47097751, -0.46759814,  0.03464194, -0.76077836, -0.38595952])

In [21]:
X_test[0]

array([-1.23797968, -0.82644183, -0.5657345 , -1.82780227, -0.80359301])

## Decision Tree Classifier

In [22]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [23]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [24]:
Y_pred_dt = clf_dt.predict(X_test)

In [25]:
confusion_matrix(Y_test, Y_pred_dt)

array([[304,   9],
       [ 73, 114]], dtype=int64)

## Random Forest Classifier

In [26]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [27]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [28]:
Y_pred_rf = clf_rf.predict(X_test)

In [29]:
confusion_matrix(Y_test, Y_pred_rf)

array([[313,   0],
       [112,  75]], dtype=int64)

## Naive Bayes Classifier

In [30]:
clf_nb = GaussianNB()

In [31]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [32]:
Y_pred_nb = clf_nb.predict(X_test)

In [33]:
confusion_matrix(Y_test, Y_pred_nb)

array([[304,   9],
       [160,  27]], dtype=int64)

## KNN Classifier

In [34]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [35]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [36]:
Y_pred_knn = clf_knn.predict(X_test)

In [37]:
confusion_matrix(Y_test, Y_pred_knn)

array([[310,   3],
       [160,  27]], dtype=int64)

## Logistic Regression

In [38]:
clf_lr = LogisticRegression()

In [39]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [40]:
Y_pred_lr = clf_lr.predict(X_test)

In [41]:
confusion_matrix(Y_test, Y_pred_lr)

array([[311,   2],
       [181,   6]], dtype=int64)

## SVC Linear

In [42]:
clf_lsvc = SVC(kernel = "linear")

In [43]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [44]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [45]:
confusion_matrix(Y_test, Y_pred_lsvc)

array([[312,   1],
       [182,   5]], dtype=int64)

## SVC Kernel

In [46]:
clf_ksvc = SVC(kernel = "rbf")

In [47]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [48]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [49]:
confusion_matrix(Y_test, Y_pred_ksvc)

array([[313,   0],
       [148,  39]], dtype=int64)

## Accuracy of Various Classifiers

In [50]:
model_accuracies['DT'] = accuracy_score(Y_test, Y_pred_dt)
model_accuracies['KNN'] = accuracy_score(Y_test, Y_pred_knn)
model_accuracies['KernelSVC'] = accuracy_score(Y_test, Y_pred_ksvc)
model_accuracies['LinearSVC'] = accuracy_score(Y_test, Y_pred_lsvc)
model_accuracies['LogReg'] = accuracy_score(Y_test, Y_pred_lr)
model_accuracies['NB'] = accuracy_score(Y_test, Y_pred_nb)
model_accuracies['RF'] = accuracy_score(Y_test, Y_pred_rf)
model_accuracies

{'DT': 0.83599999999999997,
 'KNN': 0.67400000000000004,
 'KernelSVC': 0.70399999999999996,
 'LinearSVC': 0.63400000000000001,
 'LogReg': 0.63400000000000001,
 'NB': 0.66200000000000003,
 'RF': 0.77600000000000002}