## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('machine.data', header = None)
dataset.shape

(209, 10)

In [3]:
dataset.head()

0        1    2     3      4    5   6    7    8    9
0  adviser    32/60  125   256   6000  256  16  128  198  199
1   amdahl   470v/7   29  8000  32000   32   8   32  269  253
2   amdahl  470v/7a   29  8000  32000   32   8   32  220  253
3   amdahl  470v/7b   29  8000  32000   32   8   32  172  253
4   amdahl  470v/7c   29  8000  16000   32   8   16  132  132

## Create X and Y

In [4]:
X = dataset.iloc[:, 2:8].values
Y = dataset.iloc[:, 8].values

In [5]:
X.shape

(209, 6)

In [6]:
Y.shape

(209,)

In [7]:
X

array([[  125,   256,  6000,   256,    16,   128],
       [   29,  8000, 32000,    32,     8,    32],
       [   29,  8000, 32000,    32,     8,    32],
       ..., 
       [  125,  2000,  8000,     0,     2,    14],
       [  480,   512,  8000,    32,     0,     0],
       [  480,  1000,  4000,     0,     0,     0]], dtype=int64)

In [8]:
Y

array([ 198,  269,  220,  172,  132,  318,  367,  489,  636, 1144,   38,
         40,   92,  138,   10,   35,   19,   28,   31,  120,   30,   33,
         61,   76,   23,   69,   33,   27,   77,   27,  274,  368,   32,
         63,  106,  208,   20,   29,   71,   26,   36,   40,   52,   60,
         72,   72,   18,   20,   40,   62,   24,   24,  138,   36,   26,
         60,   71,   12,   14,   20,   16,   22,   36,  144,  144,  259,
         17,   26,   32,   32,   62,   64,   22,   36,   44,   50,   45,
         53,   36,   84,   16,   38,   38,   16,   22,   29,   40,   35,
        134,   66,  141,  189,   22,  132,  237,  465,  465,  277,  185,
          6,   24,   45,    7,   13,   16,   32,   32,   11,   11,   18,
         22,   37,   40,   34,   50,   76,   66,   24,   49,   66,  100,
        133,   12,   18,   20,   27,   45,   56,   70,   80,  136,   16,
         26,   32,   45,   54,   65,   30,   50,   40,   62,   60,   50,
         66,   86,   74,   93,  111,  143,  105,  2

## Preprocess the Data

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
sc_X = StandardScaler()

In [11]:
X = sc_X.fit_transform(X)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [12]:
X

array([[-0.30358614, -0.67502598, -0.49546221,  5.69420785,  1.66198873,
         4.23103334],
       [-0.67332952,  1.32629082,  1.72704937,  0.16762947,  0.48550899,
         0.52947875],
       [-0.67332952,  1.32629082,  1.72704937,  0.16762947,  0.48550899,
         0.52947875],
       ..., 
       [-0.30358614, -0.2243162 , -0.32449978, -0.62188173, -0.39685082,
        -0.16456273],
       [ 1.06369405, -0.60886675, -0.32449978,  0.16762947, -0.69097076,
        -0.70437278],
       [ 1.06369405, -0.48275071, -0.66642464, -0.62188173, -0.69097076,
        -0.70437278]])

## Create Train and Test Data

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [15]:
X_train.shape

(167, 6)

In [16]:
X_test.shape

(42, 6)

In [17]:
Y_train.shape

(167,)

In [18]:
Y_test.shape

(42,)

## Create and train the ANN Regressor

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [65]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 56, init = 'uniform', activation = 'relu', input_dim = 6))

# Second Hidden Layer
#clf_ann.add(Dense(output_dim = 56, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 1, init = 'uniform'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 5, nb_epoch = 200)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", input_dim=6, activation="relu", units=56)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=1)`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
167/167 [==============================] - 0s - loss: 37303.9545     
Epoch 2/200
167/167 [==============================] - 0s - loss: 37245.2667    
Epoch 3/200
167/167 [==============================] - 0s - loss: 37130.4369    
Epoch 4/200
167/167 [==============================] - 0s - loss: 36912.3248     
Epoch 5/200
167/167 [==============================] - 0s - loss: 36570.6495     
Epoch 6/200
167/167 [==============================] - 0s - loss: 36139.5724    
Epoch 7/200
167/167 [==============================] - 0s - loss: 35604.3537     
Epoch 8/200
167/167 [==============================] - 0s - loss: 34994.4147     
Epoch 9/200
167/167 [==============================] - 0s - loss: 34309.1050    
Epoch 10/200
167/167 [==============================] - 0s - loss: 33559.1244    
Epoch 11/200
167/167 [==============================] - 0s - loss: 32715.7921     
Epoch 12/200
167/167 [==============================] - 0s - loss: 31779.5789    
Epoch 13/200
167/16

167/167 [==============================] - 0s - loss: 3551.6529     
Epoch 102/200
167/167 [==============================] - 0s - loss: 3526.2436    
Epoch 103/200
167/167 [==============================] - 0s - loss: 3506.7644    
Epoch 104/200
167/167 [==============================] - 0s - loss: 3497.1814     
Epoch 105/200
167/167 [==============================] - 0s - loss: 3502.0646     
Epoch 106/200
167/167 [==============================] - 0s - loss: 3461.0017     
Epoch 107/200
167/167 [==============================] - 0s - loss: 3437.0091     
Epoch 108/200
167/167 [==============================] - 0s - loss: 3425.7638     
Epoch 109/200
167/167 [==============================] - 0s - loss: 3416.9635    
Epoch 110/200
167/167 [==============================] - 0s - loss: 3393.8019     
Epoch 111/200
167/167 [==============================] - 0s - loss: 3371.6241    
Epoch 112/200
167/167 [==============================] - 0s - loss: 3362.5753    
Epoch 113/200
167/167 [

167/167 [==============================] - 0s - loss: 2620.8141    
Epoch 200/200
167/167 [==============================] - 0s - loss: 2617.2283    


In [66]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)

## Check the Accuracy

In [67]:
from sklearn.metrics import mean_squared_error, r2_score

In [68]:
mean_squared_error(Y_pred, Y_test)

1837.5050761532457

In [69]:
r2_score(Y_pred, Y_test)

0.91721816504302345