## Initialization

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [3]:
model_accuracies = {'LogReg':1, 'DT':1, 'RF':1, 'LinearSVC':1, 'KernelSVC':1, 'NB':1, 'KNN':1}

## Importing the data

In [4]:
dataset = pd.read_csv('PhishingData.csv', header = None)
dataset.shape

(1353, 10)

In [5]:
dataset.head()

0  1  2  3  4  5  6  7  8  9
0  1 -1  1 -1 -1  1  1  1  0  0
1 -1 -1 -1 -1 -1  0  1  1  1  1
2  1 -1  0  0 -1  0 -1  1  0  1
3  1  0  1 -1 -1  0  1  1  0  0
4 -1 -1  1 -1  0  0 -1  1  0  1

## Create X and Y

In [6]:
X = dataset.iloc[:, 0:9].values
Y = dataset.iloc[:, 9].values

In [7]:
X.shape

(1353, 9)

In [8]:
Y.shape

(1353,)

In [9]:
X[0]

array([ 1, -1,  1, -1, -1,  1,  1,  1,  0], dtype=int64)

In [10]:
Y

array([ 0,  1,  1, ...,  1,  1, -1], dtype=int64)

## Preprocess the Data

In [11]:
le_Y = LabelEncoder()

In [12]:
Y = le_Y.fit_transform(Y)
Y

array([1, 2, 2, ..., 2, 2, 0], dtype=int64)

In [13]:
def encoder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])

In [14]:
for x in range(0, 9):
    encoder_X(x)

In [15]:
X[0]

array([2, 0, 2, 0, 0, 2, 2, 1, 0], dtype=int64)

In [16]:
pd.DataFrame(pd.DataFrame(X[:, 6])[0].value_counts())

0
1  563
0  431
2  359

In [17]:
ohe_X = OneHotEncoder(categorical_features = [6])

In [18]:
X = ohe_X.fit_transform(X).toarray()
X[0]

array([ 0.,  0.,  1.,  2.,  0.,  2.,  0.,  0.,  2.,  1.,  0.])

In [19]:
X.shape

(1353, 11)

In [20]:
X = X[:, 1:]
X.shape

(1353, 10)

In [21]:
pd.DataFrame(pd.DataFrame(X[:, 7])[0].value_counts())

0
1.0  473
0.0  440
2.0  440

In [22]:
ohe_X = OneHotEncoder(categorical_features = [7])

In [23]:
X = ohe_X.fit_transform(X).toarray()
X.shape

(1353, 12)

In [24]:
X = X[:, 1:]
X.shape

(1353, 11)

In [25]:
pd.DataFrame(pd.DataFrame(X[:, 8])[0].value_counts())

0
0.0  610
2.0  576
1.0  167

In [26]:
ohe_X = OneHotEncoder(categorical_features = [8])

In [27]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 12)

In [28]:
pd.DataFrame(pd.DataFrame(X[:, 9])[0].value_counts())

0
0.0  617
1.0  421
2.0  315

In [29]:
ohe_X = OneHotEncoder(categorical_features = [9])

In [30]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 13)

In [31]:
pd.DataFrame(pd.DataFrame(X[:, 10])[0].value_counts())

0
2.0  751
0.0  308
1.0  294

In [32]:
ohe_X = OneHotEncoder(categorical_features = [10])

In [33]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 14)

In [34]:
pd.DataFrame(pd.DataFrame(X[:, 11])[0].value_counts())

0
1.0  639
0.0  532
2.0  182

In [35]:
ohe_X = OneHotEncoder(categorical_features = [11])

In [36]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 15)

In [37]:
pd.DataFrame(pd.DataFrame(X[:, 12])[0].value_counts())

0
2.0  767
0.0  445
1.0  141

In [38]:
ohe_X = OneHotEncoder(categorical_features = [12])

In [39]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 16)

## Create Train and Test Data

In [40]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [41]:
X_train.shape

(1082, 16)

In [42]:
X_test.shape

(271, 16)

In [43]:
Y_train.shape

(1082,)

In [44]:
Y_test.shape

(271,)

In [45]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  560
2  433
1   89

In [46]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  142
2  115
1   14

## DecisionTree

In [47]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [48]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [49]:
Y_pred_dt = clf_dt.predict(X_test)

In [50]:
confusion_matrix(Y_test, Y_pred_dt)

array([[127,   3,  12],
       [  2,  12,   0],
       [  5,   2, 108]], dtype=int64)

## Random Forest

In [51]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [52]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [53]:
Y_pred_rf = clf_rf.predict(X_test)

In [54]:
confusion_matrix(Y_test, Y_pred_rf)

array([[125,   2,  15],
       [  4,  10,   0],
       [  7,   3, 105]], dtype=int64)

## Naive Bayes

In [55]:
clf_nb = GaussianNB()

In [56]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [57]:
Y_pred_nb = clf_nb.predict(X_test)

In [58]:
confusion_matrix(Y_test, Y_pred_nb)

array([[ 39,  60,  43],
       [  0,  10,   4],
       [  0,  11, 104]], dtype=int64)

## KNN

In [59]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [60]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [61]:
Y_pred_knn = clf_knn.predict(X_test)

In [62]:
confusion_matrix(Y_test, Y_pred_knn)

array([[127,   1,  14],
       [  7,   4,   3],
       [  4,   2, 109]], dtype=int64)

## Logistic Regression

In [63]:
clf_lr = LogisticRegression()

In [64]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [65]:
Y_pred_lr = clf_lr.predict(X_test)

In [66]:
confusion_matrix(Y_test, Y_pred_lr)

array([[134,   0,   8],
       [  9,   0,   5],
       [  7,   0, 108]], dtype=int64)

## Linear SVC

In [67]:
clf_lsvc = SVC(kernel = 'linear')

In [68]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [69]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [70]:
confusion_matrix(Y_test, Y_pred_lsvc)

array([[133,   0,   9],
       [  8,   2,   4],
       [  2,   1, 112]], dtype=int64)

## Kernel SVC

In [71]:
clf_ksvc = SVC(kernel = 'rbf')

In [72]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [73]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [74]:
confusion_matrix(Y_test, Y_pred_ksvc)

array([[133,   0,   9],
       [  9,   0,   5],
       [  3,   0, 112]], dtype=int64)

## Accuracy of Various Models

In [75]:
model_accuracies['DT'] = accuracy_score(Y_test, Y_pred_dt)
model_accuracies['KNN'] = accuracy_score(Y_test, Y_pred_knn)
model_accuracies['KernelSVC'] = accuracy_score(Y_test, Y_pred_ksvc)
model_accuracies['LinearSVC'] = accuracy_score(Y_test, Y_pred_lsvc)
model_accuracies['LogReg'] = accuracy_score(Y_test, Y_pred_lr)
model_accuracies['NB'] = accuracy_score(Y_test, Y_pred_nb)
model_accuracies['RF'] = accuracy_score(Y_test, Y_pred_rf)
model_accuracies

{'DT': 0.91143911439114389,
 'KNN': 0.88560885608856088,
 'KernelSVC': 0.90405904059040587,
 'LinearSVC': 0.91143911439114389,
 'LogReg': 0.8929889298892989,
 'NB': 0.56457564575645758,
 'RF': 0.88560885608856088}