## Initialization

In [1]:
import pandas as pd
import numpy as np
import keras

Using Theano backend.


## Importing the Data

In [2]:
dataset = pd.read_csv('PhishingData.csv', header = None)
dataset.shape

(1353, 10)

In [3]:
dataset.head()

0  1  2  3  4  5  6  7  8  9
0  1 -1  1 -1 -1  1  1  1  0  0
1 -1 -1 -1 -1 -1  0  1  1  1  1
2  1 -1  0  0 -1  0 -1  1  0  1
3  1  0  1 -1 -1  0  1  1  0  0
4 -1 -1  1 -1  0  0 -1  1  0  1

## Create X and Y

In [4]:
X = dataset.iloc[:, 0:9].values
Y = dataset.iloc[:, 9].values

In [5]:
X.shape

(1353, 9)

In [6]:
Y.shape

(1353,)

In [7]:
X

array([[ 1, -1,  1, ...,  1,  1,  0],
       [-1, -1, -1, ...,  1,  1,  1],
       [ 1, -1,  0, ..., -1,  1,  0],
       ..., 
       [-1,  0, -1, ..., -1, -1,  0],
       [ 0,  0,  1, ..., -1,  1,  0],
       [ 1,  0,  1, ..., -1, -1,  0]], dtype=int64)

In [8]:
Y

array([ 0,  1,  1, ...,  1,  1, -1], dtype=int64)

## Preprocess the Data

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [10]:
le_Y = LabelEncoder()

In [11]:
Y = le_Y.fit_transform(Y)
Y

array([1, 2, 2, ..., 2, 2, 0], dtype=int64)

In [12]:
Y = Y.reshape(len(Y), 1)
ohe_Y = OneHotEncoder(categorical_features = [0])

In [13]:
Y = ohe_Y.fit_transform(Y).toarray()
Y

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [14]:
def encoder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])

In [15]:
for x in range(0, 9):
    encoder_X(x)

In [16]:
X

array([[2, 0, 2, ..., 2, 1, 0],
       [0, 0, 0, ..., 2, 1, 1],
       [2, 0, 1, ..., 0, 1, 0],
       ..., 
       [0, 1, 0, ..., 0, 0, 0],
       [1, 1, 2, ..., 0, 1, 0],
       [2, 1, 2, ..., 0, 0, 0]], dtype=int64)

In [17]:
ohe_X = OneHotEncoder(categorical_features = [6])

In [18]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 10)

In [19]:
ohe_X = OneHotEncoder(categorical_features = [7])

In [20]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 11)

In [21]:
ohe_X = OneHotEncoder(categorical_features = [8])

In [22]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 12)

In [23]:
ohe_X = OneHotEncoder(categorical_features = [9])

In [24]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 13)

In [25]:
ohe_X = OneHotEncoder(categorical_features = [10])

In [26]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 14)

In [27]:
ohe_X = OneHotEncoder(categorical_features = [11])

In [28]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 15)

In [29]:
ohe_X = OneHotEncoder(categorical_features = [12])

In [30]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(1353, 16)

## Create Train and Test Data

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [33]:
X_train.shape

(1082, 16)

In [34]:
X_test.shape

(271, 16)

In [35]:
Y_train.shape

(1082, 3)

In [36]:
Y_test.shape

(271, 3)

## Create and train the ANN Classifier

In [37]:
from keras.models import Sequential
from keras.layers import Dense

In [38]:
clf_ann = Sequential()

# First Hidden Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu', input_dim = 16))

# Second Hidden Layer
clf_ann.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu'))

# Output Layer
clf_ann.add(Dense(output_dim = 3, init = 'uniform', activation = 'softmax'))

# Compile the ANN
clf_ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Train the ANN on the Train Data
clf_ann.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=16, activation="relu", kernel_initializer="uniform", units=10)`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=10, activation="relu", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=3, activation="softmax", kernel_initializer="uniform")`
C:\Users\user\Anaconda3\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
1082/1082 [==============================] - 0s - loss: 1.0319 - acc: 0.5148     
Epoch 2/100
1082/1082 [==============================] - 0s - loss: 0.8393 - acc: 0.5213     
Epoch 3/100
1082/1082 [==============================] - 0s - loss: 0.6949 - acc: 0.7311     
Epoch 4/100
1082/1082 [==============================] - 0s - loss: 0.5526 - acc: 0.8142     
Epoch 5/100
1082/1082 [==============================] - 0s - loss: 0.4865 - acc: 0.8373     
Epoch 6/100
1082/1082 [==============================] - 0s - loss: 0.4575 - acc: 0.8401     
Epoch 7/100
1082/1082 [==============================] - 0s - loss: 0.4413 - acc: 0.8420     
Epoch 8/100
1082/1082 [==============================] - 0s - loss: 0.4325 - acc: 0.8466     
Epoch 9/100
1082/1082 [==============================] - 0s - loss: 0.4246 - acc: 0.8438     
Epoch 10/100
1082/1082 [==============================] - 0s - loss: 0.4180 - acc: 0.8447     
Epoch 11/100
1082/1082 [==============================] - 0

1082/1082 [==============================] - 0s - loss: 0.2854 - acc: 0.8660     
Epoch 88/100
1082/1082 [==============================] - 0s - loss: 0.2839 - acc: 0.8743     
Epoch 89/100
1082/1082 [==============================] - 0s - loss: 0.2846 - acc: 0.8688     
Epoch 90/100
1082/1082 [==============================] - 0s - loss: 0.2838 - acc: 0.8678     
Epoch 91/100
1082/1082 [==============================] - 0s - loss: 0.2810 - acc: 0.8762     
Epoch 92/100
1082/1082 [==============================] - 0s - loss: 0.2797 - acc: 0.8762     
Epoch 93/100
1082/1082 [==============================] - 0s - loss: 0.2778 - acc: 0.8734     
Epoch 94/100
1082/1082 [==============================] - 0s - loss: 0.2788 - acc: 0.8789     
Epoch 95/100
1082/1082 [==============================] - 0s - loss: 0.2784 - acc: 0.8780     
Epoch 96/100
1082/1082 [==============================] - 0s - loss: 0.2767 - acc: 0.8808     
Epoch 97/100
1082/1082 [==============================] - 0s - 

In [39]:
# Test the ANN on the Test Data
Y_pred = clf_ann.predict(X_test)
Y_pred_class = np.argmax(Y_pred, axis = 1)
Y_test_class = np.argmax(Y_test, axis = 1)

## Check the Accuracy

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [41]:
accuracy_score(Y_pred_class, Y_test_class)

0.89667896678966785

In [42]:
confusion_matrix(Y_pred_class, Y_test_class)

array([[127,   4,   2],
       [  1,   7,   4],
       [ 14,   3, 109]], dtype=int64)