## Initialization

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [4]:
model_accuracies = {'KNN':1, 'LogReg':1, 'DT':1, 'RF':1, 'NB':1, 'LinearSVC':1, 'KernelSVC':1}

## Importing the Data

In [5]:
df = pd.read_csv('wine.data', header = None)
df.shape

(178, 14)

In [6]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

## Creating X and Y

In [7]:
Y = df.iloc[:, 0]
Y.shape

(178,)

In [8]:
Y

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
148    3
149    3
150    3
151    3
152    3
153    3
154    3
155    3
156    3
157    3
158    3
159    3
160    3
161    3
162    3
163    3
164    3
165    3
166    3
167    3
168    3
169    3
170    3
171    3
172    3
173    3
174    3
175    3
176    3
177    3
Name: 0, Length: 178, dtype: int64

In [9]:
X = df.iloc[:, 1:]
X.shape

(178, 13)

In [10]:
X

1     2     3     4    5     6     7     8     9          10    11  \
0    14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.640000  1.04   
1    13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.380000  1.05   
2    13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.680000  1.03   
3    14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.800000  0.86   
4    13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.320000  1.04   
5    14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.750000  1.05   
6    14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98   5.250000  1.02   
7    14.06  2.15  2.61  17.6  121  2.60  2.51  0.31  1.25   5.050000  1.06   
8    14.83  1.64  2.17  14.0   97  2.80  2.98  0.29  1.98   5.200000  1.08   
9    13.86  1.35  2.27  16.0   98  2.98  3.15  0.22  1.85   7.220000  1.01   
10   14.10  2.16  2.30  18.0  105  2.95  3.32  0.22  2.38   5.750000  1.25   
11   14.12  1.48  2.32  16.8   95  2.20  2.43  0.26  1.57   5.000000  1.17   
12   13.75  1.73  2.41  16.0   89  2.60  2.76  0.29  1.81   5.600000  1.15   
13   14.75  1.73  2.39  11.4   91  3.10  3.69  0.43  2.81   5.400000  1.25   
14   14.38  1.87  2.38  12.0  102  3.30  3.64  0.29  2.96   7.500000  1.20   
15   13.63  1.81  2.70  17.2  112  2.85  2.91  0.30  1.46   7.300000  1.28   
16   14.30  1.92  2.72  20.0  120  2.80  3.14  0.33  1.97   6.200000  1.07   
17   13.83  1.57  2.62  20.0  115  2.95  3.40  0.40  1.72   6.600000  1.13   
18   14.19  1.59  2.48  16.5  108  3.30  3.93  0.32  1.86   8.700000  1.23   
19   13.64  3.10  2.56  15.2  116  2.70  3.03  0.17  1.66   5.100000  0.96   
20   14.06  1.63  2.28  16.0  126  3.00  3.17  0.24  2.10   5.650000  1.09   
21   12.93  3.80  2.65  18.6  102  2.41  2.41  0.25  1.98   4.500000  1.03   
22   13.71  1.86  2.36  16.6  101  2.61  2.88  0.27  1.69   3.800000  1.11   
23   12.85  1.60  2.52  17.8   95  2.48  2.37  0.26  1.46   3.930000  1.09   
24   13.50  1.81  2.61  20.0   96  2.53  2.61  0.28  1.66   3.520000  1.12   
25   13.05  2.05  3.22  25.0  124  2.63  2.68  0.47  1.92   3.580000  1.13   
26   13.39  1.77  2.62  16.1   93  2.85  2.94  0.34  1.45   4.800000  0.92   
27   13.30  1.72  2.14  17.0   94  2.40  2.19  0.27  1.35   3.950000  1.02   
28   13.87  1.90  2.80  19.4  107  2.95  2.97  0.37  1.76   4.500000  1.25   
29   14.02  1.68  2.21  16.0   96  2.65  2.33  0.26  1.98   4.700000  1.04   
..     ...   ...   ...   ...  ...   ...   ...   ...   ...        ...   ...   
148  13.32  3.24  2.38  21.5   92  1.93  0.76  0.45  1.25   8.420000  0.55   
149  13.08  3.90  2.36  21.5  113  1.41  1.39  0.34  1.14   9.400000  0.57   
150  13.50  3.12  2.62  24.0  123  1.40  1.57  0.22  1.25   8.600000  0.59   
151  12.79  2.67  2.48  22.0  112  1.48  1.36  0.24  1.26  10.800000  0.48   
152  13.11  1.90  2.75  25.5  116  2.20  1.28  0.26  1.56   7.100000  0.61   
153  13.23  3.30  2.28  18.5   98  1.80  0.83  0.61  1.87  10.520000  0.56   
154  12.58  1.29  2.10  20.0  103  1.48  0.58  0.53  1.40   7.600000  0.58   
155  13.17  5.19  2.32  22.0   93  1.74  0.63  0.61  1.55   7.900000  0.60   
156  13.84  4.12  2.38  19.5   89  1.80  0.83  0.48  1.56   9.010000  0.57   
157  12.45  3.03  2.64  27.0   97  1.90  0.58  0.63  1.14   7.500000  0.67   
158  14.34  1.68  2.70  25.0   98  2.80  1.31  0.53  2.70  13.000000  0.57   
159  13.48  1.67  2.64  22.5   89  2.60  1.10  0.52  2.29  11.750000  0.57   
160  12.36  3.83  2.38  21.0   88  2.30  0.92  0.50  1.04   7.650000  0.56   
161  13.69  3.26  2.54  20.0  107  1.83  0.56  0.50  0.80   5.880000  0.96   
162  12.85  3.27  2.58  22.0  106  1.65  0.60  0.60  0.96   5.580000  0.87   
163  12.96  3.45  2.35  18.5  106  1.39  0.70  0.40  0.94   5.280000  0.68   
164  13.78  2.76  2.30  22.0   90  1.35  0.68  0.41  1.03   9.580000  0.70   
165  13.73  4.36  2.26  22.5   88  1.28  0.47  0.52  1.15   6.620000  0.78   
166  13.45  3.70  2.60  23.0  111  1.70  0.92  0.43  1.46  10.680000  0.85   
167  12.82  3.37  2.30  19.5  

## Preprocess the Data

In [11]:
le_Y = LabelEncoder()

In [12]:
Y = le_Y.fit_transform(Y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [13]:
sc_X = StandardScaler()

In [14]:
X = sc_X.fit_transform(X)
X

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ..., 
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

## Create Train and Test data

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [16]:
X_train.shape

(142, 13)

In [17]:
X_test.shape

(36, 13)

In [18]:
Y_train.shape

(142,)

In [19]:
Y_test.shape

(36,)

In [20]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
1  58
0  49
2  35

In [21]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
2  13
1  13
0  10

## Decision Tree Classifier

In [22]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [23]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [24]:
Y_pred_dt = clf_dt.predict(X_test)

In [25]:
cm_dt = confusion_matrix(Y_pred_dt, Y_test)
cm_dt

array([[10,  1,  0],
       [ 0, 12,  0],
       [ 0,  0, 13]], dtype=int64)

## Random Forest Classifier

In [26]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [27]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [28]:
Y_pred_rf = clf_rf.predict(X_test)

In [29]:
cm_rf = confusion_matrix(Y_pred_rf, Y_test)
cm_rf

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

## Naive Bayes Classifier

In [30]:
clf_nb = GaussianNB()

In [31]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [32]:
Y_pred_nb = clf_nb.predict(X_test)

In [33]:
cm_nb = confusion_matrix(Y_pred_nb, Y_test)
cm_nb

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

## KNN Classifier

In [34]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [35]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [36]:
Y_pred_knn = clf_knn.predict(X_test)

In [37]:
cm_knn = confusion_matrix(Y_pred_knn, Y_test)
cm_knn

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

## Logistic Regression

In [38]:
clf_lr = LogisticRegression()

In [39]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [40]:
Y_pred_lr = clf_lr.predict(X_test)

In [41]:
cm_lr = confusion_matrix(Y_pred_lr, Y_test)
cm_lr

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

## SVC Linear

In [42]:
clf_lsvc = SVC(kernel = "linear")

In [43]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [44]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [45]:
cm_lsvc = confusion_matrix(Y_pred_lsvc, Y_test)
cm_lsvc

array([[10,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 12]], dtype=int64)

## SVC Kernel

In [46]:
clf_ksvc = SVC(kernel = "rbf")

In [47]:
clf_ksvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [48]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [49]:
cm_ksvc = confusion_matrix(Y_pred_ksvc, Y_test)
cm_ksvc

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

## Accuracy of Various Classifiers

In [50]:
model_accuracies['DT'] = accuracy_score(Y_pred_dt, Y_test)
model_accuracies['KNN'] = accuracy_score(Y_pred_knn, Y_test)
model_accuracies['KernelSVC'] = accuracy_score(Y_pred_ksvc, Y_test)
model_accuracies['LinearSVC'] = accuracy_score(Y_pred_lsvc, Y_test)
model_accuracies['LogReg'] = accuracy_score(Y_pred_lr, Y_test)
model_accuracies['NB'] = accuracy_score(Y_pred_nb, Y_test)
model_accuracies['RF'] = accuracy_score(Y_pred_rf, Y_test)
model_accuracies

{'DT': 0.97222222222222221,
 'KNN': 1.0,
 'KernelSVC': 1.0,
 'LinearSVC': 0.97222222222222221,
 'LogReg': 1.0,
 'NB': 1.0,
 'RF': 1.0}